<?php

/**
 * ERP module catalog and workflows for the AI assistant.
 * Derived from routes, permission registry, and feature tests.
 */
return [
    'how_to_guide' => [
        'Centrix is organized by workspaces (top bar): Retail Backoffice/POS, Hotel Backoffice/Hotel POS, Accounting, HR, Distribution/Admin depending on industry.',
        'AI assistant is available for both Retail & Distribution and Hotel & Hospitality industries when platform AI is enabled for the tenant.',
        'If you do not know where a feature lives, ask "Where is …?" — the assistant should reply with a path like /suppliers or /hospitality/front-desk.',
        'Purchasing: Suppliers at /suppliers, purchase orders (LPO) at /lpo, receive goods (GRN) at /inventory/receipts, pay suppliers at /suppliers/payments.',
        'Inventory: Current stock at /inventory/stock, adjustments at /inventory/adjustments, stock take at /inventory/stock-take, products at /products.',
        'Sales (retail): Orders at /sales/orders, POS at /sales/pos or /pos, debtors under /sales/shop-debtors/*, Sales by User report at /reports (Sales by user).',
        'Hospitality: Hotel dashboard at /hospitality, rooms /hospitality/rooms, reservations /hospitality/reservations, front desk /hospitality/front-desk, folios /hospitality/folios, housekeeping /hospitality/housekeeping, night audit /hospitality/night-audit, outlets /hospitality/outlets.',
        'Hotel POS (checks, not retail carts): /hotel-bar-pos — open/settle checks, room charge, F&B outlets. Hotel orders lists: /hospitality/orders, /hospitality/orders/hotel, /hospitality/orders/bar.',
        'Hospitality reports: occupancy KPI, arrivals/departures, folio balances, F&B by outlet/hour, open checks, voids, manager flash, EOD cashier, P&L under /reports/hospitality-*.',
        'Accounting: Chart of accounts, journals, bank reconciliation, expenses, and AR under /accounting/*.',
        'HR: Employees, today\'s attendance (/hr/attendance), previous attendance (/hr/attendance/history), leave, and payroll under /hr/*. Field attendance for mobile reps: /sales/field-attendance.',
        'Admin: Users and roles/permissions under /admin/users and /admin/roles. Organization AI settings under Organization settings → AI.',
        'Reports hub: /reports — sales, stock, payroll, hospitality, and custom report builder at /reports/builder (saved reports open at /reports/custom/{id}).',
        'Cashier sales targets/quotas are not stored as a Centrix AI metric — report actual sales with get_sales_by_cashier instead.',
        'When talking about people, use username and full name — never numeric user ids.',
        'Write formulas in plain language with real field names (Stock Value = Cost Price × Stock on Hand), never LaTeX.',
        'Units of measure (UoM): stock is stored in base (smallest) units. A UoM can define full pack (e.g. Bag), optional middle pack, and small unit (e.g. kg). conversion_factor = base units per full pack. Screens: /uoms.',
        'Employee pay: Centrix stores basic salary on employees.base_salary. Call get_employee_details for salary, allowance, department, statutory numbers, and bank accounts — do not say access is missing when the tool returns pay data.',
        'Display quantities as mixed packs (e.g. "2 Bag, 40 kg") — never invent kg vs bags; use qty_label from tools.',
        'Retail packaging: products with Sell on retail use /retail-package-settings for retail vs wholesale markup tiers. This is separate from UoM conversion. Call get_product_details for a product\'s measurements and retail packaging.',
        'Product weight (kg) on the product card is optional metadata — not the same as stock UoM unless the small packaging unit is also kg.',
    ],
    'modules' => [
        [
            'key' => 'catalogue',
            'label' => 'Product catalog',
            'paths' => ['/products', '/categories', '/uoms', '/retail-package-settings'],
            'tasks' => [
                'Create and edit products (code, name, price, VAT, reorder point)',
                'Manage categories and subcategories',
                'Configure units of measure (full / middle / small packaging) at /uoms',
                'Configure retail packaging / sell-on-retail tiers at /retail-package-settings',
                'Register products with KRA device when fiscal module is enabled',
            ],
        ],
        [
            'key' => 'sales',
            'label' => 'Sales & POS',
            'paths' => ['/sales/pos', '/sales/orders', '/customers', '/sales/shop-debtors/unpaid'],
            'tasks' => [
                'POS checkout — create cart, add lines, pay with cash/M-Pesa/voucher',
                'Backoffice sales orders — customer + line items + checkout',
                'Held orders — save_only checkout with status held (resume or cancel later)',
                'Credit sales, vouchers, loyalty points, order discounts',
                'Shop debtors queues — unpaid / partial / paid',
            ],
        ],
        [
            'key' => 'inventory',
            'label' => 'Inventory',
            'paths' => ['/inventory/stock', '/inventory/receipts', '/inventory/stock-take', '/inventory/adjustments'],
            'tasks' => [
                'View stock on hand, low-stock alerts',
                'Receive stock from LPO (GRN), transfer between branches',
                'Stock take and adjustments',
            ],
        ],
        [
            'key' => 'purchasing',
            'label' => 'Purchasing',
            'paths' => ['/suppliers', '/lpo', '/suppliers/payments', '/inventory/receipts'],
            'tasks' => [
                'Manage suppliers and local purchase orders (LPO)',
                'Receive goods (GRN), supplier payments, supplier returns',
            ],
        ],
        [
            'key' => 'accounting',
            'label' => 'Accounting',
            'paths' => ['/accounting', '/accounting/chart-of-accounts', '/accounting/journal-entries', '/expenses'],
            'tasks' => [
                'Chart of accounts, journal entries (post/reverse via operations API)',
                'Expenses, accounts receivable/payable, fiscal period close',
                'Bank reconciliation',
            ],
        ],
        [
            'key' => 'hr_payroll',
            'label' => 'HR & payroll',
            'paths' => ['/hr/employees', '/hr/departments', '/hr/payroll', '/hr/attendance', '/hr/attendance/history', '/hr/leave', '/sales/field-attendance'],
            'tasks' => [
                'Employees, departments, shifts, attendance (today + history), leave',
                'Field attendance for mobile sales reps at /sales/field-attendance',
                'Payroll runs, deductions, organization KPIs',
            ],
        ],
        [
            'key' => 'fulfillment',
            'label' => 'Logistics & dispatch',
            'paths' => ['/fulfillment/dispatch', '/fulfillment/trips', '/fulfillment/routes', '/fulfillment/drivers'],
            'tasks' => [
                'Dispatch trips, route schedules, drivers, POD capture',
            ],
        ],
        [
            'key' => 'distribution',
            'label' => 'Distribution (fulfillment)',
            'paths' => ['/fulfillment/dispatch', '/fulfillment/trips', '/fulfillment/routes'],
            'tasks' => [
                'Same as logistics & dispatch when distribution ops are enabled for the org',
            ],
        ],
        [
            'key' => 'hospitality',
            'label' => 'Hotel & hospitality',
            'paths' => [
                '/hospitality',
                '/hospitality/rooms',
                '/hospitality/reservations',
                '/hospitality/front-desk',
                '/hospitality/folios',
                '/hospitality/housekeeping',
                '/hospitality/orders',
                '/hotel-bar-pos',
            ],
            'tasks' => [
                'Rooms, reservations, front desk check-in/out, guest folios',
                'Housekeeping, night audit, outlets',
                'Hotel POS checks (bar/restaurant) and room charge — not retail carts',
                'F&B and occupancy reports under /reports/hospitality-*',
            ],
        ],
        [
            'key' => 'reports',
            'label' => 'Reports',
            'paths' => ['/reports', '/reports/builder', '/reports/sales-by-user', '/reports/daily-sales', '/reports/low-stock'],
            'tasks' => [
                'Built-in reports (sales, stock, payroll, KRA receipts)',
                'Sales by user / cashier performance',
                'Custom report builder — ask for a report name, save template, open /reports/custom/{id}',
            ],
        ],
        [
            'key' => 'admin',
            'label' => 'Administration',
            'paths' => ['/admin', '/admin/users', '/admin/roles', '/admin/attendance-clock'],
            'tasks' => [
                'Users, roles and permissions',
                'Organization settings (including AI credentials for org admins)',
                'Attendance clock administration',
            ],
        ],
    ],
    'workflows' => [
        'create_product' => [
            'summary' => 'Add a product to the catalog',
            'path' => '/products',
            'required' => ['product_name'],
            'optional' => ['product_code', 'unit_price', 'unit_id', 'subcategory_id', 'last_cost_price', 'reorder_point', 'vat_id'],
            'action' => 'create_product',
            'notes' => 'Collect details in chat first; offer inline form only when user asks (e.g. "show form"). product_code is auto-generated as a unique 6-digit SKU when omitted. unit_id from uoms, subcategory_id from subcategories, vat_id from vats.',
        ],
        'create_sales_order' => [
            'summary' => 'Create a normal sales order (checkout with payment)',
            'path' => '/sales/orders',
            'required' => ['customer_num', 'lines' => [['product_code', 'quantity']]],
            'optional' => ['payment_method_code', 'pay_now', 'is_credit_sale', 'channel'],
            'action' => 'create_sales_order',
            'notes' => 'Collect customer + line items in chat first; offer inline form only when user asks. Default: backoffice channel, CASH payment, full amount paid. Not the same as a held order.',
        ],
        'create_held_order' => [
            'summary' => 'Save an order without payment (held / save-only)',
            'path' => '/sales/orders',
            'required' => ['customer_num', 'lines' => [['product_code', 'quantity']]],
            'optional' => ['status'],
            'action' => 'create_held_order',
            'notes' => 'Collect customer + line items in chat first; offer inline form only when user asks.',
        ],
        'pos_checkout' => [
            'summary' => 'Quick POS sale — cart → lines → checkout completed',
            'path' => '/sales/pos',
            'steps' => ['Create cart (channel pos)', 'Add product lines', 'Checkout with payment_method_code CASH or M-Pesa'],
            'action' => 'create_sales_order',
            'notes' => 'Use channel pos; customer_num optional for walk-in.',
        ],
        'create_employee' => [
            'summary' => 'Add HR employee record',
            'path' => '/hr/employees',
            'required' => ['first_name', 'last_name'],
            'optional' => ['department_id', 'shift_id', 'email', 'phone', 'base_salary', 'hire_date'],
            'action' => 'create_employee',
            'notes' => 'Collect name and HR details in chat first; offer inline form only when user asks.',
        ],
        'create_supplier' => [
            'summary' => 'Add a supplier',
            'path' => '/suppliers',
            'required' => ['supplier_name'],
            'optional' => ['contact_person', 'phone', 'email', 'town', 'tax_pin', 'address'],
            'action' => 'create_supplier',
            'notes' => 'Collect supplier name and contacts in chat first; offer inline form only when user asks.',
        ],
        'create_lpo' => [
            'summary' => 'Create a purchase order (LPO) for a supplier',
            'path' => '/lpo',
            'required' => ['supplier_id'],
            'optional' => [
                'order_num',
                'due_date',
                'delivery_address',
                'reference_number',
                'terms',
                'lines' => [['product_code', 'ordered_qty', 'cost_price']],
            ],
            'action' => 'create_lpo',
            'notes' => 'Collect supplier + line items in chat first. Offer an inline form only when the user asks (e.g. "show form"). If order_num / sale_id is given, copy product lines from that sales order and use each product\'s last_cost_price. After create, open /lpo/{lpo_no}.',
        ],
        'create_report' => [
            'summary' => 'Save a custom report template — ask for a name first, then create and share /reports/custom/{id}',
            'path' => '/reports/builder',
            'required' => ['name', 'instruction'],
            'optional' => ['spec' => ['source', 'columns', 'group_by']],
            'action' => 'create_report_template',
            'notes' => 'Collect report name and instructions in chat first; offer inline form only when user asks.',
        ],
        'record_customer_payment' => [
            'summary' => 'Record a customer payment against an outstanding sale/invoice',
            'path' => '/accounting/accounts-receivable',
            'required' => ['sale_id', 'payment_method_id'],
            'optional' => ['amount', 'reference_number', 'mark_paid_full'],
            'action' => 'record_customer_payment',
            'notes' => 'Collect order and payment details in chat first; offer inline form only when user asks. Omit amount to pay the full balance_due. Requires payments.manage permission.',
        ],
        'analyze_debtors' => [
            'summary' => 'Review who owes money and open invoice balances',
            'path' => '/reports/top-debtors',
            'notes' => 'Use receivables_summary in context — top_debtors and open_invoices. No action required for read-only analysis.',
        ],
    ],
];
