<?php

/**
 * ERP navigation map for the AI assistant (mirrors web sidebar structure).
 * Each item may require a permission code; visibility is filtered per user at runtime.
 */
return [
    'sections' => [
        [
            'id' => 'dashboard',
            'label' => 'Dashboard',
            'items' => [
                ['label' => 'Business summary', 'path' => '/dashboard', 'permission' => 'dashboard.overview.view'],
                ['label' => 'Sales analytics', 'path' => '/sales', 'module' => 'sales.dashboard', 'permission' => 'dashboard.sales.view'],
                ['label' => 'Inventory analytics', 'path' => '/inventory', 'module' => 'inventory.dashboard', 'permission' => 'dashboard.inventory.view'],
                ['label' => 'Fulfillment dashboard', 'path' => '/fulfillment', 'module' => 'customers_suppliers', 'permission' => 'fulfillment.overview.view', 'requires_distribution_ops' => true],
                ['label' => 'Report overview', 'path' => '/reports', 'module' => 'reports', 'permission' => 'reports.hub.view'],
            ],
        ],
        [
            'id' => 'sales',
            'label' => 'Sales',
            'items' => [
                ['label' => 'Create order', 'path' => '/sales/pos', 'module' => 'sales.pos', 'permission' => 'pos.checkout.create'],
                ['label' => 'Cashier terminal', 'path' => '/pos', 'module' => 'sales.pos', 'permission' => 'pos.terminal.view'],
                ['label' => 'Till management', 'path' => '/sales/till-management', 'module' => 'sales.pos', 'permission' => 'pos.till_management.view'],
                ['label' => 'Sales orders', 'path' => '/sales/orders', 'module' => 'sales.backend', 'permission' => 'sales.order_queue_all.view'],
                ['label' => 'Unpaid Debtors', 'path' => '/sales/shop-debtors/unpaid', 'module' => 'sales.backend', 'permission' => 'shop_debtors.unpaid.view'],
                ['label' => 'Partially Paid Debtors', 'path' => '/sales/shop-debtors/partial', 'module' => 'sales.backend', 'permission' => 'shop_debtors.partial.view'],
                ['label' => 'Paid Debtors', 'path' => '/sales/shop-debtors/paid', 'module' => 'sales.backend', 'permission' => 'shop_debtors.paid.view'],
                ['label' => 'Customers', 'path' => '/customers', 'module' => 'customers_suppliers', 'permission' => 'customers.customers.view'],
                ['label' => 'Vouchers', 'path' => '/sales/vouchers', 'module' => 'sales.backend', 'permission' => 'sales.vouchers.view'],
                ['label' => 'Credit notes', 'path' => '/sales/returns', 'module' => 'sales.backend', 'permission' => 'sales.returns.view'],
            ],
        ],
        [
            'id' => 'inventory',
            'label' => 'Inventory & catalog',
            'items' => [
                ['label' => 'Products', 'path' => '/products', 'permission' => 'catalogue.products.view'],
                ['label' => 'Categories', 'path' => '/categories', 'permission' => 'catalogue.categories.view'],
                ['label' => 'Current stock', 'path' => '/inventory/stock', 'module' => 'inventory', 'permission' => 'inventory.stock.view'],
                ['label' => 'Stock receipts (GRN)', 'path' => '/inventory/receipts', 'module' => 'inventory', 'permission' => 'inventory.receipts.view'],
                ['label' => 'Stock adjustments', 'path' => '/inventory/adjustments', 'module' => 'inventory', 'permission' => 'inventory.adjustments.view'],
                ['label' => 'Stock take', 'path' => '/inventory/stock-take', 'module' => 'inventory', 'permission' => 'inventory.stock_take.view'],
            ],
        ],
        [
            'id' => 'purchases',
            'label' => 'Purchasing',
            'items' => [
                ['label' => 'Suppliers', 'path' => '/suppliers', 'module' => 'customers_suppliers', 'permission' => 'purchasing.suppliers.view'],
                ['label' => 'Purchase orders (LPO)', 'path' => '/lpo', 'module' => 'customers_suppliers', 'permission' => 'purchasing.lpo.view'],
                ['label' => 'Supplier payments', 'path' => '/suppliers/payments', 'module' => 'customers_suppliers', 'permission' => 'purchasing.supplier_payments.view'],
            ],
        ],
        [
            'id' => 'accounting',
            'label' => 'Accounting',
            'items' => [
                ['label' => 'Finance overview', 'path' => '/accounting', 'module' => 'accounting', 'permission' => 'accounting.dashboard.view'],
                ['label' => 'Chart of accounts', 'path' => '/accounting/chart-of-accounts', 'module' => 'accounting', 'permission' => 'accounting.chart_of_accounts.view'],
                ['label' => 'Journal entries', 'path' => '/accounting/journal-entries', 'module' => 'accounting', 'permission' => 'accounting.journal_entries.view'],
                ['label' => 'Bank reconciliation', 'path' => '/accounting/bank-reconciliation', 'module' => 'accounting', 'permission' => 'accounting.bank_reconciliation.view'],
                ['label' => 'Expenses', 'path' => '/expenses', 'module' => 'accounting', 'permission' => 'accounting.expenses.view'],
                ['label' => 'Accounts receivable', 'path' => '/accounting/accounts-receivable', 'module' => 'accounting', 'permission' => 'accounting.accounts_receivable.view'],
            ],
        ],
        [
            'id' => 'hr',
            'label' => 'Human resources',
            'items' => [
                ['label' => 'HR Overview', 'path' => '/hr', 'module' => 'hr_payroll', 'permission' => 'hr.employees.view'],
                ['label' => 'Employees', 'path' => '/hr/employees', 'module' => 'hr_payroll', 'permission' => 'hr.employees.view'],
                ['label' => 'Departments', 'path' => '/hr/departments', 'module' => 'hr_payroll', 'permission' => 'hr.departments.view'],
                ['label' => "Today's attendance", 'path' => '/hr/attendance', 'module' => 'hr_payroll', 'permission' => 'hr.attendance.view'],
                ['label' => 'Previous attendance', 'path' => '/hr/attendance/history', 'module' => 'hr_payroll', 'permission' => 'hr.attendance_history.view'],
                ['label' => 'Absents', 'path' => '/hr/absents', 'module' => 'hr_payroll', 'permission' => 'hr.absents.view'],
                ['label' => 'Lateness', 'path' => '/hr/lateness', 'module' => 'hr_payroll', 'permission' => 'hr.lateness.view'],
                ['label' => 'Field attendance', 'path' => '/sales/field-attendance', 'module' => 'sales.backend', 'permission' => 'sales.field_attendance.view'],
                ['label' => 'Leave', 'path' => '/hr/leave', 'module' => 'hr_payroll', 'permission' => 'hr.leave.view'],
                ['label' => 'Shifts', 'path' => '/hr/shifts', 'module' => 'hr_payroll', 'permission' => 'hr.shifts.view'],
                ['label' => 'Payroll', 'path' => '/hr/payroll', 'module' => 'hr_payroll', 'permission' => 'hr.payroll.view'],
            ],
        ],
        [
            'id' => 'logistics',
            'label' => 'Fulfillment',
            'requires_distribution_ops' => true,
            'items' => [
                ['label' => 'Dispatch', 'path' => '/fulfillment/dispatch', 'module' => 'customers_suppliers', 'permission' => 'fulfillment.drivers.view'],
                ['label' => 'Trips / shipment tracking', 'path' => '/fulfillment/trips', 'module' => 'customers_suppliers', 'permission' => 'fulfillment.drivers.view'],
                ['label' => 'Drivers', 'path' => '/fulfillment/drivers', 'module' => 'customers_suppliers', 'permission' => 'fulfillment.drivers.view'],
                ['label' => 'Routes', 'path' => '/fulfillment/routes', 'module' => 'customers_suppliers', 'permission' => 'fulfillment.routes.view'],
            ],
        ],
        [
            'id' => 'hospitality_dashboard',
            'label' => 'Hotel dashboard',
            'items' => [
                ['label' => 'Hospitality overview', 'path' => '/hospitality', 'module' => 'hospitality.dashboard', 'permission' => 'hospitality.dashboard.view'],
            ],
        ],
        [
            'id' => 'hospitality_rooms',
            'label' => 'Rooms & guests',
            'items' => [
                ['label' => 'Rooms', 'path' => '/hospitality/rooms', 'module' => 'hospitality.backend', 'permission' => 'hospitality.rooms.view'],
                ['label' => 'Reservations', 'path' => '/hospitality/reservations', 'module' => 'hospitality.backend', 'permission' => 'hospitality.reservations.view'],
                ['label' => 'Front desk', 'path' => '/hospitality/front-desk', 'module' => 'hospitality.backend', 'permission' => 'hospitality.frontdesk.view'],
                ['label' => 'Folios', 'path' => '/hospitality/folios', 'module' => 'hospitality.backend', 'permission' => 'hospitality.folios.view'],
            ],
        ],
        [
            'id' => 'hospitality_ops',
            'label' => 'Hotel operations',
            'items' => [
                ['label' => 'Housekeeping', 'path' => '/hospitality/housekeeping', 'module' => 'hospitality.backend', 'permission' => 'hospitality.housekeeping.view'],
                ['label' => 'Outlets', 'path' => '/hospitality/outlets', 'module' => 'hospitality.backend', 'permission' => 'hospitality.outlets.view'],
                ['label' => 'Night audit', 'path' => '/hospitality/night-audit', 'module' => 'hospitality.backend', 'permission' => 'hospitality.night_audit.view'],
            ],
        ],
        [
            'id' => 'hospitality_sales',
            'label' => 'Hotel sales',
            'items' => [
                ['label' => 'Hotel POS', 'path' => '/hotel-bar-pos', 'module' => 'hospitality.bar_pos', 'permission' => 'hotel_bar_pos.terminal.view'],
                ['label' => 'All checks', 'path' => '/hospitality/orders', 'module' => 'hospitality.backend', 'permission' => 'hospitality.orders.view'],
                ['label' => 'Hotel orders', 'path' => '/hospitality/orders/hotel', 'module' => 'hospitality.backend', 'permission' => 'hospitality.orders.view'],
                ['label' => 'Bar orders', 'path' => '/hospitality/orders/bar', 'module' => 'hospitality.backend', 'permission' => 'hospitality.orders.view'],
            ],
        ],
        [
            'id' => 'hospitality_catalogue',
            'label' => 'Hotel catalog',
            'items' => [
                ['label' => 'Products', 'path' => '/products', 'permission' => 'catalogue.products.view'],
                ['label' => 'Categories', 'path' => '/categories', 'permission' => 'catalogue.categories.view'],
            ],
        ],
        [
            'id' => 'hospitality_stock',
            'label' => 'Hotel stock',
            'items' => [
                ['label' => 'Current stock', 'path' => '/inventory/stock', 'module' => 'inventory', 'permission' => 'inventory.stock.view'],
                ['label' => 'Stock receipts (GRN)', 'path' => '/inventory/receipts', 'module' => 'inventory', 'permission' => 'inventory.receipts.view'],
            ],
        ],
        [
            'id' => 'hospitality_purchasing',
            'label' => 'Hotel purchasing',
            'items' => [
                ['label' => 'Suppliers', 'path' => '/suppliers', 'module' => 'customers_suppliers', 'permission' => 'purchasing.suppliers.view'],
                ['label' => 'Purchase orders (LPO)', 'path' => '/lpo', 'module' => 'customers_suppliers', 'permission' => 'purchasing.lpo.view'],
            ],
        ],
        [
            'id' => 'reports',
            'label' => 'Reports',
            'module' => 'reports',
            'items' => [
                ['label' => 'Report overview', 'path' => '/reports', 'module' => 'reports', 'permission' => 'reports.hub.view'],
                ['label' => 'Report builder', 'path' => '/reports/builder', 'module' => 'reports', 'permission' => 'reports.builder.view'],
                ['label' => 'Sales by user', 'path' => '/reports/sales-by-user', 'module' => 'reports', 'permission' => 'reports.sales_by_user.view'],
                ['label' => 'Daily sales', 'path' => '/reports/daily-sales', 'module' => 'reports', 'permission' => 'reports.daily_sales.view'],
                ['label' => 'VAT collected', 'path' => '/reports/vat-collected', 'module' => 'reports', 'permission' => 'reports.vat_collected.view'],
                ['label' => 'Low stock', 'path' => '/reports/low-stock', 'module' => 'inventory', 'permission' => 'reports.low_stock.view'],
                ['label' => 'Attendance register', 'path' => '/reports/attendance-register', 'module' => 'hr_payroll.reports', 'permission' => 'hr.attendance.view'],
                ['label' => 'Items currently in stock', 'path' => '/inventory/stock', 'module' => 'inventory', 'permission' => 'inventory.stock.view'],
                ['label' => 'Payroll summary', 'path' => '/reports/payroll-summary', 'module' => 'hr_payroll.reports', 'permission' => 'hr.payroll.view'],
                ['label' => 'Leave balance', 'path' => '/reports/leave-balance', 'module' => 'hr_payroll.reports', 'permission' => 'hr.leave.view'],
                ['label' => 'Statutory deductions', 'path' => '/reports/statutory-deductions', 'module' => 'hr_payroll.reports', 'permission' => 'hr.payroll.view'],
                ['label' => 'Bank transfer', 'path' => '/reports/bank-transfer', 'module' => 'hr_payroll.reports', 'permission' => 'hr.payroll.view'],
                ['label' => 'NSSF remittance', 'path' => '/reports/nssf-remittance', 'module' => 'hr_payroll.reports', 'permission' => 'hr.payroll.view'],
                ['label' => 'Other deductions by period', 'path' => '/reports/other-deductions', 'module' => 'hr_payroll.reports', 'permission' => 'hr.payroll.view'],
                ['label' => 'Cash advances', 'path' => '/reports/cash-advances', 'module' => 'hr_payroll.reports', 'permission' => 'hr.cash_advances.view'],
                ['label' => 'Staff turnover', 'path' => '/reports/staff-turnover', 'module' => 'hr_payroll.reports', 'permission' => 'hr.employees.view'],
                ['label' => 'Headcount', 'path' => '/reports/headcount', 'module' => 'hr_payroll.reports', 'permission' => 'hr.employees.view'],
                ['label' => 'Contract expiry', 'path' => '/reports/contract-expiry', 'module' => 'hr_payroll.reports', 'permission' => 'hr.employees.view'],
                ['label' => 'Staff turnover', 'path' => '/reports/staff-turnover', 'module' => 'hr_payroll.reports', 'permission' => 'hr.employees.view'],
                ['label' => 'Occupancy KPI', 'path' => '/reports/hospitality-kpi-occupancy', 'module' => 'hospitality.reports', 'permission' => 'hospitality.reports.view'],
                ['label' => 'Room status', 'path' => '/reports/hospitality-occupancy', 'module' => 'hospitality.reports', 'permission' => 'hospitality.reports.view'],
                ['label' => 'Arrivals & departures', 'path' => '/reports/hospitality-arrivals-departures', 'module' => 'hospitality.reports', 'permission' => 'hospitality.reports.view'],
                ['label' => 'Open folio balances', 'path' => '/reports/hospitality-folio-balances', 'module' => 'hospitality.reports', 'permission' => 'hospitality.reports.view'],
                ['label' => 'F&B check sales', 'path' => '/reports/hospitality-fnb-checks', 'module' => 'hospitality.reports', 'permission' => 'hospitality.reports.view'],
                ['label' => 'Manager flash', 'path' => '/reports/hospitality-manager-flash', 'module' => 'hospitality.reports', 'permission' => 'hospitality.reports.view'],
            ],
        ],
        [
            'id' => 'settings',
            'label' => 'Administration & settings',
            'items' => [
                ['label' => 'Admin home', 'path' => '/admin', 'module' => 'admin', 'permission' => 'admin.overview.view'],
                ['label' => 'Users', 'path' => '/admin/users', 'module' => 'admin', 'permission' => 'admin.users.view'],
                ['label' => 'Roles and permissions', 'path' => '/admin/roles', 'module' => 'admin', 'permission' => 'admin.roles.view'],
                ['label' => 'Attendance', 'path' => '/admin/attendance-clock', 'module' => 'admin', 'permission' => 'admin.attendance_clock.view'],
            ],
        ],
    ],
    'actions' => [
        [
            'type' => 'create_sales_order',
            'label' => 'Create a sales order (checkout with payment)',
            'description' => 'Normal order — customer, line items, checkout with payment. Use create_held_order only when user explicitly wants to hold/save without payment.',
            'permission' => 'sales.orders.create',
            'module' => 'sales.backend',
        ],
        [
            'type' => 'create_held_order',
            'label' => 'Save a held order (no payment yet)',
            'description' => 'Save-only checkout — use only when the user asks to hold, save for later, or defer payment.',
            'permission' => 'sales.orders.create',
            'module' => 'sales.backend',
        ],
        [
            'type' => 'create_product',
            'label' => 'Create a product',
            'description' => 'Add a new product to the catalog (code, name, price, etc.).',
            'permission' => 'catalogue.products.create',
        ],
        [
            'type' => 'create_supplier',
            'label' => 'Create a supplier',
            'description' => 'Add a new supplier for purchases and accounts payable.',
            'permission' => 'purchasing.suppliers.create',
            'module' => 'customers_suppliers',
        ],
        [
            'type' => 'create_lpo',
            'label' => 'Create a purchase order (LPO)',
            'description' => 'Create an LPO with supplier and product lines. Can seed lines from a sales order number.',
            'permission' => 'purchasing.lpo.create',
            'module' => 'customers_suppliers',
        ],
        [
            'type' => 'submit_lpo_for_approval',
            'label' => 'Submit LPO for approval',
            'description' => 'Move a draft LPO into the approval queue (or awaiting send if approval is off).',
            'permission' => 'purchasing.lpo.create',
            'module' => 'customers_suppliers',
        ],
        [
            'type' => 'approve_lpo',
            'label' => 'Approve an LPO',
            'description' => 'Approve a purchase order that is awaiting approval.',
            'permission' => 'purchasing.lpo.approve',
            'module' => 'customers_suppliers',
        ],
        [
            'type' => 'mark_lpo_sent',
            'label' => 'Mark LPO as sent',
            'description' => 'Mark an approved LPO as sent to the supplier so goods can be received.',
            'permission' => 'purchasing.lpo.edit',
            'module' => 'customers_suppliers',
        ],
        [
            'type' => 'receive_lpo_goods',
            'label' => 'Receive LPO goods',
            'description' => 'Receive remaining (or specified) quantities against an LPO into stock.',
            'permission' => 'inventory.manage',
            'module' => 'inventory',
        ],
        [
            'type' => 'create_customer',
            'label' => 'Create a customer',
            'description' => 'Add a new customer for sales and receivables.',
            'permission' => 'customers.customers.create',
            'module' => 'customers_suppliers',
        ],
        [
            'type' => 'create_employee',
            'label' => 'Create an employee',
            'description' => 'Add a new employee record in HR.',
            'permission' => 'hr.employees.create',
            'module' => 'hr_payroll',
        ],
        [
            'type' => 'create_report_template',
            'label' => 'Create a custom report',
            'description' => 'Save a report builder template.',
            'permission' => 'reports.builder.create',
            'module' => 'reports',
        ],
        [
            'type' => 'record_customer_payment',
            'label' => 'Record a customer payment (full or partial)',
            'description' => 'Apply payment to an outstanding sale/invoice — full balance or a partial amount.',
            'permission' => 'payments.manage',
            'module' => 'payments',
        ],
        [
            'type' => 'navigate_orders',
            'label' => 'Open filtered sales orders',
            'description' => 'Navigate to Sales → Orders with search/filters (product, unpaid, mobile). Confirm to open the list.',
            'permission' => 'sales.order_queue_all.view',
            'module' => 'sales.backend',
        ],
        [
            'type' => 'open_lpo',
            'label' => 'Open LPO / procurement',
            'description' => 'Open purchase orders so the user can confirm a draft from AI suggestions.',
            'permission' => 'purchasing.lpo.view',
            'module' => 'customers_suppliers',
        ],
        [
            'type' => 'open_customer_collections',
            'label' => 'Open customer for collections',
            'description' => 'Open a debtor customer record to collect / send statement.',
            'permission' => 'customers.customers.view',
            'module' => 'customers_suppliers',
        ],
        [
            'type' => 'open_product',
            'label' => 'Open product (hold / review SKU)',
            'description' => 'Open a product card to review stock or mark hold.',
            'permission' => 'catalogue.products.view',
        ],
    ],
    /**
     * Known mistaken paths the model may invent → real Centrix screens.
     *
     * @var array<string, string>
     */
    'path_aliases' => [
        '/hr/field-attendance' => '/sales/field-attendance',
        '/attendance' => '/hr/attendance',
        '/hr/attendance-history' => '/hr/attendance/history',
        '/reports/sales-summary' => '/reports/sales-by-user',
        '/reports/custom-reports' => '/reports/builder',
        '/reports/custom' => '/reports/builder',
        '/custom-reports' => '/reports/builder',
        '/report-builder' => '/reports/builder',
    ],
];
