<?php

/**
 * Curated platform training notes that teach Centrix product mechanics.
 * Installed via Platform → AI training → "Install foundation notes".
 * Topics already present are skipped (safe to re-run).
 */
return [
    [
        'topic' => 'How Centrix stores stock quantities (base units)',
        'content' => 'All stock quantities in Centrix are stored in the product UoM base (smallest) unit — e.g. kg, pcs, or litres. Display mixes full packs and remaining small units (example: "2 Bag, 40 kg"). Never invent kg vs bags; quote qty_label from tools or product details. Configure packs at /uoms and assign the UoM on each product.',
        'path' => '/uoms',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'What is a Unit of Measure (UoM)?',
        'content' => 'A UoM defines packaging hierarchy: full pack name (e.g. Bag), optional middle pack, and small/base label (e.g. kg). conversion_factor is how many base units equal one full pack (e.g. 1 Bag = 50 kg). Manage at /uoms. For a specific product, call get_product_details or open /products/{code}.',
        'path' => '/uoms',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Retail packaging vs UoM — what is the difference?',
        'content' => 'UoM controls how stock is counted and displayed. Retail packaging (Sell on retail + /retail-package-settings) controls POS retail vs wholesale entry and markup tiers. They are separate: a bag/kg UoM can still sell retail by kg with retail markups. Use get_product_details for both on one product.',
        'path' => '/retail-package-settings',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Where do I receive goods (GRN)?',
        'content' => 'Receive stock against an LPO at /inventory/receipts (GRN). Create LPOs at /lpo and manage suppliers at /suppliers. After receiving, stock updates shop/store quantities in base UoM units.',
        'path' => '/inventory/receipts',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Where is End of Day / cashier sales summary?',
        'content' => 'End of Day and related cashier summaries live under reports and sales EOD screens (often /reports or Sales → End of Day depending on industry). Prefer find_screen with "end of day" or "EOD" and open the returned path. Payment mix and till variance also appear in till health tools.',
        'path' => '/reports',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'How much VAT do I have this month / for August?',
        'content' => 'Use get_vat_collected with relative_date=this_month or month=august year=2026 (or year_month=2026-08). Quote vat_collected_total and taxable_sales_gross in KES. Open the day/branch breakdown at /reports/vat-collected. This is VAT collected on Centrix sales (output VAT). Do not answer with LPO or find_screen alone.',
        'path' => '/reports/vat-collected',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'How should answers cite Centrix screens?',
        'content' => 'Always give a real Centrix path users can open (e.g. /suppliers, /lpo, /inventory/stock, /hr/attendance). Call find_screen when unsure. Only cite paths from tools, navigation, or trained notes — never invent menus.',
        'path' => '/dashboard',
        'workspace_id' => null,
    ],
    [
        'topic' => 'Hotel POS vs retail POS',
        'content' => 'Retail carts use /sales/pos or External POS /pos. Hotel & Hospitality checks use /hotel-bar-pos (not retail carts). Hotel lists: /hospitality/orders. Do not mix hotel check workflows with retail cart checkout.',
        'path' => '/hotel-bar-pos',
        'workspace_id' => 'hotel_bar_pos',
    ],
    [
        'topic' => 'Q: Is product stock in kg or bags?',
        'content' => 'A: Call get_product_details for that product. Read measurements.conversion_meaning and stock.*_qty_label. Example answer: "Stock is stored in kg (base). 1 Bag = 50 kg. On hand shows as 1 Bag, 40 kg." Do not guess from the product name alone.',
        'path' => '/products',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I set retail packaging for a product?',
        'content' => 'A: Turn on Sell on retail on the product, then configure tiers at /retail-package-settings (min/max measures and markups). Confirm with get_product_details → retail_packaging. Path: /retail-package-settings.',
        'path' => '/retail-package-settings',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Custom reports',
        'content' => 'Users build saved reports in Report Builder at /reports/builder. After create_custom_report, give /reports/custom/{id}. Do not invent report ids.',
        'path' => '/reports/builder',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Profit, margins, and P&L in AI chat',
        'content' => 'Use get_profit_loss for gross/net profit, margins, COGS, and branch/product profitability. Link /reports/profit-loss for full detail. Never invent profit figures.',
        'path' => '/reports/profit-loss',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'AI insights from chat (anomaly, forecast, margins)',
        'content' => 'Call run_insight with insight_type such as anomaly_detection, forecast_light, margin_discount_watchdog, exception_radar, customer_360 (requires customer_num), procurement_companion, collections_playbook. Narrate the returned JSON slice.',
        'path' => '/reports',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Customer portfolio and churn',
        'content' => 'For lists of inactive or declining customers: get_customer_portfolio. For one customer deep-dive: run_insight customer_360 with customer_num. Collections: get_debtors_summary or run_insight collections_playbook.',
        'path' => '/customers',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Cash position and inventory valuation',
        'content' => 'Cash/treasury questions: get_cash_position (till + GL cash/bank + AR + AP estimate). Stock value: get_inventory_valuation. Accounting cash flow statement: /reports/cash-flow — different from till cash.',
        'path' => '/reports/cash-flow',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'What-if scenarios in AI chat',
        'content' => 'Use calculate_scenario with scenario_type (price_increase, sales_increase, supplier_cost_increase, discount_reduction) and percent_change. Always label results as illustrative estimates.',
        'path' => '/reports/profit-loss',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What is bank reconciliation in Centrix?',
        'content' => 'A: Native GL matching of a bank/cash account to a bank statement. Import CSV (not Excel), match statement lines to posted book lines, Finish when |Difference| < 0.02. Path: /accounting/bank-reconciliation. Not M-Pesa/Equity recon.',
        'path' => '/accounting/bank-reconciliation',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: What CSV format for bank statement import?',
        'content' => 'A: CSV/text only. Headers: date, description, reference, amount — or debit/credit (money_in/money_out). Example: date,description,reference,amount then 2026-06-01,Deposit,DEP-1,1500. Deposits positive; withdrawals negative. Dates YYYY-MM-DD preferred. Path: /accounting/bank-reconciliation.',
        'path' => '/accounting/bank-reconciliation',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: How do I upload and reconcile a bank statement?',
        'content' => 'A: New reconciliation → bank account, statement date, ending balance → Bank statement tab → Import CSV → Reconcile tab (suggested/manual match, amounts within 0.02) → exclude noise → Add adjustment if needed → Finish now when Difference ≈ 0. Cleared items appear on /accounting/bank-register.',
        'path' => '/accounting/bank-reconciliation',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: Why is bank reconciliation difference not zero?',
        'content' => 'A: Wrong ending balance typed, unmatched statement lines, uncleared book items, missing bank fee/interest journals, or bad matches. Match or exclude remaining lines; post missing journals; optional Add adjustment for immaterial gaps. Finish only when |Difference| < 0.02.',
        'path' => '/accounting/bank-reconciliation',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Bank reconciliation vs other recon tools',
        'content' => 'Bank reconciliation = GL bank/cash vs bank statement CSV at /accounting/bank-reconciliation. M-Pesa, Equity, and Centrix Payments recon are separate payment-channel tools. Subledger recon compares AR/AP control accounts to operational balances — different again.',
        'path' => '/accounting/bank-reconciliation',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: Can a Delivered order still be unpaid? What does Completed mean?',
        'content' => 'A: Yes — Delivered is fulfillment (goods handed over / trip POD). It may still be unpaid or partially paid. Completed means full payment is received (amount paid covers order total). Centrix blocks marking Completed while a balance remains; collect payment first (Sales → Unpaid / Partially paid, or Collect payment on the order). Paid is the payment stage; Delivered is not payment. Unpaid queues and Sales by User "Unpaid" use amount maths, so a Delivered order with nothing collected still counts as unpaid.',
        'path' => '/sales/orders',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Which products have cost higher than selling price?',
        'content' => 'A: Call find_catalogue_exceptions with check=cost_above_selling (or check=all for a catalogue health overview). Quote totals and the product table (code, name, unit_price, last_cost_price, margin_pct). Link /products to fix prices. This is catalogue master data — not the same as margin_discount_watchdog (recent sale lines sold below cost). Other checks: zero_selling_price, zero_cost_price, thin_margin, missing_supplier, missing_reorder_point, below_reorder, missing_vat, missing_uom.',
        'path' => '/products',
        'workspace_id' => 'backoffice',
    ],

    // --- Easy / quick user Q&A (~100) for Platform → AI training foundation ---

    [
        'topic' => 'Q: Where is the POS?',
        'content' => 'A: Retail checkout is at /sales/pos (Create order) or the cashier terminal at /pos. Hotel & Hospitality uses /hotel-bar-pos for checks — not the retail cart.',
        'path' => '/sales/pos',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are sales orders?',
        'content' => 'A: Open Sales → Sales orders at /sales/orders. Filter by status, customer, or date there.',
        'path' => '/sales/orders',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where do I see unpaid customers / debtors?',
        'content' => 'A: Sales → Unpaid Debtors at /sales/shop-debtors/unpaid. Partial balances: /sales/shop-debtors/partial. Fully paid history: /sales/shop-debtors/paid.',
        'path' => '/sales/shop-debtors/unpaid',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I collect payment on an unpaid order?',
        'content' => 'A: Open the order or go to /sales/shop-debtors/unpaid (or Partial), then Collect payment. You can set payment date when collecting. Checkout itself does not use payment date.',
        'path' => '/sales/shop-debtors/unpaid',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are customers?',
        'content' => 'A: Sales → Customers at /customers. Create, edit, and view balances there.',
        'path' => '/customers',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are products?',
        'content' => 'A: Inventory & catalog → Products at /products. Search by code or name; open a product for price, stock, UoM, and VAT.',
        'path' => '/products',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is current stock?',
        'content' => 'A: Inventory → Current stock at /inventory/stock. Quantities show in mixed UoM labels (e.g. 2 Bag, 40 kg). Low stock report: /reports/low-stock.',
        'path' => '/inventory/stock',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I receive stock / GRN?',
        'content' => 'A: Inventory → Stock receipts (GRN) at /inventory/receipts. Receive against an approved LPO; stock updates in base UoM units.',
        'path' => '/inventory/receipts',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where do I create a purchase order / LPO?',
        'content' => 'A: Purchasing → Purchase orders (LPO) at /lpo. Add supplier and lines, then submit for approval if your org requires it.',
        'path' => '/lpo',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are suppliers?',
        'content' => 'A: Purchasing → Suppliers at /suppliers. Pay them at /suppliers/payments.',
        'path' => '/suppliers',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I pay a supplier?',
        'content' => 'A: Open /suppliers/payments, pick the supplier and outstanding LPO/bills, then record the payment method and amount.',
        'path' => '/suppliers/payments',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are categories?',
        'content' => 'A: Inventory & catalog → Categories at /categories. Assign categories on each product card.',
        'path' => '/categories',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where do I set units of measure?',
        'content' => 'A: Configure packs at /uoms (full pack, optional middle, small/base unit and conversion_factor). Assign the UoM on the product.',
        'path' => '/uoms',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What is conversion factor on a UoM?',
        'content' => 'A: conversion_factor is how many base (small) units equal one full pack. Example: 1 Bag = 50 kg means conversion_factor 50. Stock is always stored in base units.',
        'path' => '/uoms',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How much Sugar do we have?',
        'content' => 'A: Call get_product_details for Sugar (match by name/code). Quote stock.*_qty_label and measurements.conversion_meaning — never invent bags vs kg from the name alone.',
        'path' => '/inventory/stock',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What is the selling price of product X?',
        'content' => 'A: Call get_product_details with the product name or code. Quote unit_price (and cost if asked). Open /products/{code} to edit.',
        'path' => '/products',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Who changed the price of this product?',
        'content' => 'A: Call get_product_price_history for that product, or open /price-history. Centrix keeps a formal ledger of unit/cost/discount changes with who and when.',
        'path' => '/price-history',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is price history?',
        'content' => 'A: Catalogue price-change ledger is at /price-history. For one product, call get_product_price_history — do not invent changes from sales averages.',
        'path' => '/price-history',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I do a stock take?',
        'content' => 'A: Inventory → Stock take at /inventory/stock-take. Count physical stock and post variances. For one-off fixes use /inventory/adjustments.',
        'path' => '/inventory/stock-take',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are stock adjustments?',
        'content' => 'A: Inventory → Stock adjustments at /inventory/adjustments. Use for write-offs, damage, or corrections outside a full stock take.',
        'path' => '/inventory/adjustments',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is End of Day?',
        'content' => 'A: Use find_screen with "end of day" or "EOD", or open Reports at /reports. Till health and cashier payment mix also appear in till tools.',
        'path' => '/reports',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is Sales by User?',
        'content' => 'A: Reports → Sales by user at /reports/sales-by-user. Collected = money taken; Unpaid = remaining balance. For a named cashier call get_sales_by_cashier — do not invent totals.',
        'path' => '/reports/sales-by-user',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How much did we sell today?',
        'content' => 'A: Call get_sales_summary (or daily sales) for today, or open /reports/daily-sales. Quote gross and collected separately when credit sales exist.',
        'path' => '/reports/daily-sales',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How much VAT this month?',
        'content' => 'A: Call get_vat_collected with relative_date=this_month. Quote vat_collected_total and taxable_sales_gross in KES. Detail: /reports/vat-collected.',
        'path' => '/reports/vat-collected',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is the VAT report?',
        'content' => 'A: Reports → VAT collected at /reports/vat-collected. This is output VAT on Centrix sales, not LPO input VAT.',
        'path' => '/reports/vat-collected',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What products are low on stock?',
        'content' => 'A: Open /reports/low-stock, or call find_catalogue_exceptions with check=below_reorder. Fix reorder points on /products.',
        'path' => '/reports/low-stock',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is profit and loss?',
        'content' => 'A: Call get_profit_loss for the period, or open /reports/profit-loss. Never invent margin or COGS figures.',
        'path' => '/reports/profit-loss',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is the dashboard?',
        'content' => 'A: Business summary is at /dashboard. Sales analytics /sales, inventory analytics /inventory, reports hub /reports.',
        'path' => '/dashboard',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is till management?',
        'content' => 'A: Sales → Till management at /sales/till-management. Open/close tills and review float there.',
        'path' => '/sales/till-management',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are vouchers?',
        'content' => 'A: Sales → Vouchers at /sales/vouchers. Issue and redeem gift/credit vouchers from there and at POS checkout.',
        'path' => '/sales/vouchers',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are returns / credit notes?',
        'content' => 'A: Sales → Credit notes at /sales/returns. For a person\'s returns, call get_customer_returns with user_name.',
        'path' => '/sales/returns',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I hold an order without payment?',
        'content' => 'A: At checkout choose save/hold (held status) — not a paid checkout. Resume or cancel later from /sales/orders. Use create_held_order only when the user explicitly asks to hold.',
        'path' => '/sales/orders',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Can I mark an order Completed if it is unpaid?',
        'content' => 'A: No. Completed means fully paid. Centrix blocks Completed while a balance remains — collect payment first. Delivered can still be unpaid.',
        'path' => '/sales/orders',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What is the difference between Delivered and Paid?',
        'content' => 'A: Delivered = goods fulfilled (may still owe money). Paid = payment stage fully collected. Completed requires full payment. Unpaid queues use amount maths, not labels alone.',
        'path' => '/sales/orders',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is retail packaging / sell on retail?',
        'content' => 'A: Turn on Sell on retail on the product, then configure tiers at /retail-package-settings. Separate from UoM conversion — confirm with get_product_details → retail_packaging.',
        'path' => '/retail-package-settings',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where do I set VAT rates?',
        'content' => 'A: VAT masters live under catalogue settings at /vats. Assign a VAT rate on each product.',
        'path' => '/vats',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are expenses?',
        'content' => 'A: Accounting → Expenses at /expenses. For one user\'s expenses call get_expense_summary with user_name.',
        'path' => '/expenses',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: Where is chart of accounts?',
        'content' => 'A: Accounting → Chart of accounts at /accounting/chart-of-accounts.',
        'path' => '/accounting/chart-of-accounts',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: Where are journal entries?',
        'content' => 'A: Accounting → Journal entries at /accounting/journal-entries. Post balanced debit/credit lines there.',
        'path' => '/accounting/journal-entries',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: Where is accounts receivable?',
        'content' => 'A: Accounting → Accounts receivable at /accounting/accounts-receivable. Shop debtors queues are also under Sales → Unpaid/Partial.',
        'path' => '/accounting/accounts-receivable',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: Where is cash flow report?',
        'content' => 'A: Accounting cash flow statement is at /reports/cash-flow. Till/treasury snapshot uses get_cash_position — different from the statement.',
        'path' => '/reports/cash-flow',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: How much cash do we have?',
        'content' => 'A: Call get_cash_position (tills + GL cash/bank + AR/AP estimate). For the formal cash flow statement open /reports/cash-flow.',
        'path' => '/reports/cash-flow',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: What is our inventory value?',
        'content' => 'A: Call get_inventory_valuation and quote the returned totals. Stock Value = Cost Price × Stock on Hand in plain language.',
        'path' => '/inventory/stock',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are employees?',
        'content' => 'A: HR → Employees at /hr/employees. For pay/department/bank details call get_employee_details.',
        'path' => '/hr/employees',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is today\'s attendance?',
        'content' => 'A: HR → Today\'s attendance at /hr/attendance. History: /hr/attendance/history. Field reps: /sales/field-attendance.',
        'path' => '/hr/attendance',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is payroll?',
        'content' => 'A: HR → Payroll at /hr/payroll. Summary report: /reports/payroll-summary. Overtime pays only when status is approved.',
        'path' => '/hr/payroll',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is leave?',
        'content' => 'A: HR → Leave at /hr/leave. Balances report: /reports/leave-balance.',
        'path' => '/hr/leave',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are departments?',
        'content' => 'A: HR → Departments at /hr/departments. Assign department on each employee.',
        'path' => '/hr/departments',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are shifts?',
        'content' => 'A: HR → Shifts at /hr/shifts. Link employees to shift schedules there.',
        'path' => '/hr/shifts',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are absents and lateness?',
        'content' => 'A: Absents: /hr/absents. Lateness: /hr/lateness. Attendance register report: /reports/attendance-register.',
        'path' => '/hr/absents',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What is someone\'s basic salary?',
        'content' => 'A: Call get_employee_details for that person. Centrix stores basic salary on employees.base_salary — do not say pay data is missing when the tool returns it.',
        'path' => '/hr/employees',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Does pending overtime get paid?',
        'content' => 'A: No. Overtime only enters payroll when approved. Pending OT waits for approval; denied/rejected OT never pays. Path: /hr/payroll and pending overtime screens.',
        'path' => '/hr/payroll',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where do I add users?',
        'content' => 'A: Administration → Users at /admin/users. Assign roles at /admin/roles.',
        'path' => '/admin/users',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are roles and permissions?',
        'content' => 'A: Administration → Roles and permissions at /admin/roles. Grant screen/action permissions per role.',
        'path' => '/admin/roles',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is Report Builder?',
        'content' => 'A: Reports → Report builder at /reports/builder. Saved reports open at /reports/custom/{id} — never invent report ids.',
        'path' => '/reports/builder',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are routes / distribution routes?',
        'content' => 'A: Fulfillment → Routes at /fulfillment/routes (when distribution ops is enabled). Dispatch /fulfillment/dispatch, trips /fulfillment/trips, drivers /fulfillment/drivers.',
        'path' => '/fulfillment/routes',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What markups are on this route?',
        'content' => 'A: Call get_route_markups for the route name/code. Quote the returned markup tiers; do not invent percentages. Manage routes at /fulfillment/routes.',
        'path' => '/fulfillment/routes',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is dispatch?',
        'content' => 'A: Fulfillment → Dispatch at /fulfillment/dispatch. Assign drivers and load trips for delivery.',
        'path' => '/fulfillment/dispatch',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where do I track trips?',
        'content' => 'A: Fulfillment → Trips / shipment tracking at /fulfillment/trips.',
        'path' => '/fulfillment/trips',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are drivers?',
        'content' => 'A: Fulfillment → Drivers at /fulfillment/drivers.',
        'path' => '/fulfillment/drivers',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is field attendance?',
        'content' => 'A: Sales/HR field attendance for mobile reps is at /sales/field-attendance.',
        'path' => '/sales/field-attendance',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is Hotel POS?',
        'content' => 'A: Hotel & Hospitality checks use /hotel-bar-pos — not retail /sales/pos. Lists: /hospitality/orders.',
        'path' => '/hotel-bar-pos',
        'workspace_id' => 'hotel_bar_pos',
    ],
    [
        'topic' => 'Q: Where is front desk?',
        'content' => 'A: Rooms & guests → Front desk at /hospitality/front-desk. Reservations: /hospitality/reservations. Rooms: /hospitality/rooms.',
        'path' => '/hospitality/front-desk',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are folios?',
        'content' => 'A: Hospitality → Folios at /hospitality/folios. Open folio balances report: /reports/hospitality-folio-balances.',
        'path' => '/hospitality/folios',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is housekeeping?',
        'content' => 'A: Hotel operations → Housekeeping at /hospitality/housekeeping.',
        'path' => '/hospitality/housekeeping',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is night audit?',
        'content' => 'A: Hotel operations → Night audit at /hospitality/night-audit.',
        'path' => '/hospitality/night-audit',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are hotel outlets?',
        'content' => 'A: Hotel operations → Outlets at /hospitality/outlets (bars, restaurants, etc.).',
        'path' => '/hospitality/outlets',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is occupancy report?',
        'content' => 'A: Reports → Occupancy KPI at /reports/hospitality-kpi-occupancy. Room status: /reports/hospitality-occupancy.',
        'path' => '/reports/hospitality-kpi-occupancy',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are arrivals and departures?',
        'content' => 'A: Reports → Arrivals & departures at /reports/hospitality-arrivals-departures.',
        'path' => '/reports/hospitality-arrivals-departures',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I open the AI assistant?',
        'content' => 'A: Use the Assist / Talk controls in the app chrome (chat panel or near-mic Talk). Ask "Where is …?" for screen paths. Platform must have AI enabled for the tenant.',
        'path' => '/dashboard',
        'workspace_id' => null,
    ],
    [
        'topic' => 'Q: Can the AI speak answers?',
        'content' => 'A: Yes — Talk mode can reply briefly by voice (TTS). Keep answers short for speech; longer detail stays in the chat panel.',
        'path' => '/dashboard',
        'workspace_id' => null,
    ],
    [
        'topic' => 'Q: Where are Organization AI settings?',
        'content' => 'A: Organization settings → AI (tenant). Platform admins manage models and training notes under Platform → AI training.',
        'path' => '/admin',
        'workspace_id' => null,
    ],
    [
        'topic' => 'Q: How do I find a screen I forgot?',
        'content' => 'A: Ask the assistant "Where is …?" — it should call find_screen and give a real path like /suppliers. Never invent menu names.',
        'path' => '/dashboard',
        'workspace_id' => null,
    ],
    [
        'topic' => 'Q: Show me inactive customers',
        'content' => 'A: Call get_customer_portfolio for inactive/declining lists. One customer deep-dive: run_insight customer_360 with customer_num. Path: /customers.',
        'path' => '/customers',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Who are our top debtors?',
        'content' => 'A: Call get_debtors_summary or open /reports/top-debtors. Collect at /sales/shop-debtors/unpaid.',
        'path' => '/reports/top-debtors',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Any unusual sales today?',
        'content' => 'A: Call run_insight with insight_type=anomaly_detection (or exception_radar). Narrate the returned JSON; do not invent anomalies.',
        'path' => '/reports',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What if we raise prices by 5%?',
        'content' => 'A: Call calculate_scenario with scenario_type=price_increase and percent_change=5. Label results as illustrative estimates. Path: /reports/profit-loss.',
        'path' => '/reports/profit-loss',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Which sales were below cost?',
        'content' => 'A: Call run_insight margin_discount_watchdog for recent sold-below-cost lines. Catalogue cost>selling uses find_catalogue_exceptions check=cost_above_selling — different check.',
        'path' => '/reports',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I create a product?',
        'content' => 'A: Open /products → New, or ask the assistant to create_product (code, name, price, VAT, UoM). Set reorder point and supplier when known.',
        'path' => '/products',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I create a supplier?',
        'content' => 'A: Open /suppliers → New, or use create_supplier. Then you can raise LPOs at /lpo.',
        'path' => '/suppliers',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I approve an LPO?',
        'content' => 'A: Open the LPO at /lpo in awaiting approval, or use approve_lpo. After approval, receive goods at /inventory/receipts.',
        'path' => '/lpo',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I submit an LPO for approval?',
        'content' => 'A: From draft LPO at /lpo use Submit for approval (or submit_lpo_for_approval). If approval is off, it may go straight to awaiting send.',
        'path' => '/lpo',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What is GRN?',
        'content' => 'A: Goods Received Note — receiving stock against an LPO at /inventory/receipts. After GRN, quantities update current stock.',
        'path' => '/inventory/receipts',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What is an LPO?',
        'content' => 'A: Local Purchase Order — buy from a supplier. Create at /lpo, approve if required, then receive at /inventory/receipts and pay at /suppliers/payments.',
        'path' => '/lpo',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How is stock displayed — bags or kg?',
        'content' => 'A: Stock is stored in base units; the UI shows mixed packs via qty_label (e.g. 1 Bag, 40 kg). Call get_product_details — never guess from the product name.',
        'path' => '/uoms',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Is product weight the same as UoM?',
        'content' => 'A: No. Optional weight (kg) on the product card is metadata. Stock UoM is separate unless the small packaging unit is also kg. Confirm with get_product_details.',
        'path' => '/products',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is NSSF remittance report?',
        'content' => 'A: Reports → NSSF remittance at /reports/nssf-remittance. Related: statutory deductions /reports/statutory-deductions, bank transfer /reports/bank-transfer.',
        'path' => '/reports/nssf-remittance',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is headcount report?',
        'content' => 'A: Reports → Headcount at /reports/headcount. Staff turnover: /reports/staff-turnover. Contract expiry: /reports/contract-expiry.',
        'path' => '/reports/headcount',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are cash advances?',
        'content' => 'A: Cash advances report at /reports/cash-advances (HR payroll module).',
        'path' => '/reports/cash-advances',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I print or reprint a receipt?',
        'content' => 'A: Open the order at /sales/orders (or the POS sale) and use Print / Reprint on that order. Do not invent printer settings paths.',
        'path' => '/sales/orders',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I apply a discount on a sale?',
        'content' => 'A: On the POS/order line or checkout, enter the allowed discount (permission may be required). Price history of catalogue discounts is at /price-history.',
        'path' => '/sales/pos',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Can I sell on credit?',
        'content' => 'A: Yes — checkout with credit/customer account when the customer allows credit. Unpaid balances appear on /sales/shop-debtors/unpaid until collected.',
        'path' => '/sales/pos',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: What payment methods can POS take?',
        'content' => 'A: Typically cash, M-Pesa, card/bank, voucher, and credit depending on org settings. Exact mix shows on till/EOD and payment screens at checkout.',
        'path' => '/sales/pos',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is finance overview?',
        'content' => 'A: Accounting home at /accounting. From there open COA, journals, bank recon, expenses, and AR.',
        'path' => '/accounting',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: Where is hospitality overview?',
        'content' => 'A: Hotel dashboard at /hospitality. Manager flash report: /reports/hospitality-manager-flash.',
        'path' => '/hospitality',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where are bar / hotel order lists?',
        'content' => 'A: All checks /hospitality/orders, hotel /hospitality/orders/hotel, bar /hospitality/orders/bar. Terminal: /hotel-bar-pos.',
        'path' => '/hospitality/orders',
        'workspace_id' => 'hotel_bar_pos',
    ],
    [
        'topic' => 'Q: How do I room-charge from Hotel POS?',
        'content' => 'A: On /hotel-bar-pos settle/charge the check to the guest room folio when the outlet allows room charge. Folios: /hospitality/folios.',
        'path' => '/hotel-bar-pos',
        'workspace_id' => 'hotel_bar_pos',
    ],
    [
        'topic' => 'Q: What is the difference between retail POS and Hotel POS?',
        'content' => 'A: Retail carts: /sales/pos or /pos. Hotel checks (open/settle, room charge, F&B): /hotel-bar-pos. Do not mix the two workflows.',
        'path' => '/hotel-bar-pos',
        'workspace_id' => 'hotel_bar_pos',
    ],
    [
        'topic' => 'Q: How do I transfer stock between branches?',
        'content' => 'A: Use inventory transfer/receipt flows from stock screens (often via adjustments or inter-branch receive depending on setup). Start from /inventory/stock and find_screen "transfer" if unsure — do not invent a path.',
        'path' => '/inventory/stock',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Products missing supplier or reorder point?',
        'content' => 'A: Call find_catalogue_exceptions with check=missing_supplier, missing_reorder_point, or check=all. Fix on /products.',
        'path' => '/products',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Products with zero selling price?',
        'content' => 'A: Call find_catalogue_exceptions check=zero_selling_price (or check=all). Update unit price on /products.',
        'path' => '/products',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How do I see CHEGE\'s sales / expenses / returns?',
        'content' => 'A: Multi-part: call get_sales_by_cashier (or get_route_orders), get_expense_summary, and get_customer_returns with the same user_name and period. Answer under clear headings — never say these are only org-wide.',
        'path' => '/reports/sales-by-user',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is admin home?',
        'content' => 'A: Administration → Admin home at /admin. Users /admin/users, roles /admin/roles, attendance clock /admin/attendance-clock when HR is enabled.',
        'path' => '/admin',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Where is fulfillment dashboard?',
        'content' => 'A: When distribution ops is on: /fulfillment. Dispatch, trips, drivers, and routes live under that section.',
        'path' => '/fulfillment',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: How should stock value be calculated?',
        'content' => 'A: Stock Value = Cost Price × Stock on Hand (base units). Prefer get_inventory_valuation tool totals over manual maths when available.',
        'path' => '/inventory/stock',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Do I use charts in every AI answer?',
        'content' => 'A: No. Only add bar/donut/pie chart fences when the user asks for a chart or graph. Default to short tables or bullets to save tokens.',
        'path' => '/reports',
        'workspace_id' => null,
    ],
    [
        'topic' => 'Q: Should AI use user ids or names?',
        'content' => 'A: Always speak about people with username and full name — never numeric user ids in answers to users.',
        'path' => '/admin/users',
        'workspace_id' => null,
    ],
    [
        'topic' => 'Q: Where is bank register after reconciliation?',
        'content' => 'A: Cleared/reconciled bank items appear on /accounting/bank-register after you Finish a reconciliation at /accounting/bank-reconciliation.',
        'path' => '/accounting/bank-register',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: Is bank recon the same as M-Pesa recon?',
        'content' => 'A: No. Bank reconciliation matches GL bank/cash to a bank statement CSV. M-Pesa, Equity, and Centrix Payments recon are separate channel tools.',
        'path' => '/accounting/bank-reconciliation',
        'workspace_id' => 'accounting',
    ],
    [
        'topic' => 'Q: How do I forecast sales lightly?',
        'content' => 'A: Call run_insight with insight_type=forecast_light and narrate the returned slice. Path: /reports.',
        'path' => '/reports',
        'workspace_id' => 'backoffice',
    ],
    [
        'topic' => 'Q: Collections playbook — who to call first?',
        'content' => 'A: Call run_insight collections_playbook or get_debtors_summary. Work the queue at /sales/shop-debtors/unpaid.',
        'path' => '/sales/shop-debtors/unpaid',
        'workspace_id' => 'backoffice',
    ],
];
