<?php

/**
 * ERP module registry and deployment profiles.
 *
 * Organizations store deployment_profile + optional enabled_modules overrides.
 * API middleware uses module keys (e.g. sales.pos) to gate routes.
 */
$erpModuleTree = require __DIR__.'/erp_module_tree.php';
$allModulesFalse = array_fill_keys(
    array_diff(array_keys($erpModuleTree), \App\Services\Erp\ModuleRegistry::configOnlyKeys()),
    false,
);

return [

    'company_code' => env('APP_COMPANY_CODE'),

/** When true, super admins can register new tenant organizations via POST /admin/organizations/provision. */
    'allow_org_provisioning' => filter_var(env('APP_ALLOW_ORG_PROVISIONING', true), FILTER_VALIDATE_BOOL),

    /** Company code for the platform super-admin organization (login target). */
    'platform_company_code' => strtoupper(env('APP_PLATFORM_COMPANY_CODE', 'PLATFORM')),

    /** Platform super-admin account (seeded / upserted via PlatformSuperAdminSeeder). */
    'platform_super_admin_email' => env('PLATFORM_SUPER_ADMIN_EMAIL'),
    'platform_super_admin_password' => env('PLATFORM_SUPER_ADMIN_PASSWORD'),

    /** Idle API tokens are revoked after this many minutes without a request. */
    'session_idle_minutes' => (int) env('AUTH_SESSION_IDLE_MINUTES', 60),

    /** Default screen lock delay for new organizations (minutes). */
    'screen_lock_minutes' => (int) env('AUTH_SCREEN_LOCK_MINUTES', 5),

    /** Frontend base URL for password-reset links (no trailing slash). */
    'frontend_url' => rtrim(env('FRONTEND_URL', 'http://localhost:3000'), '/'),

    'profiles' => [
        'platform' => [
            'label' => 'Platform operator',
            'modules' => $allModulesFalse,
            'default_channels' => ['backend'],
        ],
        'small_shop' => [
            'label' => 'Small shop (backend sales only)',
            'modules' => array_merge($allModulesFalse, [
                'sales' => true,
                'sales.backend' => true,
                'sales.dashboard' => true,
                'sales.reports' => true,
                'payments' => true,
                'inventory' => true,
                'inventory.dashboard' => true,
                'inventory.reports' => true,
                'customers_suppliers' => true,
                'customers_suppliers.reports' => true,
                'admin' => true,
            ]),
            'default_channels' => ['backend'],
        ],
        'wholesale_retail' => [
            'label' => 'Wholesale & retail (full stack)',
            'modules' => array_merge($allModulesFalse, [
                'sales' => true,
                'sales.backend' => true,
                'sales.pos' => true,
                'sales.mobile' => true,
                'sales.dashboard' => true,
                'sales.reports' => true,
                'payments' => true,
                'inventory' => true,
                'inventory.dashboard' => true,
                'inventory.reports' => true,
                'accounting' => true,
                'accounting.dashboard' => true,
                'accounting.reports' => true,
                'hr_payroll' => true,
                'hr_payroll.dashboard' => true,
                'hr_payroll.reports' => true,
                'admin' => true,
                'customers_suppliers' => true,
                'customers_suppliers.reports' => true,
            ]),
            'default_channels' => ['pos', 'mobile', 'backend'],
        ],
        'supermarket' => [
            'label' => 'Supermarket (POS retail)',
            'modules' => array_merge($allModulesFalse, [
                'sales' => true,
                'sales.backend' => true,
                'sales.pos' => true,
                'sales.dashboard' => true,
                'sales.reports' => true,
                'payments' => true,
                'inventory' => true,
                'inventory.dashboard' => true,
                'inventory.reports' => true,
                'accounting' => true,
                'accounting.dashboard' => true,
                'accounting.reports' => true,
                'hr_payroll' => true,
                'hr_payroll.dashboard' => true,
                'hr_payroll.reports' => true,
                'admin' => true,
                'customers_suppliers' => true,
                'customers_suppliers.reports' => true,
            ]),
            'default_channels' => ['pos', 'backend'],
        ],
        'custom' => [
            'label' => 'Custom setup',
            'modules' => $allModulesFalse,
            'default_channels' => ['backend'],
        ],
        'distribution' => [
            'label' => 'Distribution / warehouse',
            'modules' => array_merge($allModulesFalse, [
                'sales' => true,
                'sales.backend' => true,
                'sales.mobile' => true,
                'sales.dashboard' => true,
                'sales.reports' => true,
                'payments' => true,
                'inventory' => true,
                'inventory.dashboard' => true,
                'inventory.reports' => true,
                'accounting' => true,
                'accounting.dashboard' => true,
                'accounting.reports' => true,
                'hr_payroll' => true,
                'hr_payroll.dashboard' => true,
                'hr_payroll.reports' => true,
                'admin' => true,
                'customers_suppliers' => true,
                'customers_suppliers.reports' => true,
                'distribution' => true,
                'distribution.dashboard' => true,
                'distribution.reports' => true,
            ]),
            'default_channels' => ['mobile', 'backend'],
        ],
    ],

    /*
    | Module registry lives in config/erp_module_tree.php (hierarchical domains).
    | Legacy flat keys in erp.modules are merged for backward compatibility.
    */
    'modules' => $erpModuleTree,

    /** Sidebar section order when super admin configures module access. */
    'nav_groups' => [
        'Sales' => ['sort' => 10, 'description' => 'POS, orders, dashboard, and sales reports'],
        'Inventory' => ['sort' => 20, 'description' => 'Stock, transfers, dashboard, and inventory reports'],
        'Purchasing' => ['sort' => 30, 'description' => 'Suppliers, LPO, customers, and purchasing reports'],
        'Distribution' => ['sort' => 35, 'description' => 'Dispatch, fleet, dashboard, and logistics reports'],
        'Accounting' => ['sort' => 40, 'description' => 'GL, payments, dashboard, and financial reports'],
        'Human resources' => ['sort' => 50, 'description' => 'Employees, payroll, dashboard, and HR reports'],
        'Administration' => ['sort' => 70, 'description' => 'Users, roles, branches, org preferences'],
    ],

    /** Keys only platform super admin may set (registration or Platform → Organizations). */
    'platform_controlled' => [
        'sales' => [
            'show_checkout_on_create_order',
            'enable_mobile_orders',
            'stock_deduct_on',
            'require_pos_till_float',
        ],
        'distribution' => [],
        'finance' => [
            'enable_mpesa_stk',
            'enable_kra_integration',
        ],
        'ai' => [
            'enable_ai',
        ],
        'admin' => [
            'enable_advanced_data_import',
        ],
    ],

    /*
    | Order lifecycle (fulfillment) — sales.status
    | Payment lifecycle — sales.payment_status + sale_payments + customer_invoices
    */
    'workflows' => [
        'pos' => [
            'statuses' => ['draft', 'held', 'booked', 'unpaid', 'pending_payment', 'paid', 'delivered', 'completed', 'cancelled'],
            'pay_on_complete' => true,
        ],
        'mobile' => [
            'statuses' => ['draft', 'booked', 'pending', 'unpaid', 'pending_payment', 'paid', 'processed', 'delivered', 'completed', 'cancelled'],
            'payment_statuses' => ['unpaid', 'partial', 'paid'],
        ],
        'backend' => [
            'statuses' => ['draft', 'booked', 'pending', 'unpaid', 'pending_payment', 'paid', 'processed', 'delivered', 'completed', 'cancelled'],
            'payment_statuses' => ['unpaid', 'partial', 'paid'],
            'credit_allowed' => true,
        ],
    ],

    'order_status_labels' => [
        'draft' => 'Draft',
        'held' => 'Held',
        'booked' => 'Booked',
        'pending' => 'Pending',
        'unpaid' => 'Unpaid',
        'pending_payment' => 'Partially paid',
        'paid' => 'Paid',
        'processed' => 'Processed',
        'delivered' => 'Delivered',
        'completed' => 'Completed',
        'cancelled' => 'Cancelled',
    ],

    'default_order_workflow' => [
        'steps' => [
            ['status' => 'booked', 'label' => 'Booked', 'enabled' => true],
            ['status' => 'pending', 'label' => 'Pending', 'enabled' => true],
            ['status' => 'unpaid', 'label' => 'Unpaid', 'enabled' => true],
            ['status' => 'pending_payment', 'label' => 'Partially paid', 'enabled' => true],
            ['status' => 'paid', 'label' => 'Paid', 'enabled' => true],
            ['status' => 'processed', 'label' => 'Processed', 'enabled' => true],
            ['status' => 'delivered', 'label' => 'Delivered', 'enabled' => true],
            ['status' => 'completed', 'label' => 'Completed', 'enabled' => true],
        ],
        'transitions' => [
            'booked' => ['pending', 'unpaid', 'cancelled'],
            'pending' => ['unpaid', 'pending_payment', 'cancelled'],
            'unpaid' => ['pending_payment', 'paid', 'cancelled'],
            'pending_payment' => ['paid', 'cancelled'],
            'paid' => ['processed', 'delivered', 'completed'],
            'processed' => ['delivered', 'completed'],
            'delivered' => ['completed'],
            'draft' => ['held', 'completed', 'booked', 'cancelled'],
            'held' => ['draft', 'booked', 'completed', 'cancelled'],
        ],
        'save_status' => [
            'pos' => 'unpaid',
            'mobile' => 'unpaid',
            'backend' => 'unpaid',
        ],
        'checkout' => [
            'full_paid' => [
                'pos' => 'completed',
                'mobile' => 'paid',
                'backend' => 'paid',
            ],
            'partial' => 'pending_payment',
            'unpaid' => [
                'pos' => 'unpaid',
                'mobile' => 'unpaid',
                'backend' => 'unpaid',
            ],
        ],
        'deduct_stock_on' => 'completed',
    ],

    'standard_chart_of_accounts' => [
        ['account_code' => '1000', 'account_name' => 'Cash', 'account_type' => 'asset'],
        ['account_code' => '1100', 'account_name' => 'Bank Account', 'account_type' => 'asset'],
        ['account_code' => '1200', 'account_name' => 'Accounts Receivable', 'account_type' => 'asset'],
        ['account_code' => '1300', 'account_name' => 'Inventory', 'account_type' => 'asset'],
        ['account_code' => '2000', 'account_name' => 'Accounts Payable', 'account_type' => 'liability'],
        ['account_code' => '2100', 'account_name' => 'VAT Payable', 'account_type' => 'liability'],
        ['account_code' => '3000', 'account_name' => 'Owner Equity', 'account_type' => 'equity'],
        ['account_code' => '3100', 'account_name' => 'Retained Earnings', 'account_type' => 'equity'],
        ['account_code' => '4000', 'account_name' => 'Sales Revenue', 'account_type' => 'revenue'],
        ['account_code' => '5000', 'account_name' => 'Cost of Goods Sold', 'account_type' => 'expense'],
        ['account_code' => '5100', 'account_name' => 'Cash Over / Short', 'account_type' => 'expense'],
        ['account_code' => '5200', 'account_name' => 'Payroll Expense', 'account_type' => 'expense'],
        ['account_code' => '5300', 'account_name' => 'Operating Expenses', 'account_type' => 'expense'],
    ],

    'module_settings_defaults' => [
        'accounting' => [
            'auto_post_sales' => true,
            'auto_post_expenses' => true,
            'auto_post_purchases' => true,
            'auto_post_payments' => true,
            'auto_post_payroll' => true,
            'auto_post_returns' => true,
            'post_till_variance' => true,
            'account_codes' => [
                'cash' => '1000',
                'bank' => '1100',
                'ar' => '1200',
                'inventory' => '1300',
                'ap' => '2000',
                'vat_payable' => '2100',
                'retained_earnings' => '3100',
                'sales_revenue' => '4000',
                'cogs' => '5000',
                'till_variance' => '5100',
                'payroll_expense' => '5200',
                'operating_expense' => '5300',
            ],
            'payment_method_accounts' => [
                'CASH' => '1000',
                'MPESA' => '1100',
                'CARD' => '1100',
                'BANK' => '1100',
                'TRANSFER' => '1100',
                'VOUCHER' => '1000',
                'POINTS' => '1000',
            ],
        ],
        'sales' => [
            'allow_sell_from_shop' => true,
            'allow_sell_from_store' => false,
            'enable_retail_pricing' => false,
            'allow_discounts' => true,
            'allow_edit_line_discount' => false,
            'enable_order_discount' => false,
            'enable_vouchers' => false,
            'enable_redeemable_points' => false,
            'point_cash_value' => 1,
            'points_earn_per_kes' => 1000,
            'allow_edit_unit_price' => true,
            'allow_pos_edit_unit_price' => false,
            'enable_barcode_scanner' => false,
            'default_tax_rate' => 16,
            'enable_mpesa_amount' => true,
            'enable_mpesa_code' => false,
            'enable_bank_select' => false,
            'enable_equity_bank' => true,
            'enable_kcb_bank' => true,
            'enable_other_bank' => false,
            'other_bank_name' => 'Other bank',
            'enable_bank_amount' => true,
            'enable_cheque' => true,
            'enable_cheque_number' => false,
            'enable_payment_date' => false,
            'enable_credit_payment' => true,
            'allow_credit_pay_now' => false,
            'show_checkout_on_create_order' => true,
            'enable_checkout_customer_name' => false,
            'retail_shop_wholesale_store_stock' => false,
            'add_route_markup_prices' => false,
            'backoffice_order_type_mode' => 'toggle',
            'pos_order_type_mode' => 'normal',
            'enable_mobile_orders' => true,
            'mobile_enable_checkout_location_verification' => false,
            'mobile_allow_offline_orders' => false,
            'mobile_checkout_location_radius_metres' => 5,
            'mobile_enable_field_attendance' => false,
            'require_pos_till_float' => false,
            'require_backoffice_till_float' => false,
            'blind_till_close' => false,
            'default_submit_kra' => true,
            'order_document_type' => 'receipt',
            'invoice_valid_days' => 7,
            'invoice_print_delivery_terms' => "Order valid for the period shown above.\nNo goods shall be received without an invoice or delivery note.\nPlease quote invoice number on all delivery notes.\nKindly attach a copy of this invoice to delivery notes.\nNo oversupply will be accepted.\nEnsure KRA PIN is captured on all supplier invoices.\nGoods must comply with applicable KEBS standards.\nVAT amount will not be paid on invoices without ETR receipt.\nPayment terms as agreed with the customer.",
            'invoice_print_footer_lines' => "No Oversupply will be accepted.\nThis invoice is not valid unless sent directly or signed by an authorised signatory of {organization}.\nOrder only valid for {days} days from above date.\nWe will only receive products with K.E.B.S mark / certificate\nTake note: VAT amount will not be paid on invoices without ETR receipt",
            'receipt_copies' => 1,
            'show_branch_on_receipt' => true,
            'order_workflow' => null,
            'stock_deduct_on' => 'order_created',
        ],
        'distribution' => [
            'enable_distribution_ops' => true,
            'inherit_customer_route' => true,
            'assign_on_status' => 'processed',
            'auto_assign_truck' => true,
            'auto_assign_driver' => true,
            'auto_create_trips' => true,
            'require_weight_on_load' => false,
            'set_delivery_date_on' => 'delivered',
            'require_pod_on_delivered' => false,
            'enforce_vehicle_capacity' => true,
            'enable_cod_reconciliation' => true,
            'require_trip_cash_settlement' => false,
            'include_normal_orders_in_loading_list' => false,
            'loading_sheet_footer_lines' => '',
            'loading_sheet_show_signatures' => true,
            'loading_sheet_default_checked_by' => '',
        ],
        'inventory' => [
            'default_receive_location' => 'store',
            'default_pos_sale_location' => 'shop',
            'default_distribution_sale_location' => 'store',
            'reserve_stock_on_cart' => true,
            'cart_reservation_ttl_minutes' => 15,
        ],
        'finance' => [
            'enable_mpesa_stk' => true,
            'enable_kra_integration' => true,
            'enable_kra_device' => false,
            'kra_device_ip' => '',
            /** Smart VSCU hardware IP for POST /api/init and /api/restart-device (when API URL is a hostname). */
            'kra_device_hardware_ip' => '',
            'kra_serial_number' => '',
            'kra_pin_number' => '',
            'kra_plu_upload_batch_size' => 50,
            'kra_device_test_mode' => false,
            'kra_plu_register_path' => '/api/upload-plu-data',
            'kra_plu_defaults' => [
                'plu_no' => '301',
                'barcode_prefix' => '000000',
                'unit_price' => '1',
                'item_cls_code' => '99010000',
                'pkg_unit_cd' => 'BG-Bag',
                'qty_unit_cd' => 'U-Pieces/item [Number]',
                'orgn_nat_cd' => 'KE-KENYA',
                'type_code' => '02Finished Product',
                'change_qty' => '100000',
                'from_no' => 1,
                'end_no' => 100000,
                'update_flag' => 0,
            ],
            'default_submit_kra' => true,
            'kra_bypass_above_amount' => null,
            /** @deprecated Trader invoice numbers are generated uniquely per submission (not from order_num). */
            'kra_trader_invoice_start' => null,
            'accounting_mode' => 'native',
            'accounting_provider' => null,
            'accounting_sync_direction' => 'export',
            'mpesa' => [
                'enable_stk_push' => true,
                'env' => 'sandbox',
                'consumer_key' => '',
                'consumer_secret' => '',
                'shortcode' => '',
                'till_number' => '',
                'child_storecode' => '',
                'passkey' => '',
                'stk_callback_url' => '',
                'c2b_confirmation_url' => '',
                'c2b_validation_url' => '',
            ],
            'quickbooks' => [
                'client_id' => '',
                'client_secret' => '',
                'redirect_uri' => '',
                'environment' => 'sandbox',
            ],
        ],
        'ai' => [
            'enable_ai' => true,
            'enabled' => false,
            'provider' => 'openai',
            'model' => '',
            'api_key' => '',
            'base_url' => '',
        ],
        'admin' => [
            'enable_advanced_data_import' => false,
        ],
        'general' => [
            'currency' => 'KES',
            'timezone' => 'Africa/Nairobi',
            'date_format' => 'DD/MM/YYYY',
            'language' => 'en',
            'decimal_places' => 2,
            'number_thousands_separator' => 'comma',
            'fiscal_year_start_month' => 1,
            'week_starts_on' => 'monday',
            'phone_country_code' => '+254',
            'default_country_code' => 'KE',
            'document_footer_text' => '',
            'print_footer_receipt' => '',
            'print_footer_a4_invoice' => '',
            'print_footer_lpo' => '',
            'print_footer_loading_sheet' => '',
            'show_organization_on_documents' => true,
            'document_header_display' => 'auto',
        ],
        'notifications' => [
            'sms_enabled' => false,
            'sms_provider' => 'africas_talking',
            'africas_talking_username' => '',
            'africas_talking_api_key' => '',
            'africas_talking_sender_id' => '',
            'email_enabled' => false,
            'email_from_name' => '',
            'email_from_address' => '',
            'smtp_enabled' => false,
            'smtp_host' => '',
            'smtp_port' => 587,
            'smtp_username' => '',
            'smtp_password' => '',
            'smtp_encryption' => 'tls',
            'notify_on_dispatch' => false,
            'notify_on_delivery' => false,
            'notify_on_order_placed' => false,
            'order_placed_scope' => 'all',
            'notify_on_debtor_payment' => false,
            'debtor_payment_scope' => 'debtors',
            'dispatch_sms_template' => 'Your order {order_num} is out for delivery on route {route_name}.',
            'delivery_sms_template' => 'Your order {order_num} was delivered. Thank you for your business.',
            'dispatch_email_template' => '',
            'delivery_email_template' => '',
            'order_placed_sms_template' => 'Thank you. Your order {order_num} for KES {order_total} has been received. Balance due: KES {balance_due}.',
            'order_placed_email_template' => '',
            'debtor_payment_sms_template' => 'Payment of KES {amount} received for order {order_num}. Balance due: KES {balance_due}.',
            'debtor_payment_email_template' => '',
        ],
        'procurement' => [
            'default_payment_terms_days' => 30,
            'require_lpo_approval' => true,
            'default_receive_location' => 'store',
            'auto_email_supplier_on_lpo' => false,
            'lpo_print_delivery_notes' => "Order valid until the date shown above.\nNo goods shall be received without an invoice or delivery note.\nPlease quote LPO number on all delivery notes and invoices.\nKindly attach a copy of this LPO to invoices and delivery notes.\nNo oversupply will be accepted.\nEnsure KRA PIN is captured on all supplier invoices.\nGoods must comply with applicable KEBS standards.",
            'lpo_print_kebs_warning' => 'We will only receive products with K.E.B.S mark / certificate',
            'lpo_print_vat_note' => 'VAT amount will not be paid on invoices without ETR receipt',
            'lpo_print_footer_lines' => "No Oversupply will be accepted.\nThis order is not valid unless sent directly OR Signed by an authorised Signatory of {organization}.\nORDER ONLY VALID FOR {days} DAYS FROM ABOVE DATE.",
            'lpo_print_validity_days' => 7,
            'lpo_print_checked_by' => '',
            'lpo_print_authorised_by' => '',
        ],
        'security' => [
            'screen_lock_minutes' => 5,
            'session_idle_minutes' => 60,
            'require_strong_passwords' => false,
            'password_min_length' => 8,
            'password_expiry_enabled' => true,
            'password_expiry_days' => 90,
            'password_expiry_max_skips' => 2,
        ],
        'hr_payroll' => [
            'pay_frequency' => 'monthly',
            'grace_days_after_month_end' => 7,
            'payroll_run_delete_lock_minutes' => 20,
            'auto_calculate_statutory' => true,
            'close_cycle_on_process' => true,
            'include_overtime_in_payroll' => true,
            'include_other_deductions_in_payroll' => true,
            'require_payroll_approval' => false,
            'require_attendance_for_payroll' => false,
            'standard_work_hours_per_day' => 8,
            'overtime_rate_multiplier' => 1.5,
            'default_probation_months' => 3,
            'enable_cash_advance_deductions' => true,
            'deduct_cash_advances_on_payroll' => true,
            'attendance_capture_mode' => 'clock_device',
            'company_premises_latitude' => null,
            'company_premises_longitude' => null,
            'company_premises_radius_metres' => 5,
            'company_face_match_threshold' => 0.72,
            'company_fingerprint_match_threshold' => 0.85,
            'company_fingerprint_auto_enroll_on_clock' => true,
            'company_mobile_verification_method' => 'face_or_fingerprint',
        ],
        'legacy_archive' => [
            'enabled' => false,
            'database' => null,
            'host' => null,
            'port' => null,
            'username' => null,
            'password' => null,
            'label' => 'LightStores archive',
            'cutover_date' => null,
        ],
    ],
];
