<?php

/**
 * Maps route capability codes (erp.permission middleware) to feature permission codes.
 */
return [
    'sales.create' => [
        'sales.orders.create',
        'pos.checkout.create',
    ],
    'sales.manage' => [
        'sales.orders.edit',
        'sales.orders.delete',
        'sales.orders.approve',
    ],
    'payments.manage' => [
        'payments.sale_payments.create',
        'payments.sale_payments.edit',
    ],
    'inventory.view' => [
        'inventory.stock.view',
        'inventory.receipts.view',
        'inventory.movements.view',
        'inventory.transfers.view',
        'inventory.damages.view',
        'inventory.stock_take.view',
    ],
    'inventory.manage' => [
        'inventory.receipts.create',
        'inventory.receipts.approve',
        'inventory.transfers.create',
        'inventory.damages.create',
        'inventory.stock_take.create',
        'inventory.stock_take.approve',
    ],
    'reports.view' => [
        'reports.hub.view',
        'reports.daily_sales.view',
        'reports.stock_on_hand.view',
        'reports.profit_loss.view',
        'reports.top_debtors.view',
        'reports.stock_movement.view',
        'reports.vat_collected.view',
        'reports.till_sessions.view',
        'reports.expenses.view',
        'reports.customer_statement.view',
    ],
    'purchasing.manage' => [
        'purchasing.lpo.create',
        'purchasing.lpo.edit',
        'purchasing.lpo.delete',
        'purchasing.lpo.approve',
        'purchasing.suppliers.create',
        'purchasing.suppliers.edit',
        'purchasing.suppliers.delete',
        'purchasing.supplier_payments.create',
        'purchasing.supplier_returns.create',
        'fulfillment.drivers.create',
        'fulfillment.drivers.edit',
        'fulfillment.drivers.delete',
        'fulfillment.vehicles.create',
        'fulfillment.vehicles.edit',
        'fulfillment.vehicles.delete',
        'fulfillment.routes.create',
        'fulfillment.routes.edit',
        'fulfillment.routes.delete',
    ],
    'accounting.view' => [
        'accounting.dashboard.view',
        'accounting.chart_of_accounts.view',
        'accounting.journal_entries.view',
        'accounting.fiscal_periods.view',
        'accounting.settings.view',
        'accounting.account_mappings.view',
        'accounting.export_queue.view',
        'accounting.general_ledger.view',
        'accounting.trial_balance.view',
        'accounting.profit_loss.view',
        'accounting.balance_sheet.view',
        'accounting.cash_flow.view',
        'accounting.accounts_receivable.view',
        'accounting.accounts_payable.view',
        'accounting.expenses.view',
    ],
    'accounting.manage' => [
        'accounting.chart_of_accounts.create',
        'accounting.chart_of_accounts.edit',
        'accounting.chart_of_accounts.delete',
        'accounting.journal_entries.create',
        'accounting.journal_entries.edit',
        'accounting.journal_entries.delete',
        'accounting.journal_entries.approve',
        'accounting.fiscal_periods.edit',
        'accounting.fiscal_periods.approve',
        'accounting.settings.edit',
        'accounting.account_mappings.edit',
        'accounting.expenses.create',
        'accounting.expenses.edit',
        'accounting.expenses.delete',
    ],
    'hr.manage' => [
        'hr.employees.create',
        'hr.employees.edit',
        'hr.employees.delete',
        'hr.positions.create',
        'hr.positions.edit',
        'hr.positions.delete',
        'hr.shifts.create',
        'hr.shifts.edit',
        'hr.shifts.delete',
        'hr.allowances.create',
        'hr.allowances.edit',
        'hr.allowances.delete',
        'hr.deductions.create',
        'hr.deductions.edit',
        'hr.deductions.delete',
        'hr.overtime.create',
        'hr.overtime.edit',
        'hr.overtime.delete',
        'hr.cash_advances.create',
        'hr.cash_advances.edit',
        'hr.cash_advances.approve',
        'hr.attendance.create',
        'hr.leave.create',
        'hr.leave.edit',
        'hr.leave.approve',
        'hr.payroll.create',
        'hr.payroll.approve',
    ],
    'admin.manage' => [
        'admin.company.edit',
        'admin.branches.create',
        'admin.branches.edit',
        'admin.branches.delete',
        'admin.users.create',
        'admin.users.edit',
        'admin.users.delete',
        'admin.roles.edit',
        'admin.settings.edit',
    ],
    'pos.till' => [
        'pos.till_management.view',
        'pos.till_management.create',
        'pos.till_management.edit',
        'pos.checkout.create',
    ],
    'products.manage' => [
        'catalogue.products.create',
        'catalogue.products.edit',
        'catalogue.products.delete',
        'catalogue.categories.create',
        'catalogue.categories.edit',
        'catalogue.categories.delete',
        'catalogue.uoms.create',
        'catalogue.uoms.edit',
        'catalogue.uoms.delete',
        'catalogue.retail_packages.edit',
        'catalogue.vat_rates.create',
        'catalogue.vat_rates.edit',
        'catalogue.vat_rates.delete',
    ],
];
