<?php

/**
 * Maps route capability codes (erp.permission middleware) to feature permission codes.
 */
return [
    'sales.create' => [
        'sales.orders.create',
        'pos.checkout.create',
        'pos.terminal.view',
        'mobile.dashboard.view',
        'mobile.orders.view',
        'mobile.orders.create',
        'mobile.customers.view',
        'mobile.customers.create',
        'mobile.customers.edit',
        'mobile.catalog.view',
        'mobile.stock.view',
        'mobile.routes.view',
    ],
    'sales.manage' => [
        'sales.orders.edit',
        'sales.orders.delete',
        'sales.orders.approve',
        'sales.vouchers.create',
        'sales.vouchers.edit',
        'sales.vouchers.delete',
        'sales.loyalty_cards.create',
        'sales.loyalty_cards.edit',
        'sales.loyalty_cards.delete',
        'sales.reservations.create',
        'sales.reservations.edit',
        'sales.reservations.delete',
        'sales.returns.create',
        'mobile.orders.edit',
    ],
    'sales.view' => [
        'sales.orders.view',
        'sales.carts.view',
        'sales.vouchers.view',
        'sales.loyalty_cards.view',
        'sales.reservations.view',
        'sales.returns.view',
    ],
    'payments.manage' => [
        'payments.sale_payments.create',
        'payments.sale_payments.edit',
        'payments.customer_invoices.create',
        'payments.customer_invoices.edit',
        'payments.customer_payments.create',
        'payments.customer_payments.edit',
    ],
    'payments.view' => [
        'payments.sale_payments.view',
        'payments.customer_invoices.view',
        'payments.customer_payments.view',
    ],
    'catalogue.view' => [
        'catalogue.products.view',
        'catalogue.categories.view',
        'catalogue.uoms.view',
        'catalogue.retail_packages.view',
        'catalogue.vat_rates.view',
        'catalogue.price_history.view',
        'mobile.catalog.view',
    ],
    'inventory.view' => [
        'inventory.stock.view',
        'inventory.receipts.view',
        'inventory.movements.view',
        'inventory.transfers.view',
        'inventory.damages.view',
        'inventory.stock_take.view',
        'mobile.stock.view',
    ],
    'inventory.manage' => [
        'inventory.receipts.create',
        'inventory.receipts.approve',
        'inventory.transfers.create',
        'inventory.damages.create',
        'inventory.stock_take.create',
        'inventory.stock_take.approve',
    ],
    'reports.view' => [
        'reports.hub.view',
        'reports.daily_sales.view',
        'reports.stock_on_hand.view',
        'reports.profit_loss.view',
        'reports.top_debtors.view',
        'reports.stock_movement.view',
        'reports.vat_collected.view',
        'reports.till_sessions.view',
        'reports.expenses.view',
        'reports.customer_statement.view',
        'reports.builder.view',
        'reports.builder.create',
    ],
    'reports.builder' => [
        'reports.builder.view',
        'reports.builder.create',
        'reports.builder.edit',
        'reports.builder.delete',
    ],
    'ai.assist' => [
        'ai.assist.create',
    ],
    'purchasing.view' => [
        'purchasing.lpo.view',
        'purchasing.suppliers.view',
        'purchasing.supplier_payments.view',
        'purchasing.supplier_returns.view',
    ],
    'purchasing.manage' => [
        'purchasing.lpo.create',
        'purchasing.lpo.edit',
        'purchasing.lpo.delete',
        'purchasing.lpo.approve',
        'purchasing.suppliers.create',
        'purchasing.suppliers.edit',
        'purchasing.suppliers.delete',
        'purchasing.supplier_payments.create',
        'purchasing.supplier_returns.create',
    ],
    'customers.view' => [
        'customers.customers.view',
        'customers.statements.view',
        'mobile.customers.view',
    ],
    'customers.manage' => [
        'customers.customers.create',
        'customers.customers.edit',
        'customers.customers.delete',
        'mobile.customers.create',
        'mobile.customers.edit',
    ],
    'fulfillment.view' => [
        'fulfillment.drivers.view',
        'fulfillment.vehicles.view',
        'fulfillment.routes.view',
        'mobile.routes.view',
    ],
    'fulfillment.manage' => [
        'fulfillment.drivers.create',
        'fulfillment.drivers.edit',
        'fulfillment.drivers.delete',
        'fulfillment.vehicles.create',
        'fulfillment.vehicles.edit',
        'fulfillment.vehicles.delete',
        'fulfillment.routes.create',
        'fulfillment.routes.edit',
        'fulfillment.routes.delete',
    ],
    'accounting.view' => [
        'accounting.dashboard.view',
        'accounting.chart_of_accounts.view',
        'accounting.journal_entries.view',
        'accounting.fiscal_periods.view',
        'accounting.settings.view',
        'accounting.account_mappings.view',
        'accounting.export_queue.view',
        'accounting.general_ledger.view',
        'accounting.trial_balance.view',
        'accounting.profit_loss.view',
        'accounting.balance_sheet.view',
        'accounting.cash_flow.view',
        'accounting.accounts_receivable.view',
        'accounting.accounts_payable.view',
        'accounting.expenses.view',
    ],
    'accounting.manage' => [
        'accounting.chart_of_accounts.create',
        'accounting.chart_of_accounts.edit',
        'accounting.chart_of_accounts.delete',
        'accounting.journal_entries.create',
        'accounting.journal_entries.edit',
        'accounting.journal_entries.delete',
        'accounting.journal_entries.approve',
        'accounting.fiscal_periods.edit',
        'accounting.fiscal_periods.approve',
        'accounting.settings.edit',
        'accounting.account_mappings.edit',
        'accounting.expenses.create',
        'accounting.expenses.edit',
        'accounting.expenses.delete',
    ],
    'hr.view' => [
        'hr.employees.view',
        'hr.departments.view',
        'hr.positions.view',
        'hr.kpis.view',
        'hr.shifts.view',
        'hr.allowances.view',
        'hr.deductions.view',
        'hr.overtime.view',
        'hr.cash_advances.view',
        'hr.attendance.view',
        'hr.leave.view',
        'hr.payroll.view',
        'hr.holidays.view',
        'hr.leave_settings.view',
    ],
    'hr.manage' => [
        'hr.employees.create',
        'hr.employees.edit',
        'hr.employees.delete',
        'hr.departments.create',
        'hr.departments.edit',
        'hr.departments.delete',
        'hr.kpis.create',
        'hr.kpis.edit',
        'hr.kpis.delete',
        'hr.positions.create',
        'hr.positions.edit',
        'hr.positions.delete',
        'hr.shifts.create',
        'hr.shifts.edit',
        'hr.shifts.delete',
        'hr.allowances.create',
        'hr.allowances.edit',
        'hr.allowances.delete',
        'hr.deductions.create',
        'hr.deductions.edit',
        'hr.deductions.delete',
        'hr.overtime.create',
        'hr.overtime.edit',
        'hr.overtime.delete',
        'hr.cash_advances.create',
        'hr.cash_advances.edit',
        'hr.cash_advances.approve',
        'hr.attendance.create',
        'hr.leave.create',
        'hr.leave.edit',
        'hr.leave.approve',
        'hr.payroll.create',
        'hr.payroll.approve',
        'hr.holidays.create',
        'hr.holidays.edit',
        'hr.holidays.delete',
        'hr.leave_settings.edit',
    ],
    'admin.view' => [
        'admin.overview.view',
        'admin.company.view',
        'admin.branches.view',
        'admin.users.view',
        'admin.roles.view',
        'admin.audit.view',
        'admin.settings.view',
        'admin.payment_methods.view',
    ],
    'admin.manage' => [
        'admin.company.edit',
        'admin.branches.create',
        'admin.branches.edit',
        'admin.branches.delete',
        'admin.users.create',
        'admin.users.edit',
        'admin.users.delete',
        'admin.roles.edit',
        'admin.settings.edit',
        'admin.payment_methods.create',
        'admin.payment_methods.edit',
        'admin.payment_methods.delete',
    ],
    'pos.till' => [
        'pos.till_management.view',
        'pos.till_management.create',
        'pos.till_management.edit',
        'pos.checkout.create',
        'pos.terminal.view',
    ],
    'products.manage' => [
        'catalogue.products.create',
        'catalogue.products.edit',
        'catalogue.products.delete',
        'catalogue.categories.create',
        'catalogue.categories.edit',
        'catalogue.categories.delete',
        'catalogue.uoms.create',
        'catalogue.uoms.edit',
        'catalogue.uoms.delete',
        'catalogue.retail_packages.edit',
        'catalogue.vat_rates.create',
        'catalogue.vat_rates.edit',
        'catalogue.vat_rates.delete',
    ],
    'mobile.access' => [
        'mobile.dashboard.view',
        'mobile.orders.view',
        'mobile.orders.create',
        'mobile.customers.view',
        'mobile.customers.create',
        'mobile.customers.edit',
        'mobile.catalog.view',
        'mobile.stock.view',
        'mobile.routes.view',
    ],
];
