<?php

/**
 * Allowlisted data sources for the report builder.
 * Users compose reports from these fields only — no raw SQL.
 */
return [
    'sources' => array_merge([
        'sales' => [
            'label' => 'Sales',
            'module' => 'Sales',
            'description' => 'Completed sales orders',
            'table' => 'sales as s',
            'org_column' => 's.organization_id',
            'branch_column' => 's.branch_id',
            'default_date_column' => 's.completed_at',
            'left_joins' => ['customers'],
            'base_where' => [
                ['s.status', '=', 'completed'],
                ['s.archived', '=', 0],
            ],
            'joins' => [
                'branches' => ['branches as b', 'b.id', '=', 's.branch_id'],
                'customers' => ['customers as c', 'c.customer_num', '=', 's.customer_num'],
            ],
            'fields' => [
                'sale_day' => [
                    'label' => 'Sale date',
                    'expr' => 'DATE(s.completed_at)',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'order_num' => [
                    'label' => 'Order #',
                    'expr' => 's.order_num',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'sale_id' => [
                    'label' => 'Sale ID',
                    'expr' => 's.id',
                    'type' => 'number',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'channel' => [
                    'label' => 'Channel',
                    'expr' => 's.channel',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'customer_name' => [
                    'label' => 'Customer',
                    'expr' => "COALESCE(c.customer_name, s.customer_name_override)",
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'customers',
                ],
                'payment_status' => [
                    'label' => 'Payment status',
                    'expr' => 's.payment_status',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'order_total' => [
                    'label' => 'Order total',
                    'expr' => 's.order_total',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
                ],
                'amount_paid' => [
                    'label' => 'Amount paid',
                    'expr' => 's.amount_paid',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'total_vat' => [
                    'label' => 'VAT',
                    'expr' => 's.total_vat',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'order_count' => [
                    'label' => 'Orders',
                    'expr' => 's.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'sale_items' => [
            'label' => 'Sale line items',
            'module' => 'Sales',
            'description' => 'Products sold on completed orders',
            'table' => 'sale_items as si',
            'org_column' => 's.organization_id',
            'branch_column' => 's.branch_id',
            'default_date_column' => 's.completed_at',
            'always_join' => ['sales', 'products', 'branches'],
            'base_where' => [
                ['s.status', '=', 'completed'],
                ['s.archived', '=', 0],
            ],
            'joins' => [
                'sales' => ['sales as s', 's.id', '=', 'si.sale_id'],
                'products' => ['products as p', 'p.product_code', '=', 'si.product_code'],
                'branches' => ['branches as b', 'b.id', '=', 's.branch_id'],
            ],
            'fields' => [
                'sale_day' => [
                    'label' => 'Sale date',
                    'expr' => 'DATE(s.completed_at)',
                    'type' => 'date',
                    'groupable' => true,
                    'requires_join' => 'sales',
                ],
                'product_code' => [
                    'label' => 'Product code',
                    'expr' => 'si.product_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'product_name' => [
                    'label' => 'Product name',
                    'expr' => 'p.product_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'products',
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'channel' => [
                    'label' => 'Channel',
                    'expr' => 's.channel',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'sales',
                ],
                'quantity' => [
                    'label' => 'Quantity sold',
                    'expr' => 'si.quantity',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'line_revenue' => [
                    'label' => 'Line revenue',
                    'expr' => 'si.amount',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'line_vat' => [
                    'label' => 'Line VAT',
                    'expr' => 'si.product_vat',
                    'type' => 'money',
                    'aggregates' => ['sum'],
                ],
                'line_discount' => [
                    'label' => 'Discount',
                    'expr' => 'si.discount_given',
                    'type' => 'money',
                    'aggregates' => ['sum'],
                ],
            ],
        ],

        'customers' => [
            'label' => 'Customers',
            'module' => 'Sales',
            'description' => 'Customer master and balances',
            'table' => 'customers as c',
            'org_column' => 'c.organization_id',
            'branch_column' => 'c.branch_id',
            'default_date_column' => 'c.created_at',
            'left_joins' => ['routes', 'branches'],
            'base_where' => [
                ['c.deleted_at', '=', null],
            ],
            'joins' => [
                'routes' => ['routes as r', 'r.id', '=', 'c.route_id'],
                'branches' => ['branches as b', 'b.id', '=', 'c.branch_id'],
            ],
            'fields' => [
                'customer_num' => [
                    'label' => 'Customer code',
                    'expr' => 'c.customer_num',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'customer_name' => [
                    'label' => 'Customer name',
                    'expr' => 'c.customer_name',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'customer_type' => [
                    'label' => 'Type',
                    'expr' => 'c.customer_type',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'route_name' => [
                    'label' => 'Route',
                    'expr' => 'r.route_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'routes',
                ],
                'current_balance' => [
                    'label' => 'Current balance',
                    'expr' => 'c.current_balance',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'max'],
                ],
                'credit_limit' => [
                    'label' => 'Credit limit',
                    'expr' => 'c.credit_limit',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'customer_count' => [
                    'label' => 'Customers',
                    'expr' => 'c.customer_num',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'stock' => [
            'label' => 'Stock on hand',
            'module' => 'Inventory',
            'description' => 'Current inventory levels and valuation',
            'table' => 'current_stock as cs',
            'org_column' => 'p.organization_id',
            'branch_column' => 'cs.branch_id',
            'default_date_column' => null,
            'always_join' => ['products', 'branches', 'uoms'],
            'base_where' => [
                ['p.deleted_at', '=', null],
            ],
            'joins' => [
                'products' => [
                    'products as p',
                    'p.product_code',
                    '=',
                    'cs.product_code',
                    [['p.organization_id', '=', 'b.organization_id']],
                ],
                'branches' => ['branches as b', 'b.id', '=', 'cs.branch_id'],
                'uoms' => ['uoms as u', 'u.id', '=', 'p.unit_id'],
            ],
            'join_order' => ['branches', 'products', 'uoms'],
            'fields' => [
                'product_code' => [
                    'label' => 'Product code',
                    'expr' => 'cs.product_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'product_name' => [
                    'label' => 'Product name',
                    'expr' => 'p.product_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'products',
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'shop_quantity' => [
                    'label' => 'Shop qty',
                    'expr' => 'cs.shop_quantity',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg'],
                ],
                'store_quantity' => [
                    'label' => 'Store qty',
                    'expr' => 'cs.store_quantity',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg'],
                ],
                'total_qty' => [
                    'label' => 'Total qty',
                    'expr' => '(cs.shop_quantity + cs.store_quantity)',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg'],
                ],
                'cost_value' => [
                    'label' => 'Cost value',
                    'expr' => '((cs.shop_quantity + cs.store_quantity) / GREATEST(COALESCE(u.conversion_factor, 1), 1)) * COALESCE(NULLIF(p.last_cost_price, 0), (SELECT sr.cost_price FROM stock_receipts sr WHERE sr.organization_id = b.organization_id AND sr.product_code = p.product_code AND sr.cost_price IS NOT NULL AND sr.cost_price > 0 ORDER BY sr.id DESC LIMIT 1), 0)',
                    'type' => 'money',
                    'aggregates' => ['sum'],
                    'requires_join' => 'products',
                ],
                'shop_cost_value' => [
                    'label' => 'Shop cost value',
                    'expr' => '(cs.shop_quantity / GREATEST(COALESCE(u.conversion_factor, 1), 1)) * COALESCE(NULLIF(p.last_cost_price, 0), (SELECT sr.cost_price FROM stock_receipts sr WHERE sr.organization_id = b.organization_id AND sr.product_code = p.product_code AND sr.cost_price IS NOT NULL AND sr.cost_price > 0 ORDER BY sr.id DESC LIMIT 1), 0)',
                    'type' => 'money',
                    'aggregates' => ['sum'],
                    'requires_join' => 'products',
                ],
                'store_cost_value' => [
                    'label' => 'Store cost value',
                    'expr' => '(cs.store_quantity / GREATEST(COALESCE(u.conversion_factor, 1), 1)) * COALESCE(NULLIF(p.last_cost_price, 0), (SELECT sr.cost_price FROM stock_receipts sr WHERE sr.organization_id = b.organization_id AND sr.product_code = p.product_code AND sr.cost_price IS NOT NULL AND sr.cost_price > 0 ORDER BY sr.id DESC LIMIT 1), 0)',
                    'type' => 'money',
                    'aggregates' => ['sum'],
                    'requires_join' => 'products',
                ],
                'retail_value' => [
                    'label' => 'Retail value',
                    'expr' => '((cs.shop_quantity + cs.store_quantity) / GREATEST(COALESCE(u.conversion_factor, 1), 1)) * p.unit_price',
                    'type' => 'money',
                    'aggregates' => ['sum'],
                    'requires_join' => 'products',
                ],
                'sku_count' => [
                    'label' => 'SKUs',
                    'expr' => 'cs.product_code',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'invoices' => [
            'label' => 'Customer invoices',
            'module' => 'Sales',
            'description' => 'Invoices and balances',
            'table' => 'customer_invoices as ci',
            'org_column' => 'ci.organization_id',
            'branch_column' => 'ci.branch_id',
            'default_date_column' => 'ci.invoice_date',
            'left_joins' => ['customers', 'branches'],
            'base_where' => [
                ['ci.deleted_at', '=', null],
            ],
            'joins' => [
                'customers' => ['customers as c', 'c.customer_num', '=', 'ci.customer_num'],
                'branches' => ['branches as b', 'b.id', '=', 'ci.branch_id'],
            ],
            'fields' => [
                'invoice_date' => [
                    'label' => 'Invoice date',
                    'expr' => 'ci.invoice_date',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'invoice_number' => [
                    'label' => 'Invoice #',
                    'expr' => 'ci.invoice_number',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'customer_name' => [
                    'label' => 'Customer',
                    'expr' => 'c.customer_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'customers',
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'invoice_total' => [
                    'label' => 'Invoice total',
                    'expr' => 'ci.invoice_total',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'amount_paid' => [
                    'label' => 'Amount paid',
                    'expr' => 'ci.amount_paid',
                    'type' => 'money',
                    'aggregates' => ['sum'],
                ],
                'balance_due' => [
                    'label' => 'Balance due',
                    'expr' => 'ci.balance_due',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'max'],
                ],
                'invoice_count' => [
                    'label' => 'Invoices',
                    'expr' => 'ci.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'products' => [
            'label' => 'Products',
            'module' => 'Inventory',
            'description' => 'Product catalog and pricing',
            'table' => 'products as p',
            'org_column' => 'p.organization_id',
            'branch_column' => null,
            'default_date_column' => 'p.created_at',
            'base_where' => [
                ['p.deleted_at', '=', null],
            ],
            'joins' => [
                'suppliers' => ['suppliers as sup', 'sup.id', '=', 'p.supplier_id'],
            ],
            'left_joins' => ['suppliers'],
            'fields' => [
                'product_code' => [
                    'label' => 'Product code',
                    'expr' => 'p.product_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'product_name' => [
                    'label' => 'Product name',
                    'expr' => 'p.product_name',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'supplier_name' => [
                    'label' => 'Supplier',
                    'expr' => 'sup.supplier_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'suppliers',
                ],
                'unit_price' => [
                    'label' => 'Unit price',
                    'expr' => 'p.unit_price',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'min', 'max'],
                ],
                'last_cost_price' => [
                    'label' => 'Last cost',
                    'expr' => 'p.last_cost_price',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'min', 'max'],
                ],
                'reorder_point' => [
                    'label' => 'Reorder point',
                    'expr' => 'p.reorder_point',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'max'],
                ],
                'product_count' => [
                    'label' => 'Products',
                    'expr' => 'p.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'sale_payments' => [
            'label' => 'Sale payments',
            'module' => 'Sales',
            'description' => 'Payments collected on sales',
            'table' => 'sale_payments as sp',
            'org_column' => 's.organization_id',
            'branch_column' => 's.branch_id',
            'default_date_column' => 'sp.paid_at',
            'always_join' => ['sales'],
            'joins' => [
                'sales' => ['sales as s', 's.id', '=', 'sp.sale_id'],
                'payment_methods' => ['payment_methods as pm', 'pm.id', '=', 'sp.payment_method_id'],
                'branches' => ['branches as b', 'b.id', '=', 's.branch_id'],
            ],
            'left_joins' => ['payment_methods', 'branches'],
            'fields' => [
                'payment_day' => [
                    'label' => 'Payment date',
                    'expr' => 'DATE(sp.paid_at)',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'payment_method' => [
                    'label' => 'Payment method',
                    'expr' => 'pm.method_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'payment_methods',
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'channel' => [
                    'label' => 'Channel',
                    'expr' => 's.channel',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'sales',
                ],
                'amount' => [
                    'label' => 'Amount',
                    'expr' => 'sp.amount',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
                ],
                'payment_count' => [
                    'label' => 'Payments',
                    'expr' => 'sp.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'returns' => [
            'label' => 'Customer returns',
            'module' => 'Sales',
            'description' => 'Product returns from customers',
            'table' => 'returns as r',
            'org_column' => 'b.organization_id',
            'branch_column' => 'r.branch_id',
            'default_date_column' => 'r.created_at',
            'always_join' => ['branches'],
            'joins' => [
                'branches' => ['branches as b', 'b.id', '=', 'r.branch_id'],
                'products' => ['products as p', 'p.product_code', '=', 'r.product_code'],
                'sales' => ['sales as s', 's.id', '=', 'r.sale_id'],
            ],
            'left_joins' => ['products', 'sales'],
            'fields' => [
                'return_day' => [
                    'label' => 'Return date',
                    'expr' => 'r.created_at',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'product_code' => [
                    'label' => 'Product code',
                    'expr' => 'r.product_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'product_name' => [
                    'label' => 'Product name',
                    'expr' => 'p.product_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'products',
                ],
                'return_type' => [
                    'label' => 'Return type',
                    'expr' => 'r.return_type',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'quantity' => [
                    'label' => 'Quantity',
                    'expr' => 'r.quantity',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'amount' => [
                    'label' => 'Return amount',
                    'expr' => 'r.amount',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'return_count' => [
                    'label' => 'Returns',
                    'expr' => 'r.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'inventory_transactions' => [
            'label' => 'Inventory transactions',
            'module' => 'Inventory',
            'description' => 'Stock movements and adjustments',
            'table' => 'inventory_transactions as it',
            'org_column' => 'b.organization_id',
            'branch_column' => 'it.branch_id',
            'default_date_column' => 'it.created_at',
            'always_join' => ['branches'],
            'joins' => [
                'branches' => ['branches as b', 'b.id', '=', 'it.branch_id'],
                'products' => ['products as p', 'p.product_code', '=', 'it.product_code'],
            ],
            'left_joins' => ['products'],
            'fields' => [
                'transaction_day' => [
                    'label' => 'Transaction date',
                    'expr' => 'DATE(it.created_at)',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'product_code' => [
                    'label' => 'Product code',
                    'expr' => 'it.product_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'product_name' => [
                    'label' => 'Product name',
                    'expr' => 'p.product_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'products',
                ],
                'transaction_type' => [
                    'label' => 'Type',
                    'expr' => 'it.transaction_type',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'stock_location' => [
                    'label' => 'Location',
                    'expr' => 'it.stock_location',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'quantity_change' => [
                    'label' => 'Qty change',
                    'expr' => 'it.quantity_change',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'unit_cost' => [
                    'label' => 'Unit cost',
                    'expr' => 'it.unit_cost',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'transaction_count' => [
                    'label' => 'Transactions',
                    'expr' => 'it.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'stock_receipts' => [
            'label' => 'Stock receipts',
            'module' => 'Inventory',
            'description' => 'Goods received into stock',
            'table' => 'stock_receipts as sr',
            'org_column' => 'sr.organization_id',
            'branch_column' => 'sr.branch_id',
            'default_date_column' => 'sr.created_at',
            'joins' => [
                'products' => ['products as p', 'p.product_code', '=', 'sr.product_code'],
                'branches' => ['branches as b', 'b.id', '=', 'sr.branch_id'],
            ],
            'left_joins' => ['products', 'branches'],
            'fields' => [
                'receipt_day' => [
                    'label' => 'Receipt date',
                    'expr' => 'DATE(sr.created_at)',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'product_code' => [
                    'label' => 'Product code',
                    'expr' => 'sr.product_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'product_name' => [
                    'label' => 'Product name',
                    'expr' => 'p.product_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'products',
                ],
                'stock_location' => [
                    'label' => 'Location',
                    'expr' => 'sr.stock_location',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'units_received' => [
                    'label' => 'Units received',
                    'expr' => 'sr.units_received',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'cost_price' => [
                    'label' => 'Cost price',
                    'expr' => 'sr.cost_price',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'receipt_count' => [
                    'label' => 'Receipts',
                    'expr' => 'sr.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'stock_movements' => [
            'label' => 'Stock transfers',
            'module' => 'Inventory',
            'description' => 'Shop/store stock transfers',
            'table' => 'stock_movement_history as smh',
            'org_column' => 'b.organization_id',
            'branch_column' => 'smh.branch_id',
            'default_date_column' => 'smh.created_at',
            'always_join' => ['branches'],
            'joins' => [
                'branches' => ['branches as b', 'b.id', '=', 'smh.branch_id'],
                'products' => ['products as p', 'p.product_code', '=', 'smh.product_code'],
            ],
            'left_joins' => ['products'],
            'fields' => [
                'move_day' => [
                    'label' => 'Move date',
                    'expr' => 'DATE(smh.created_at)',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'product_code' => [
                    'label' => 'Product code',
                    'expr' => 'smh.product_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'from_location' => [
                    'label' => 'From',
                    'expr' => 'smh.from_location',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'to_location' => [
                    'label' => 'To',
                    'expr' => 'smh.to_location',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'quantity_moved' => [
                    'label' => 'Qty moved',
                    'expr' => 'smh.quantity_moved',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'move_count' => [
                    'label' => 'Transfers',
                    'expr' => 'smh.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'damages' => [
            'label' => 'Stock damages',
            'module' => 'Inventory',
            'description' => 'Damaged or written-off stock',
            'table' => 'damages as d',
            'org_column' => 'b.organization_id',
            'branch_column' => 'd.branch_id',
            'default_date_column' => 'd.created_at',
            'always_join' => ['branches'],
            'joins' => [
                'branches' => ['branches as b', 'b.id', '=', 'd.branch_id'],
                'products' => ['products as p', 'p.product_code', '=', 'd.product_code'],
            ],
            'left_joins' => ['products'],
            'fields' => [
                'damage_day' => [
                    'label' => 'Date',
                    'expr' => 'DATE(d.created_at)',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'product_code' => [
                    'label' => 'Product code',
                    'expr' => 'd.product_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'stock_location' => [
                    'label' => 'Location',
                    'expr' => 'd.stock_location',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'quantity' => [
                    'label' => 'Quantity',
                    'expr' => 'd.quantity',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'damage_count' => [
                    'label' => 'Damage records',
                    'expr' => 'd.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'suppliers' => [
            'label' => 'Suppliers',
            'module' => 'Purchasing',
            'description' => 'Supplier master data',
            'table' => 'suppliers as sup',
            'org_column' => 'sup.organization_id',
            'branch_column' => null,
            'default_date_column' => 'sup.created_at',
            'base_where' => [
                ['sup.deleted_at', '=', null],
            ],
            'fields' => [
                'supplier_code' => [
                    'label' => 'Supplier code',
                    'expr' => 'sup.supplier_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'supplier_name' => [
                    'label' => 'Supplier name',
                    'expr' => 'sup.supplier_name',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'town' => [
                    'label' => 'Town',
                    'expr' => 'sup.town',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'is_active' => [
                    'label' => 'Active',
                    'expr' => 'sup.is_active',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'supplier_count' => [
                    'label' => 'Suppliers',
                    'expr' => 'sup.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'lpo_orders' => [
            'label' => 'Purchase orders (LPO)',
            'module' => 'Purchasing',
            'description' => 'Local purchase orders',
            'table' => 'lpo_mst as lpo',
            'org_column' => 'sup.organization_id',
            'branch_column' => null,
            'default_date_column' => 'lpo.created_at',
            'always_join' => ['suppliers'],
            'base_where' => [
                ['lpo.deleted_at', '=', null],
            ],
            'joins' => [
                'suppliers' => ['suppliers as sup', 'sup.id', '=', 'lpo.supplier_id'],
            ],
            'fields' => [
                'lpo_day' => [
                    'label' => 'LPO date',
                    'expr' => 'DATE(lpo.created_at)',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'supplier_name' => [
                    'label' => 'Supplier',
                    'expr' => 'sup.supplier_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'suppliers',
                ],
                'reference_number' => [
                    'label' => 'Reference',
                    'expr' => 'lpo.reference_number',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'total_amount' => [
                    'label' => 'Total amount',
                    'expr' => 'lpo.total_amount',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
                ],
                'net_amount' => [
                    'label' => 'Net amount',
                    'expr' => 'lpo.net_amount',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'lpo_count' => [
                    'label' => 'LPOs',
                    'expr' => 'lpo.lpo_no',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'lpo_lines' => [
            'label' => 'LPO line items',
            'module' => 'Purchasing',
            'description' => 'Products on purchase orders',
            'table' => 'lpo_txn as lt',
            'org_column' => 'sup.organization_id',
            'branch_column' => null,
            'default_date_column' => 'lpo.created_at',
            'always_join' => ['lpo', 'suppliers'],
            'base_where' => [
                ['lpo.deleted_at', '=', null],
            ],
            'joins' => [
                'lpo' => ['lpo_mst as lpo', 'lpo.lpo_no', '=', 'lt.lpo_no'],
                'suppliers' => ['suppliers as sup', 'sup.id', '=', 'lpo.supplier_id'],
                'products' => ['products as p', 'p.product_code', '=', 'lt.product_code'],
            ],
            'left_joins' => ['products'],
            'fields' => [
                'lpo_day' => [
                    'label' => 'LPO date',
                    'expr' => 'DATE(lpo.created_at)',
                    'type' => 'date',
                    'groupable' => true,
                    'requires_join' => 'lpo',
                ],
                'supplier_name' => [
                    'label' => 'Supplier',
                    'expr' => 'sup.supplier_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'suppliers',
                ],
                'product_code' => [
                    'label' => 'Product code',
                    'expr' => 'lt.product_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'product_name' => [
                    'label' => 'Product name',
                    'expr' => 'p.product_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'products',
                ],
                'ordered_qty' => [
                    'label' => 'Ordered qty',
                    'expr' => 'lt.ordered_qty',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'received_qty' => [
                    'label' => 'Received qty',
                    'expr' => 'lt.received_qty',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg'],
                ],
                'cost_price' => [
                    'label' => 'Cost price',
                    'expr' => 'lt.cost_price',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'line_count' => [
                    'label' => 'Lines',
                    'expr' => 'lt.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'supplier_returns' => [
            'label' => 'Supplier returns',
            'module' => 'Purchasing',
            'description' => 'Returns to suppliers',
            'table' => 'supplier_return_documents as srd',
            'org_column' => 'srd.organization_id',
            'branch_column' => 'srd.branch_id',
            'default_date_column' => 'srd.created_at',
            'joins' => [
                'suppliers' => ['suppliers as sup', 'sup.id', '=', 'srd.supplier_id'],
                'branches' => ['branches as b', 'b.id', '=', 'srd.branch_id'],
            ],
            'left_joins' => ['suppliers', 'branches'],
            'fields' => [
                'return_day' => [
                    'label' => 'Return date',
                    'expr' => 'DATE(srd.created_at)',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'supplier_name' => [
                    'label' => 'Supplier',
                    'expr' => 'sup.supplier_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'suppliers',
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'status' => [
                    'label' => 'Status',
                    'expr' => 'srd.status',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'source_type' => [
                    'label' => 'Source',
                    'expr' => 'srd.source_type',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'return_count' => [
                    'label' => 'Returns',
                    'expr' => 'srd.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'expenses' => [
            'label' => 'Expenses',
            'module' => 'Accounting',
            'description' => 'Branch expenses and bills',
            'table' => 'expenses as e',
            'org_column' => 'b.organization_id',
            'branch_column' => 'e.branch_id',
            'default_date_column' => 'e.expense_date',
            'always_join' => ['branches'],
            'base_where' => [
                ['e.deleted_at', '=', null],
            ],
            'joins' => [
                'branches' => ['branches as b', 'b.id', '=', 'e.branch_id'],
                'expense_groups' => ['expense_groups as eg', 'eg.id', '=', 'e.expense_group_id'],
                'payment_methods' => ['payment_methods as pm', 'pm.id', '=', 'e.payment_method_id'],
            ],
            'left_joins' => ['expense_groups', 'payment_methods'],
            'fields' => [
                'expense_date' => [
                    'label' => 'Expense date',
                    'expr' => 'e.expense_date',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'expense_group' => [
                    'label' => 'Group',
                    'expr' => 'eg.group_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'expense_groups',
                ],
                'payment_method' => [
                    'label' => 'Payment method',
                    'expr' => 'pm.method_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'payment_methods',
                ],
                'description' => [
                    'label' => 'Description',
                    'expr' => 'e.description',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'expense_amount' => [
                    'label' => 'Amount',
                    'expr' => 'e.expense_amount',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
                ],
                'expense_count' => [
                    'label' => 'Expenses',
                    'expr' => 'e.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'journal_entries' => [
            'label' => 'Journal entries',
            'module' => 'Accounting',
            'description' => 'General ledger journal entries',
            'table' => 'journal_entries as je',
            'org_column' => 'je.organization_id',
            'branch_column' => 'je.branch_id',
            'default_date_column' => 'je.entry_date',
            'joins' => [
                'branches' => ['branches as b', 'b.id', '=', 'je.branch_id'],
            ],
            'left_joins' => ['branches'],
            'fields' => [
                'entry_date' => [
                    'label' => 'Entry date',
                    'expr' => 'je.entry_date',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'entry_number' => [
                    'label' => 'Entry #',
                    'expr' => 'je.entry_number',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'status' => [
                    'label' => 'Status',
                    'expr' => 'je.status',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'reference_type' => [
                    'label' => 'Reference type',
                    'expr' => 'je.reference_type',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'entry_count' => [
                    'label' => 'Entries',
                    'expr' => 'je.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'journal_lines' => [
            'label' => 'Journal lines',
            'module' => 'Accounting',
            'description' => 'Debit/credit lines on journal entries',
            'table' => 'journal_entry_lines as jel',
            'org_column' => 'je.organization_id',
            'branch_column' => 'je.branch_id',
            'default_date_column' => 'je.entry_date',
            'always_join' => ['journal_entries'],
            'joins' => [
                'journal_entries' => ['journal_entries as je', 'je.id', '=', 'jel.journal_entry_id'],
                'accounts' => ['chart_of_accounts as coa', 'coa.id', '=', 'jel.account_id'],
                'branches' => ['branches as b', 'b.id', '=', 'je.branch_id'],
            ],
            'left_joins' => ['accounts', 'branches'],
            'fields' => [
                'entry_date' => [
                    'label' => 'Entry date',
                    'expr' => 'je.entry_date',
                    'type' => 'date',
                    'groupable' => true,
                    'requires_join' => 'journal_entries',
                ],
                'account_code' => [
                    'label' => 'Account code',
                    'expr' => 'coa.account_code',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'accounts',
                ],
                'account_name' => [
                    'label' => 'Account name',
                    'expr' => 'coa.account_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'accounts',
                ],
                'account_type' => [
                    'label' => 'Account type',
                    'expr' => 'coa.account_type',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'accounts',
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'debit' => [
                    'label' => 'Debit',
                    'expr' => 'jel.debit',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'credit' => [
                    'label' => 'Credit',
                    'expr' => 'jel.credit',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'line_count' => [
                    'label' => 'Lines',
                    'expr' => 'jel.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'chart_of_accounts' => [
            'label' => 'Chart of accounts',
            'module' => 'Accounting',
            'description' => 'GL account master',
            'table' => 'chart_of_accounts as coa',
            'org_column' => 'coa.organization_id',
            'branch_column' => null,
            'default_date_column' => 'coa.created_at',
            'fields' => [
                'account_code' => [
                    'label' => 'Account code',
                    'expr' => 'coa.account_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'account_name' => [
                    'label' => 'Account name',
                    'expr' => 'coa.account_name',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'account_type' => [
                    'label' => 'Account type',
                    'expr' => 'coa.account_type',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'is_active' => [
                    'label' => 'Active',
                    'expr' => 'coa.is_active',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'account_count' => [
                    'label' => 'Accounts',
                    'expr' => 'coa.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'employees' => [
            'label' => 'Employees',
            'module' => 'HR',
            'description' => 'Employee master records',
            'table' => 'employees as emp',
            'org_column' => 'emp.organization_id',
            'branch_column' => 'emp.branch_id',
            'default_date_column' => 'emp.created_at',
            'joins' => [
                'departments' => ['departments as dept', 'dept.id', '=', 'emp.department_id'],
                'positions' => ['positions as pos', 'pos.id', '=', 'emp.position_id'],
                'branches' => ['branches as b', 'b.id', '=', 'emp.branch_id'],
            ],
            'left_joins' => ['departments', 'positions', 'branches'],
            'fields' => [
                'employee_code' => [
                    'label' => 'Employee code',
                    'expr' => 'emp.employee_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'full_name' => [
                    'label' => 'Name',
                    'expr' => 'emp.full_name',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'department_name' => [
                    'label' => 'Department',
                    'expr' => 'dept.department_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'departments',
                ],
                'position_title' => [
                    'label' => 'Position',
                    'expr' => 'pos.position_title',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'positions',
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'employment_status' => [
                    'label' => 'Status',
                    'expr' => 'emp.employment_status',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'employment_type' => [
                    'label' => 'Type',
                    'expr' => 'emp.employment_type',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'base_salary' => [
                    'label' => 'Base salary',
                    'expr' => 'emp.base_salary',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'min', 'max'],
                ],
                'employee_count' => [
                    'label' => 'Employees',
                    'expr' => 'emp.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'attendance' => [
            'label' => 'Attendance',
            'module' => 'HR',
            'description' => 'Employee attendance records',
            'table' => 'employee_attendance as ea',
            'org_column' => 'ea.organization_id',
            'branch_column' => 'ea.branch_id',
            'default_date_column' => 'ea.attendance_date',
            'joins' => [
                'employees' => ['employees as emp', 'emp.id', '=', 'ea.employee_id'],
                'branches' => ['branches as b', 'b.id', '=', 'ea.branch_id'],
            ],
            'left_joins' => ['employees', 'branches'],
            'fields' => [
                'attendance_date' => [
                    'label' => 'Date',
                    'expr' => 'ea.attendance_date',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'employee_name' => [
                    'label' => 'Employee',
                    'expr' => 'emp.full_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'employees',
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'status' => [
                    'label' => 'Status',
                    'expr' => 'ea.status',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'login_channel' => [
                    'label' => 'Login channel',
                    'expr' => "CASE ea.source WHEN 'field_rep' THEN 'Mobile sales app' WHEN 'clock_device' THEN 'Premises' WHEN 'company_mobile' THEN 'Premises' ELSE 'Manual entry' END",
                    'type' => 'string',
                    'groupable' => true,
                ],
                'capture_method' => [
                    'label' => 'Capture method',
                    'expr' => "CASE ea.source WHEN 'field_rep' THEN 'Mobile sales app' WHEN 'company_mobile' THEN 'Premises (company phone)' WHEN 'clock_device' THEN 'Premises (clock)' ELSE 'Manual entry' END",
                    'type' => 'string',
                    'groupable' => true,
                ],
                'check_in' => [
                    'label' => 'Check in',
                    'expr' => 'ea.check_in',
                    'type' => 'string',
                ],
                'check_out' => [
                    'label' => 'Check out',
                    'expr' => 'ea.check_out',
                    'type' => 'string',
                ],
                'hours_worked' => [
                    'label' => 'Hours worked',
                    'expr' => 'ea.hours_worked',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'attendance_count' => [
                    'label' => 'Records',
                    'expr' => 'ea.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'payroll_lines' => [
            'label' => 'Payroll lines',
            'module' => 'HR',
            'description' => 'Payroll per employee per run',
            'table' => 'payroll_lines as pl',
            'org_column' => 'emp.organization_id',
            'branch_column' => 'emp.branch_id',
            'default_date_column' => 'pr.run_date',
            'always_join' => ['payroll_runs', 'employees'],
            'joins' => [
                'payroll_runs' => ['payroll_runs as pr', 'pr.id', '=', 'pl.payroll_run_id'],
                'employees' => ['employees as emp', 'emp.id', '=', 'pl.employee_id'],
                'departments' => ['departments as dept', 'dept.id', '=', 'emp.department_id'],
            ],
            'left_joins' => ['departments'],
            'fields' => [
                'run_date' => [
                    'label' => 'Run date',
                    'expr' => 'pr.run_date',
                    'type' => 'date',
                    'groupable' => true,
                    'requires_join' => 'payroll_runs',
                ],
                'employee_name' => [
                    'label' => 'Employee',
                    'expr' => 'emp.full_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'employees',
                ],
                'department_name' => [
                    'label' => 'Department',
                    'expr' => 'dept.department_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'departments',
                ],
                'run_status' => [
                    'label' => 'Run status',
                    'expr' => 'pr.status',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'payroll_runs',
                ],
                'gross_pay' => [
                    'label' => 'Gross pay',
                    'expr' => 'pl.gross_pay',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg', 'count'],
                ],
                'deductions' => [
                    'label' => 'Deductions',
                    'expr' => 'pl.deductions',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'net_pay' => [
                    'label' => 'Net pay',
                    'expr' => 'pl.net_pay',
                    'type' => 'money',
                    'aggregates' => ['sum', 'avg'],
                ],
                'line_count' => [
                    'label' => 'Lines',
                    'expr' => 'pl.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'employee_kpis' => [
            'label' => 'Employee KPIs',
            'module' => 'HR',
            'description' => 'Employee key performance indicators',
            'table' => 'employee_kpis as ek',
            'org_column' => 'ek.organization_id',
            'branch_column' => null,
            'default_date_column' => 'ek.period_start',
            'joins' => [
                'employees' => ['employees as emp', 'emp.id', '=', 'ek.employee_id'],
            ],
            'left_joins' => ['employees'],
            'fields' => [
                'period_start' => [
                    'label' => 'Period start',
                    'expr' => 'ek.period_start',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'employee_name' => [
                    'label' => 'Employee',
                    'expr' => 'emp.full_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'employees',
                ],
                'label' => [
                    'label' => 'KPI label',
                    'expr' => 'ek.label',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'kpi_code' => [
                    'label' => 'KPI code',
                    'expr' => 'ek.kpi_code',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'target_value' => [
                    'label' => 'Target',
                    'expr' => 'ek.target_value',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'min', 'max'],
                ],
                'actual_value' => [
                    'label' => 'Actual',
                    'expr' => 'ek.actual_value',
                    'type' => 'number',
                    'aggregates' => ['sum', 'avg', 'min', 'max'],
                ],
                'kpi_count' => [
                    'label' => 'KPIs',
                    'expr' => 'ek.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],

        'audit_logs' => [
            'label' => 'Audit logs',
            'module' => 'Administration',
            'description' => 'System audit trail',
            'table' => 'audit_logs as al',
            'org_column' => 'u.organization_id',
            'branch_column' => 'al.branch_id',
            'default_date_column' => 'al.created_at',
            'always_join' => ['users'],
            'joins' => [
                'users' => ['users as u', 'u.id', '=', 'al.user_id'],
                'branches' => ['branches as b', 'b.id', '=', 'al.branch_id'],
            ],
            'left_joins' => ['branches'],
            'fields' => [
                'log_day' => [
                    'label' => 'Date',
                    'expr' => 'DATE(al.created_at)',
                    'type' => 'date',
                    'groupable' => true,
                ],
                'username' => [
                    'label' => 'User',
                    'expr' => 'u.username',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'users',
                ],
                'action' => [
                    'label' => 'Action',
                    'expr' => 'al.action',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'table_name' => [
                    'label' => 'Table',
                    'expr' => 'al.table_name',
                    'type' => 'string',
                    'groupable' => true,
                ],
                'branch_name' => [
                    'label' => 'Branch',
                    'expr' => 'b.branch_name',
                    'type' => 'string',
                    'groupable' => true,
                    'requires_join' => 'branches',
                ],
                'log_count' => [
                    'label' => 'Events',
                    'expr' => 'al.id',
                    'type' => 'number',
                    'aggregates' => ['count'],
                ],
            ],
        ],
    ], is_file(__DIR__.'/report_builder_extended.php')
        ? require __DIR__.'/report_builder_extended.php'
        : []),

    'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
    'chart_types' => ['bar', 'donut'],
    'max_columns' => null,
    'max_group_by' => null,
    'max_chart_limit' => null,
    'max_sources' => 4,

    'blend_dimensions' => is_file(__DIR__.'/report_builder_blend.php')
        ? require __DIR__.'/report_builder_blend.php'
        : [],

    'source_links' => is_file(__DIR__.'/report_builder_links.php')
        ? require __DIR__.'/report_builder_links.php'
        : ['extra_edges' => []],

    /*
     * Report builder data sources allowed per product workspace.
     * Keys match config/erp_workspaces.php and the web workspace switcher.
     */
    'workspace_source_modules' => [
        'backoffice' => ['Sales', 'Inventory', 'Purchasing'],
        'accounting' => ['Accounting'],
        'hr' => ['HR'],
        'distribution' => ['Sales', 'Distribution'],
        'admin' => ['Administration', 'Sales', 'Inventory', 'Purchasing', 'Accounting', 'HR'],
        'pos' => [],
    ],
];
