<?php

/**
 * Hospitality Report Builder sources (F&B checks, folios, rooms).
 * Separate from retail sales — used by hospitality_backoffice workspace.
 */
return [
    'hospitality_checks' => [
        'label' => 'F&B checks',
        'module' => 'Hospitality',
        'description' => 'Bar and restaurant checks (not retail sales)',
        'table' => 'hospitality_checks as hc',
        'org_column' => 'hc.organization_id',
        'branch_column' => 'hc.branch_id',
        'default_date_column' => 'hc.opened_at',
        'left_joins' => ['outlets', 'branches', 'floor_tables'],
        'joins' => [
            'outlets' => ['hospitality_outlets as ho', 'ho.id', '=', 'hc.outlet_id'],
            'branches' => ['branches as b', 'b.id', '=', 'hc.branch_id'],
            'floor_tables' => ['hospitality_floor_tables as hft', 'hft.id', '=', 'hc.floor_table_id'],
        ],
        'fields' => [
            'check_day' => [
                'label' => 'Open date',
                'expr' => 'DATE(hc.opened_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'check_number' => [
                'label' => 'Check number',
                'expr' => 'hc.check_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'hc.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'service_mode' => [
                'label' => 'Service mode',
                'expr' => 'hc.service_mode',
                'type' => 'string',
                'groupable' => true,
            ],
            'guest_name' => [
                'label' => 'Guest name',
                'expr' => 'hc.guest_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'outlet_name' => [
                'label' => 'Outlet',
                'expr' => 'ho.name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'outlets',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'table_label' => [
                'label' => 'Table',
                'expr' => 'hft.label',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'floor_tables',
            ],
            'subtotal' => [
                'label' => 'Subtotal',
                'expr' => 'hc.subtotal',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max'],
            ],
            'vat_total' => [
                'label' => 'VAT',
                'expr' => 'hc.vat_total',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'total' => [
                'label' => 'Check total',
                'expr' => 'hc.total',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max', 'count'],
            ],
            'amount_paid' => [
                'label' => 'Amount paid',
                'expr' => 'hc.amount_paid',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'check_count' => [
                'label' => 'Checks',
                'expr' => 'hc.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'hospitality_check_lines' => [
        'label' => 'F&B check lines',
        'module' => 'Hospitality',
        'description' => 'Line items on hospitality checks',
        'table' => 'hospitality_check_lines as hcl',
        'org_column' => 'hcl.organization_id',
        'branch_column' => 'hc.branch_id',
        'default_date_column' => 'hc.opened_at',
        'always_join' => ['checks'],
        'left_joins' => ['products', 'outlets', 'branches'],
        'joins' => [
            'checks' => ['hospitality_checks as hc', 'hc.id', '=', 'hcl.check_id'],
            'products' => ['products as p', 'p.product_code', '=', 'hcl.product_code'],
            'outlets' => ['hospitality_outlets as ho', 'ho.id', '=', 'hc.outlet_id'],
            'branches' => ['branches as b', 'b.id', '=', 'hc.branch_id'],
        ],
        'fields' => [
            'check_day' => [
                'label' => 'Open date',
                'expr' => 'DATE(hc.opened_at)',
                'type' => 'date',
                'groupable' => true,
                'requires_join' => 'checks',
            ],
            'description' => [
                'label' => 'Item description',
                'expr' => 'hcl.description',
                'type' => 'string',
                'groupable' => true,
            ],
            'product_name' => [
                'label' => 'Product name',
                'expr' => 'p.product_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'products',
            ],
            'outlet_name' => [
                'label' => 'Outlet',
                'expr' => 'ho.name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'outlets',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'qty' => [
                'label' => 'Quantity',
                'expr' => 'hcl.qty',
                'type' => 'number',
                'aggregates' => ['sum', 'avg', 'min', 'max'],
            ],
            'unit_price' => [
                'label' => 'Unit price',
                'expr' => 'hcl.unit_price',
                'type' => 'money',
                'aggregates' => ['avg', 'min', 'max'],
            ],
            'line_total' => [
                'label' => 'Line total',
                'expr' => 'hcl.line_total',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max'],
            ],
            'line_count' => [
                'label' => 'Lines',
                'expr' => 'hcl.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'hospitality_check_payments' => [
        'label' => 'F&B check payments',
        'module' => 'Hospitality',
        'description' => 'Payments taken against hospitality checks',
        'table' => 'hospitality_check_payments as hcp',
        'org_column' => 'hcp.organization_id',
        'branch_column' => 'hc.branch_id',
        'default_date_column' => 'hcp.created_at',
        'always_join' => ['checks'],
        'left_joins' => ['outlets', 'branches'],
        'joins' => [
            'checks' => ['hospitality_checks as hc', 'hc.id', '=', 'hcp.check_id'],
            'outlets' => ['hospitality_outlets as ho', 'ho.id', '=', 'hc.outlet_id'],
            'branches' => ['branches as b', 'b.id', '=', 'hc.branch_id'],
        ],
        'fields' => [
            'payment_day' => [
                'label' => 'Payment date',
                'expr' => 'DATE(hcp.created_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'method_code' => [
                'label' => 'Payment method',
                'expr' => 'hcp.method_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'outlet_name' => [
                'label' => 'Outlet',
                'expr' => 'ho.name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'outlets',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'amount' => [
                'label' => 'Amount',
                'expr' => 'hcp.amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max', 'count'],
            ],
            'payment_count' => [
                'label' => 'Payments',
                'expr' => 'hcp.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'hospitality_folios' => [
        'label' => 'Guest folios',
        'module' => 'Hospitality',
        'description' => 'In-house guest folio balances',
        'table' => 'hospitality_folios as hf',
        'org_column' => 'hf.organization_id',
        'branch_column' => 'hf.branch_id',
        'default_date_column' => 'hf.checked_in_at',
        'left_joins' => ['rooms', 'room_types', 'branches'],
        'joins' => [
            'rooms' => ['hospitality_rooms as hr', 'hr.id', '=', 'hf.room_id'],
            'room_types' => ['hospitality_room_types as hrt', 'hrt.id', '=', 'hr.room_type_id'],
            'branches' => ['branches as b', 'b.id', '=', 'hf.branch_id'],
        ],
        'fields' => [
            'check_in_day' => [
                'label' => 'Check-in date',
                'expr' => 'DATE(hf.checked_in_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'folio_number' => [
                'label' => 'Folio number',
                'expr' => 'hf.folio_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'guest_name' => [
                'label' => 'Guest name',
                'expr' => 'hf.guest_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'hf.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'room_number' => [
                'label' => 'Room',
                'expr' => 'hr.room_number',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'rooms',
            ],
            'room_type' => [
                'label' => 'Room type',
                'expr' => 'hrt.name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'room_types',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'balance' => [
                'label' => 'Balance',
                'expr' => 'hf.balance',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max'],
            ],
            'folio_count' => [
                'label' => 'Folios',
                'expr' => 'hf.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'hospitality_folio_charges' => [
        'label' => 'Folio charges',
        'module' => 'Hospitality',
        'description' => 'Charges posted to guest folios',
        'table' => 'hospitality_folio_charges as hfc',
        'org_column' => 'hfc.organization_id',
        'branch_column' => 'hf.branch_id',
        'default_date_column' => 'hfc.posted_at',
        'always_join' => ['folios'],
        'left_joins' => ['rooms', 'branches'],
        'joins' => [
            'folios' => ['hospitality_folios as hf', 'hf.id', '=', 'hfc.folio_id'],
            'rooms' => ['hospitality_rooms as hr', 'hr.id', '=', 'hf.room_id'],
            'branches' => ['branches as b', 'b.id', '=', 'hf.branch_id'],
        ],
        'fields' => [
            'posted_day' => [
                'label' => 'Posted date',
                'expr' => 'DATE(COALESCE(hfc.posted_at, hfc.created_at))',
                'type' => 'date',
                'groupable' => true,
            ],
            'charge_type' => [
                'label' => 'Charge type',
                'expr' => 'hfc.charge_type',
                'type' => 'string',
                'groupable' => true,
            ],
            'description' => [
                'label' => 'Description',
                'expr' => 'hfc.description',
                'type' => 'string',
                'groupable' => true,
            ],
            'guest_name' => [
                'label' => 'Guest name',
                'expr' => 'hf.guest_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'folios',
            ],
            'room_number' => [
                'label' => 'Room',
                'expr' => 'hr.room_number',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'rooms',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'amount' => [
                'label' => 'Amount',
                'expr' => 'hfc.amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max'],
            ],
            'charge_count' => [
                'label' => 'Charges',
                'expr' => 'hfc.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'hospitality_folio_payments' => [
        'label' => 'Folio payments',
        'module' => 'Hospitality',
        'description' => 'Payments against guest folios',
        'table' => 'hospitality_folio_payments as hfp',
        'org_column' => 'hfp.organization_id',
        'branch_column' => 'hf.branch_id',
        'default_date_column' => 'hfp.created_at',
        'always_join' => ['folios'],
        'left_joins' => ['branches'],
        'joins' => [
            'folios' => ['hospitality_folios as hf', 'hf.id', '=', 'hfp.folio_id'],
            'branches' => ['branches as b', 'b.id', '=', 'hf.branch_id'],
        ],
        'fields' => [
            'payment_day' => [
                'label' => 'Payment date',
                'expr' => 'DATE(hfp.created_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'method_code' => [
                'label' => 'Payment method',
                'expr' => 'hfp.method_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'guest_name' => [
                'label' => 'Guest name',
                'expr' => 'hf.guest_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'folios',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'amount' => [
                'label' => 'Amount',
                'expr' => 'hfp.amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max', 'count'],
            ],
            'payment_count' => [
                'label' => 'Payments',
                'expr' => 'hfp.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'hospitality_rooms' => [
        'label' => 'Rooms',
        'module' => 'Hospitality',
        'description' => 'Room inventory and status',
        'table' => 'hospitality_rooms as hr',
        'org_column' => 'hr.organization_id',
        'branch_column' => 'hr.branch_id',
        'default_date_column' => 'hr.updated_at',
        'left_joins' => ['room_types', 'branches'],
        'joins' => [
            'room_types' => ['hospitality_room_types as hrt', 'hrt.id', '=', 'hr.room_type_id'],
            'branches' => ['branches as b', 'b.id', '=', 'hr.branch_id'],
        ],
        'fields' => [
            'room_number' => [
                'label' => 'Room number',
                'expr' => 'hr.room_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'floor' => [
                'label' => 'Floor',
                'expr' => 'hr.floor',
                'type' => 'string',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'hr.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'room_type' => [
                'label' => 'Room type',
                'expr' => 'hrt.name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'room_types',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'hr.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'room_count' => [
                'label' => 'Rooms',
                'expr' => 'hr.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'hospitality_reservations' => [
        'label' => 'Reservations',
        'module' => 'Hospitality',
        'description' => 'Room reservations and arrivals',
        'table' => 'hospitality_reservations as hres',
        'org_column' => 'hres.organization_id',
        'branch_column' => 'hres.branch_id',
        'default_date_column' => 'hres.arrival_date',
        'left_joins' => ['rooms', 'room_types', 'branches'],
        'joins' => [
            'rooms' => ['hospitality_rooms as hr', 'hr.id', '=', 'hres.room_id'],
            'room_types' => ['hospitality_room_types as hrt', 'hrt.id', '=', 'hres.room_type_id'],
            'branches' => ['branches as b', 'b.id', '=', 'hres.branch_id'],
        ],
        'fields' => [
            'arrival_date' => [
                'label' => 'Arrival date',
                'expr' => 'hres.arrival_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'departure_date' => [
                'label' => 'Departure date',
                'expr' => 'hres.departure_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'confirmation_code' => [
                'label' => 'Confirmation',
                'expr' => 'hres.confirmation_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'guest_name' => [
                'label' => 'Guest name',
                'expr' => 'hres.guest_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'hres.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'room_number' => [
                'label' => 'Room',
                'expr' => 'hr.room_number',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'rooms',
            ],
            'room_type' => [
                'label' => 'Room type',
                'expr' => 'hrt.name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'room_types',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'deposit_amount' => [
                'label' => 'Deposit',
                'expr' => 'hres.deposit_amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max'],
            ],
            'reservation_count' => [
                'label' => 'Reservations',
                'expr' => 'hres.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'hospitality_outlets' => [
        'label' => 'Outlets',
        'module' => 'Hospitality',
        'description' => 'Bars, restaurants, and other outlets',
        'table' => 'hospitality_outlets as ho',
        'org_column' => 'ho.organization_id',
        'branch_column' => 'ho.branch_id',
        'default_date_column' => 'ho.created_at',
        'left_joins' => ['branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'ho.branch_id'],
        ],
        'fields' => [
            'code' => [
                'label' => 'Outlet code',
                'expr' => 'ho.code',
                'type' => 'string',
                'groupable' => true,
            ],
            'name' => [
                'label' => 'Outlet name',
                'expr' => 'ho.name',
                'type' => 'string',
                'groupable' => true,
            ],
            'outlet_type' => [
                'label' => 'Outlet type',
                'expr' => 'ho.outlet_type',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'ho.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'outlet_count' => [
                'label' => 'Outlets',
                'expr' => 'ho.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],
];
