<?php

/**
 * Additional organization-scoped report builder data sources.
 * Merged into config/report_builder.php — one source per major API module/table.
 */
return [
    'sales_pipeline' => [
        'label' => 'Sales pipeline',
        'module' => 'Sales',
        'description' => 'All sales orders including open, pending, and completed',
        'table' => 'sales as s',
        'org_column' => 's.organization_id',
        'branch_column' => 's.branch_id',
        'default_date_column' => 's.created_at',
        'base_where' => [
            ['s.archived', '=', 0],
            ['s.deleted_at', '=', null],
        ],
        'left_joins' => ['customers', 'routes', 'branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 's.branch_id'],
            'customers' => ['customers as c', 'c.customer_num', '=', 's.customer_num'],
            'routes' => ['routes as r', 'r.id', '=', 's.route_id'],
        ],
        'fields' => [
            'order_day' => [
                'label' => 'Order date',
                'expr' => 'DATE(s.created_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 's.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'channel' => [
                'label' => 'Channel',
                'expr' => 's.channel',
                'type' => 'string',
                'groupable' => true,
            ],
            'route_name' => [
                'label' => 'Route',
                'expr' => 'r.route_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'routes',
            ],
            'payment_status' => [
                'label' => 'Payment status',
                'expr' => 's.payment_status',
                'type' => 'string',
                'groupable' => true,
            ],
            'order_total' => [
                'label' => 'Order total',
                'expr' => 's.order_total',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
            ],
            'order_count' => [
                'label' => 'Orders',
                'expr' => 's.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'invoice_payments' => [
        'label' => 'Invoice payments',
        'module' => 'Sales',
        'description' => 'Customer payments against invoices',
        'table' => 'customer_invoice_payments as cip',
        'org_column' => 'cip.organization_id',
        'branch_column' => 'ci.branch_id',
        'default_date_column' => 'cip.date_paid',
        'always_join' => ['invoices'],
        'joins' => [
            'invoices' => ['customer_invoices as ci', 'ci.id', '=', 'cip.customer_invoice_id'],
            'customers' => ['customers as c', 'c.customer_num', '=', 'cip.customer_num'],
            'payment_methods' => ['payment_methods as pm', 'pm.id', '=', 'cip.payment_method_id'],
            'branches' => ['branches as b', 'b.id', '=', 'ci.branch_id'],
        ],
        'left_joins' => ['customers', 'payment_methods', 'branches'],
        'fields' => [
            'payment_date' => [
                'label' => 'Payment date',
                'expr' => 'cip.date_paid',
                'type' => 'date',
                'groupable' => true,
            ],
            'customer_name' => [
                'label' => 'Customer',
                'expr' => 'c.customer_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'customers',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'payment_method' => [
                'label' => 'Payment method',
                'expr' => 'pm.method_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'payment_methods',
            ],
            'amount_paid' => [
                'label' => 'Amount paid',
                'expr' => 'cip.amount_paid',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
            ],
            'payment_count' => [
                'label' => 'Payments',
                'expr' => 'cip.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'customer_returns' => [
        'label' => 'Customer returns (workflow)',
        'module' => 'Sales',
        'description' => 'Return documents with approval workflow',
        'table' => 'customer_returns as cr',
        'org_column' => 'cr.organization_id',
        'branch_column' => 'cr.branch_id',
        'default_date_column' => 'cr.return_date',
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'cr.branch_id'],
            'customers' => ['customers as c', 'c.customer_num', '=', 'cr.customer_num'],
        ],
        'left_joins' => ['customers', 'branches'],
        'fields' => [
            'return_date' => [
                'label' => 'Return date',
                'expr' => 'cr.return_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'return_no' => [
                'label' => 'Return #',
                'expr' => 'cr.return_no',
                'type' => 'string',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'cr.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'refund_method' => [
                'label' => 'Refund method',
                'expr' => 'cr.refund_method',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'customer_name' => [
                'label' => 'Customer',
                'expr' => 'c.customer_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'customers',
            ],
            'total_amount' => [
                'label' => 'Total amount',
                'expr' => 'cr.total_amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
            ],
            'return_count' => [
                'label' => 'Returns',
                'expr' => 'cr.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'customer_return_lines' => [
        'label' => 'Customer return lines',
        'module' => 'Sales',
        'description' => 'Line items on customer return documents',
        'table' => 'customer_return_lines as crl',
        'org_column' => 'cr.organization_id',
        'branch_column' => 'cr.branch_id',
        'default_date_column' => 'cr.return_date',
        'always_join' => ['returns'],
        'joins' => [
            'returns' => ['customer_returns as cr', 'cr.id', '=', 'crl.customer_return_id'],
            'products' => ['products as p', 'p.product_code', '=', 'crl.product_code'],
            'branches' => ['branches as b', 'b.id', '=', 'cr.branch_id'],
        ],
        'left_joins' => ['products', 'branches'],
        'fields' => [
            'return_date' => [
                'label' => 'Return date',
                'expr' => 'cr.return_date',
                'type' => 'date',
                'groupable' => true,
                'requires_join' => 'returns',
            ],
            'product_code' => [
                'label' => 'Product code',
                'expr' => 'crl.product_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'product_name' => [
                'label' => 'Product name',
                'expr' => 'COALESCE(crl.product_name, p.product_name)',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'products',
            ],
            'return_qty' => [
                'label' => 'Return qty',
                'expr' => 'crl.return_qty',
                'type' => 'number',
                'aggregates' => ['sum', 'avg', 'count'],
            ],
            'amount' => [
                'label' => 'Amount',
                'expr' => 'crl.amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'line_count' => [
                'label' => 'Lines',
                'expr' => 'crl.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'credit_notes' => [
        'label' => 'Credit notes',
        'module' => 'Sales',
        'description' => 'Credit notes issued for returns',
        'table' => 'credit_notes as cn',
        'org_column' => 'cn.organization_id',
        'branch_column' => 'cn.branch_id',
        'default_date_column' => 'cn.credit_date',
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'cn.branch_id'],
            'customers' => ['customers as c', 'c.customer_num', '=', 'cn.customer_num'],
        ],
        'left_joins' => ['customers', 'branches'],
        'fields' => [
            'credit_date' => [
                'label' => 'Credit date',
                'expr' => 'cn.credit_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'credit_note_no' => [
                'label' => 'Credit note #',
                'expr' => 'cn.credit_note_no',
                'type' => 'string',
                'groupable' => true,
            ],
            'kra_status' => [
                'label' => 'KRA status',
                'expr' => 'cn.kra_status',
                'type' => 'string',
                'groupable' => true,
            ],
            'refund_method' => [
                'label' => 'Refund method',
                'expr' => 'cn.refund_method',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'total_amount' => [
                'label' => 'Total amount',
                'expr' => 'cn.total_amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
            ],
            'credit_count' => [
                'label' => 'Credit notes',
                'expr' => 'cn.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'vouchers' => [
        'label' => 'Vouchers',
        'module' => 'Sales',
        'description' => 'Discount and payment vouchers',
        'table' => 'vouchers as v',
        'org_column' => 'v.organization_id',
        'branch_column' => null,
        'default_date_column' => 'v.created_at',
        'fields' => [
            'voucher_code' => [
                'label' => 'Voucher code',
                'expr' => 'v.voucher_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'voucher_kind' => [
                'label' => 'Kind',
                'expr' => 'v.voucher_kind',
                'type' => 'string',
                'groupable' => true,
            ],
            'discount_type' => [
                'label' => 'Discount type',
                'expr' => 'v.discount_type',
                'type' => 'string',
                'groupable' => true,
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'v.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'balance' => [
                'label' => 'Balance',
                'expr' => 'v.balance',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max'],
            ],
            'redemption_count' => [
                'label' => 'Redemptions',
                'expr' => 'v.redemption_count',
                'type' => 'number',
                'aggregates' => ['sum', 'avg', 'max'],
            ],
            'voucher_count' => [
                'label' => 'Vouchers',
                'expr' => 'v.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'loyalty_cards' => [
        'label' => 'Loyalty cards',
        'module' => 'Sales',
        'description' => 'Customer loyalty cards and points',
        'table' => 'loyalty_cards as lc',
        'org_column' => 'lc.organization_id',
        'branch_column' => null,
        'default_date_column' => 'lc.created_at',
        'joins' => [
            'customers' => ['customers as c', 'c.customer_num', '=', 'lc.customer_num'],
        ],
        'left_joins' => ['customers'],
        'fields' => [
            'card_number' => [
                'label' => 'Card number',
                'expr' => 'lc.card_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'customer_name' => [
                'label' => 'Customer',
                'expr' => 'c.customer_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'customers',
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'lc.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'points_balance' => [
                'label' => 'Points balance',
                'expr' => 'lc.points_balance',
                'type' => 'number',
                'aggregates' => ['sum', 'avg', 'max'],
            ],
            'card_count' => [
                'label' => 'Cards',
                'expr' => 'lc.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'kra_receipts' => [
        'label' => 'KRA receipts',
        'module' => 'Sales',
        'description' => 'KRA fiscalisation responses for sales',
        'table' => 'kra_responses as kr',
        'org_column' => 's.organization_id',
        'branch_column' => 's.branch_id',
        'default_date_column' => 'kr.created_at',
        'always_join' => ['sales'],
        'joins' => [
            'sales' => ['sales as s', 's.id', '=', 'kr.sale_id'],
            'branches' => ['branches as b', 'b.id', '=', 's.branch_id'],
        ],
        'left_joins' => ['branches'],
        'fields' => [
            'receipt_day' => [
                'label' => 'Date',
                'expr' => 'DATE(kr.created_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'kr.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'invoice_number' => [
                'label' => 'Invoice #',
                'expr' => 'kr.invoice_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'receipt_count' => [
                'label' => 'Receipts',
                'expr' => 'kr.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'till_sessions' => [
        'label' => 'Till sessions',
        'module' => 'POS',
        'description' => 'Cashier float sessions and reconciliation',
        'table' => 'till_float_sessions as tfs',
        'org_column' => 'b.organization_id',
        'branch_column' => 'tfs.branch_id',
        'default_date_column' => 'tfs.session_date',
        'always_join' => ['branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'tfs.branch_id'],
            'tills' => ['tills as t', 't.id', '=', 'tfs.till_id'],
            'cashiers' => ['users as u', 'u.id', '=', 'tfs.cashier_id'],
        ],
        'left_joins' => ['tills', 'cashiers'],
        'fields' => [
            'session_date' => [
                'label' => 'Session date',
                'expr' => 'tfs.session_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'tfs.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'till_name' => [
                'label' => 'Till',
                'expr' => 't.till_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'tills',
            ],
            'cashier' => [
                'label' => 'Cashier',
                'expr' => 'u.username',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'cashiers',
            ],
            'working_amount' => [
                'label' => 'Opening float',
                'expr' => 'tfs.working_amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'cash_sales' => [
                'label' => 'Cash sales',
                'expr' => 'tfs.cash_sales',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'closing_amount' => [
                'label' => 'Closing amount',
                'expr' => 'tfs.closing_amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'session_count' => [
                'label' => 'Sessions',
                'expr' => 'tfs.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'tills' => [
        'label' => 'Tills',
        'module' => 'POS',
        'description' => 'Point-of-sale till registers',
        'table' => 'tills as t',
        'org_column' => 'b.organization_id',
        'branch_column' => 't.branch_id',
        'default_date_column' => 't.created_at',
        'always_join' => ['branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 't.branch_id'],
        ],
        'fields' => [
            'till_number' => [
                'label' => 'Till number',
                'expr' => 't.till_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'till_name' => [
                'label' => 'Till name',
                'expr' => 't.till_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 't.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'till_count' => [
                'label' => 'Tills',
                'expr' => 't.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'supplier_payments' => [
        'label' => 'Supplier payments',
        'module' => 'Purchasing',
        'description' => 'Payments made to suppliers',
        'table' => 'supplier_payments as sp',
        'org_column' => 'sp.organization_id',
        'branch_column' => null,
        'default_date_column' => 'sp.date_paid',
        'joins' => [
            'suppliers' => ['suppliers as sup', 'sup.id', '=', 'sp.supplier_id'],
            'payment_methods' => ['payment_methods as pm', 'pm.id', '=', 'sp.payment_method_id'],
        ],
        'left_joins' => ['payment_methods'],
        'fields' => [
            'payment_date' => [
                'label' => 'Payment date',
                'expr' => 'sp.date_paid',
                'type' => 'date',
                'groupable' => true,
            ],
            'supplier_name' => [
                'label' => 'Supplier',
                'expr' => 'sup.supplier_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'suppliers',
            ],
            'payment_method' => [
                'label' => 'Payment method',
                'expr' => 'pm.method_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'payment_methods',
            ],
            'amount_paid' => [
                'label' => 'Amount paid',
                'expr' => 'sp.amount_paid',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
            ],
            'payment_count' => [
                'label' => 'Payments',
                'expr' => 'sp.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'supplier_return_lines' => [
        'label' => 'Supplier return lines',
        'module' => 'Purchasing',
        'description' => 'Line items on supplier return documents',
        'table' => 'supplier_return_document_lines as srdl',
        'org_column' => 'srd.organization_id',
        'branch_column' => 'srd.branch_id',
        'default_date_column' => 'srd.created_at',
        'always_join' => ['documents'],
        'joins' => [
            'documents' => ['supplier_return_documents as srd', 'srd.id', '=', 'srdl.document_id'],
            'suppliers' => ['suppliers as sup', 'sup.id', '=', 'srd.supplier_id'],
            'branches' => ['branches as b', 'b.id', '=', 'srd.branch_id'],
        ],
        'left_joins' => ['suppliers', 'branches'],
        'fields' => [
            'return_day' => [
                'label' => 'Return date',
                'expr' => 'DATE(srd.created_at)',
                'type' => 'date',
                'groupable' => true,
                'requires_join' => 'documents',
            ],
            'supplier_name' => [
                'label' => 'Supplier',
                'expr' => 'sup.supplier_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'suppliers',
            ],
            'product_code' => [
                'label' => 'Product code',
                'expr' => 'srdl.product_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'quantity' => [
                'label' => 'Quantity',
                'expr' => 'srdl.quantity',
                'type' => 'number',
                'aggregates' => ['sum', 'avg', 'count'],
            ],
            'line_count' => [
                'label' => 'Lines',
                'expr' => 'srdl.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'lpo_supplier_invoices' => [
        'label' => 'LPO supplier invoices',
        'module' => 'Purchasing',
        'description' => 'Supplier invoices linked to LPOs',
        'table' => 'lpo_supplier_invoices as lsi',
        'org_column' => 'sup.organization_id',
        'branch_column' => null,
        'default_date_column' => 'lsi.invoice_date',
        'always_join' => ['suppliers', 'lpo'],
        'joins' => [
            'suppliers' => ['suppliers as sup', 'sup.id', '=', 'lsi.supplier_id'],
            'lpo' => ['lpo_mst as lpo', 'lpo.lpo_no', '=', 'lsi.lpo_no'],
        ],
        'fields' => [
            'invoice_date' => [
                'label' => 'Invoice date',
                'expr' => 'lsi.invoice_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'supplier_name' => [
                'label' => 'Supplier',
                'expr' => 'sup.supplier_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'suppliers',
            ],
            'supplier_invoice_number' => [
                'label' => 'Supplier invoice #',
                'expr' => 'lsi.supplier_invoice_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'invoice_amount' => [
                'label' => 'Invoice amount',
                'expr' => 'lsi.invoice_amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
            ],
            'invoice_count' => [
                'label' => 'Invoices',
                'expr' => 'lsi.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'stock_reservations' => [
        'label' => 'Stock reservations',
        'module' => 'Inventory',
        'description' => 'Stock reserved for carts and sales',
        'table' => 'stock_reservations as sr',
        'org_column' => 'b.organization_id',
        'branch_column' => 'sr.branch_id',
        'default_date_column' => 'sr.created_at',
        'always_join' => ['branches'],
        'base_where' => [
            ['sr.released_at', '=', null],
        ],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'sr.branch_id'],
            'products' => ['products as p', 'p.product_code', '=', 'sr.product_code'],
        ],
        'left_joins' => ['products'],
        'fields' => [
            'reservation_day' => [
                'label' => 'Date',
                'expr' => 'DATE(sr.created_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'product_code' => [
                'label' => 'Product code',
                'expr' => 'sr.product_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'stock_location' => [
                'label' => 'Location',
                'expr' => 'sr.stock_location',
                'type' => 'string',
                'groupable' => true,
            ],
            'quantity' => [
                'label' => 'Quantity',
                'expr' => 'sr.quantity',
                'type' => 'number',
                'aggregates' => ['sum', 'avg', 'count'],
            ],
            'reservation_count' => [
                'label' => 'Reservations',
                'expr' => 'sr.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'stock_take_sessions' => [
        'label' => 'Stock take sessions',
        'module' => 'Inventory',
        'description' => 'Physical stock count sessions',
        'table' => 'stock_take_sessions as sts',
        'org_column' => 'b.organization_id',
        'branch_column' => 'sts.branch_id',
        'default_date_column' => 'sts.started_at',
        'always_join' => ['branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'sts.branch_id'],
        ],
        'fields' => [
            'session_day' => [
                'label' => 'Date',
                'expr' => 'DATE(sts.started_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'session_code' => [
                'label' => 'Session code',
                'expr' => 'sts.session_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'sts.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'stock_location' => [
                'label' => 'Location',
                'expr' => 'sts.stock_location',
                'type' => 'string',
                'groupable' => true,
            ],
            'session_count' => [
                'label' => 'Sessions',
                'expr' => 'sts.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'stock_take_lines' => [
        'label' => 'Stock take lines',
        'module' => 'Inventory',
        'description' => 'Counted quantities and variances',
        'table' => 'stock_take_lines as stl',
        'org_column' => 'b.organization_id',
        'branch_column' => 'sts.branch_id',
        'default_date_column' => 'sts.started_at',
        'always_join' => ['sessions', 'branches'],
        'joins' => [
            'sessions' => ['stock_take_sessions as sts', 'sts.id', '=', 'stl.session_id'],
            'branches' => ['branches as b', 'b.id', '=', 'sts.branch_id'],
            'products' => ['products as p', 'p.product_code', '=', 'stl.product_code'],
        ],
        'left_joins' => ['products'],
        'fields' => [
            'session_day' => [
                'label' => 'Date',
                'expr' => 'DATE(sts.started_at)',
                'type' => 'date',
                'groupable' => true,
                'requires_join' => 'sessions',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'product_code' => [
                'label' => 'Product code',
                'expr' => 'stl.product_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'system_quantity' => [
                'label' => 'System qty',
                'expr' => 'stl.system_quantity',
                'type' => 'number',
                'aggregates' => ['sum', 'avg'],
            ],
            'counted_quantity' => [
                'label' => 'Counted qty',
                'expr' => 'stl.counted_quantity',
                'type' => 'number',
                'aggregates' => ['sum', 'avg'],
            ],
            'variance' => [
                'label' => 'Variance',
                'expr' => 'stl.variance',
                'type' => 'number',
                'aggregates' => ['sum', 'avg'],
            ],
            'line_count' => [
                'label' => 'Lines',
                'expr' => 'stl.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'price_history' => [
        'label' => 'Price history',
        'module' => 'Inventory',
        'description' => 'Product price change audit trail',
        'table' => 'price_history as ph',
        'org_column' => 'ph.organization_id',
        'branch_column' => null,
        'default_date_column' => 'ph.changed_at',
        'joins' => [
            'products' => ['products as p', 'p.product_code', '=', 'ph.product_code'],
        ],
        'left_joins' => ['products'],
        'fields' => [
            'change_day' => [
                'label' => 'Change date',
                'expr' => 'DATE(ph.changed_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'product_code' => [
                'label' => 'Product code',
                'expr' => 'ph.product_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'product_name' => [
                'label' => 'Product name',
                'expr' => 'p.product_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'products',
            ],
            'unit_price' => [
                'label' => 'Unit price',
                'expr' => 'ph.unit_price',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max'],
            ],
            'cost_price' => [
                'label' => 'Cost price',
                'expr' => 'ph.cost_price',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'min', 'max'],
            ],
            'change_count' => [
                'label' => 'Changes',
                'expr' => 'ph.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'dispatch_trips' => [
        'label' => 'Dispatch trips',
        'module' => 'Logistics',
        'description' => 'Delivery trips and cash settlement',
        'table' => 'dispatch_trips as dt',
        'org_column' => 'b.organization_id',
        'branch_column' => 'dt.branch_id',
        'default_date_column' => 'dt.scheduled_date',
        'always_join' => ['branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'dt.branch_id'],
            'routes' => ['routes as r', 'r.id', '=', 'dt.route_id'],
            'drivers' => ['drivers as dr', 'dr.id', '=', 'dt.driver_id'],
            'vehicles' => ['vehicles as vh', 'vh.id', '=', 'dt.vehicle_id'],
        ],
        'left_joins' => ['routes', 'drivers', 'vehicles'],
        'fields' => [
            'scheduled_date' => [
                'label' => 'Scheduled date',
                'expr' => 'dt.scheduled_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'trip_code' => [
                'label' => 'Trip code',
                'expr' => 'dt.trip_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'dt.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'route_name' => [
                'label' => 'Route',
                'expr' => 'r.route_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'routes',
            ],
            'driver_name' => [
                'label' => 'Driver',
                'expr' => 'dr.full_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'drivers',
            ],
            'expected_cash' => [
                'label' => 'Expected cash',
                'expr' => 'dt.expected_cash',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'collected_cash' => [
                'label' => 'Collected cash',
                'expr' => 'dt.collected_cash',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'cash_variance' => [
                'label' => 'Cash variance',
                'expr' => 'dt.cash_variance',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'trip_count' => [
                'label' => 'Trips',
                'expr' => 'dt.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'loading_list_lines' => [
        'label' => 'Loading list lines',
        'module' => 'Logistics',
        'description' => 'Products loaded for dispatch trips',
        'table' => 'loading_list_lines as lll',
        'org_column' => 'b.organization_id',
        'branch_column' => 'll.branch_id',
        'default_date_column' => 'll.list_date',
        'always_join' => ['loading_lists', 'branches'],
        'joins' => [
            'loading_lists' => ['loading_lists as ll', 'll.id', '=', 'lll.loading_list_id'],
            'branches' => ['branches as b', 'b.id', '=', 'll.branch_id'],
            'trips' => ['dispatch_trips as dt', 'dt.id', '=', 'll.trip_id'],
        ],
        'left_joins' => ['trips'],
        'fields' => [
            'list_date' => [
                'label' => 'List date',
                'expr' => 'll.list_date',
                'type' => 'date',
                'groupable' => true,
                'requires_join' => 'loading_lists',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'product_code' => [
                'label' => 'Product code',
                'expr' => 'lll.product_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'quantity' => [
                'label' => 'Quantity',
                'expr' => 'lll.quantity',
                'type' => 'number',
                'aggregates' => ['sum', 'avg', 'count'],
            ],
            'line_total' => [
                'label' => 'Line total',
                'expr' => 'lll.line_total',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'line_count' => [
                'label' => 'Lines',
                'expr' => 'lll.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'pod_records' => [
        'label' => 'Proof of delivery',
        'module' => 'Logistics',
        'description' => 'Delivery confirmation records',
        'table' => 'pod_records as pod',
        'org_column' => 'b.organization_id',
        'branch_column' => 'pod.branch_id',
        'default_date_column' => 'pod.captured_at',
        'always_join' => ['branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'pod.branch_id'],
            'sales' => ['sales as s', 's.id', '=', 'pod.sale_id'],
        ],
        'left_joins' => ['sales'],
        'fields' => [
            'captured_day' => [
                'label' => 'Date',
                'expr' => 'DATE(pod.captured_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'pod.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'recipient_name' => [
                'label' => 'Recipient',
                'expr' => 'pod.recipient_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'pod_count' => [
                'label' => 'POD records',
                'expr' => 'pod.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'pod_lines' => [
        'label' => 'POD line items',
        'module' => 'Logistics',
        'description' => 'Delivered vs refused quantities per POD',
        'table' => 'pod_lines as pl',
        'org_column' => 'b.organization_id',
        'branch_column' => 'pod.branch_id',
        'default_date_column' => 'pod.captured_at',
        'always_join' => ['pod_records', 'branches'],
        'joins' => [
            'pod_records' => ['pod_records as pod', 'pod.id', '=', 'pl.pod_record_id'],
            'branches' => ['branches as b', 'b.id', '=', 'pod.branch_id'],
        ],
        'fields' => [
            'captured_day' => [
                'label' => 'Date',
                'expr' => 'DATE(pod.captured_at)',
                'type' => 'date',
                'groupable' => true,
                'requires_join' => 'pod_records',
            ],
            'qty_ordered' => [
                'label' => 'Qty ordered',
                'expr' => 'pl.qty_ordered',
                'type' => 'number',
                'aggregates' => ['sum', 'avg'],
            ],
            'qty_delivered' => [
                'label' => 'Qty delivered',
                'expr' => 'pl.qty_delivered',
                'type' => 'number',
                'aggregates' => ['sum', 'avg'],
            ],
            'qty_refused' => [
                'label' => 'Qty refused',
                'expr' => 'pl.qty_refused',
                'type' => 'number',
                'aggregates' => ['sum', 'avg'],
            ],
            'line_count' => [
                'label' => 'Lines',
                'expr' => 'pl.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'vehicles' => [
        'label' => 'Vehicles',
        'module' => 'Logistics',
        'description' => 'Fleet vehicles',
        'table' => 'vehicles as vh',
        'org_column' => 'b.organization_id',
        'branch_column' => 'vh.branch_id',
        'default_date_column' => 'vh.created_at',
        'always_join' => ['branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'vh.branch_id'],
        ],
        'fields' => [
            'vehicle_code' => [
                'label' => 'Vehicle code',
                'expr' => 'vh.vehicle_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'vehicle_name' => [
                'label' => 'Vehicle name',
                'expr' => 'vh.vehicle_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'plate_number' => [
                'label' => 'Plate number',
                'expr' => 'vh.plate_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'vh.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'vehicle_count' => [
                'label' => 'Vehicles',
                'expr' => 'vh.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'drivers' => [
        'label' => 'Drivers',
        'module' => 'Logistics',
        'description' => 'Delivery drivers',
        'table' => 'drivers as dr',
        'org_column' => 'b.organization_id',
        'branch_column' => 'dr.branch_id',
        'default_date_column' => 'dr.created_at',
        'always_join' => ['branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'dr.branch_id'],
            'routes' => ['routes as r', 'r.id', '=', 'dr.default_route_id'],
        ],
        'left_joins' => ['routes'],
        'fields' => [
            'driver_code' => [
                'label' => 'Driver code',
                'expr' => 'dr.driver_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'full_name' => [
                'label' => 'Name',
                'expr' => 'dr.full_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'default_route' => [
                'label' => 'Default route',
                'expr' => 'r.route_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'routes',
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'dr.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'driver_count' => [
                'label' => 'Drivers',
                'expr' => 'dr.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'route_schedules' => [
        'label' => 'Route schedules',
        'module' => 'Logistics',
        'description' => 'Weekly route departure schedules',
        'table' => 'route_schedules as rs',
        'org_column' => 'b.organization_id',
        'branch_column' => 'rs.branch_id',
        'default_date_column' => 'rs.created_at',
        'always_join' => ['branches'],
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'rs.branch_id'],
            'routes' => ['routes as r', 'r.id', '=', 'rs.route_id'],
            'drivers' => ['drivers as dr', 'dr.id', '=', 'rs.default_driver_id'],
        ],
        'left_joins' => ['routes', 'drivers'],
        'fields' => [
            'day_of_week' => [
                'label' => 'Day of week',
                'expr' => 'rs.day_of_week',
                'type' => 'number',
                'groupable' => true,
            ],
            'route_name' => [
                'label' => 'Route',
                'expr' => 'r.route_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'routes',
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'driver_name' => [
                'label' => 'Driver',
                'expr' => 'dr.full_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'drivers',
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'rs.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'schedule_count' => [
                'label' => 'Schedules',
                'expr' => 'rs.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'pay_periods' => [
        'label' => 'Pay periods',
        'module' => 'HR',
        'description' => 'Payroll period calendar',
        'table' => 'pay_periods as pp',
        'org_column' => 'pp.organization_id',
        'branch_column' => null,
        'default_date_column' => 'pp.period_start',
        'fields' => [
            'period_code' => [
                'label' => 'Period code',
                'expr' => 'pp.period_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'period_start' => [
                'label' => 'Period start',
                'expr' => 'pp.period_start',
                'type' => 'date',
                'groupable' => true,
            ],
            'period_end' => [
                'label' => 'Period end',
                'expr' => 'pp.period_end',
                'type' => 'date',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'pp.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'period_count' => [
                'label' => 'Periods',
                'expr' => 'pp.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'payroll_runs' => [
        'label' => 'Payroll runs',
        'module' => 'HR',
        'description' => 'Payroll run headers and totals',
        'table' => 'payroll_runs as pr',
        'org_column' => 'pp.organization_id',
        'branch_column' => null,
        'default_date_column' => 'pr.run_date',
        'always_join' => ['pay_periods'],
        'joins' => [
            'pay_periods' => ['pay_periods as pp', 'pp.id', '=', 'pr.pay_period_id'],
        ],
        'fields' => [
            'run_date' => [
                'label' => 'Run date',
                'expr' => 'pr.run_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'pr.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'period_code' => [
                'label' => 'Pay period',
                'expr' => 'pp.period_code',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'pay_periods',
            ],
            'total_gross' => [
                'label' => 'Total gross',
                'expr' => 'pr.total_gross',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count'],
            ],
            'total_net' => [
                'label' => 'Total net',
                'expr' => 'pr.total_net',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'run_count' => [
                'label' => 'Runs',
                'expr' => 'pr.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'employee_overtime' => [
        'label' => 'Employee overtime',
        'module' => 'HR',
        'description' => 'Overtime hours and amounts',
        'table' => 'employee_overtime as eo',
        'org_column' => 'eo.organization_id',
        'branch_column' => null,
        'default_date_column' => 'eo.work_date',
        'joins' => [
            'employees' => ['employees as emp', 'emp.id', '=', 'eo.employee_id'],
        ],
        'left_joins' => ['employees'],
        'fields' => [
            'work_date' => [
                'label' => 'Work date',
                'expr' => 'eo.work_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'employee_name' => [
                'label' => 'Employee',
                'expr' => 'emp.full_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'employees',
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'eo.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'hours' => [
                'label' => 'Hours',
                'expr' => 'eo.hours',
                'type' => 'number',
                'aggregates' => ['sum', 'avg', 'count'],
            ],
            'amount' => [
                'label' => 'Amount',
                'expr' => 'eo.amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg'],
            ],
            'overtime_count' => [
                'label' => 'Records',
                'expr' => 'eo.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'cash_advances' => [
        'label' => 'Cash advances',
        'module' => 'HR',
        'description' => 'Employee cash advance loans',
        'table' => 'employee_cash_advances as eca',
        'org_column' => 'eca.organization_id',
        'branch_column' => null,
        'default_date_column' => 'eca.advance_date',
        'joins' => [
            'employees' => ['employees as emp', 'emp.id', '=', 'eca.employee_id'],
        ],
        'left_joins' => ['employees'],
        'fields' => [
            'advance_date' => [
                'label' => 'Advance date',
                'expr' => 'eca.advance_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'employee_name' => [
                'label' => 'Employee',
                'expr' => 'emp.full_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'employees',
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'eca.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'amount' => [
                'label' => 'Amount',
                'expr' => 'eca.amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
            ],
            'balance' => [
                'label' => 'Balance',
                'expr' => 'eca.balance',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'max'],
            ],
            'advance_count' => [
                'label' => 'Advances',
                'expr' => 'eca.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'departments' => [
        'label' => 'Departments',
        'module' => 'HR',
        'description' => 'HR departments',
        'table' => 'departments as dept',
        'org_column' => 'dept.organization_id',
        'branch_column' => null,
        'default_date_column' => null,
        'fields' => [
            'department_code' => [
                'label' => 'Department code',
                'expr' => 'dept.department_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'department_name' => [
                'label' => 'Department name',
                'expr' => 'dept.department_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'dept.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'department_count' => [
                'label' => 'Departments',
                'expr' => 'dept.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'positions' => [
        'label' => 'Positions',
        'module' => 'HR',
        'description' => 'Job positions',
        'table' => 'positions as pos',
        'org_column' => 'pos.organization_id',
        'branch_column' => null,
        'default_date_column' => 'pos.created_at',
        'fields' => [
            'position_code' => [
                'label' => 'Position code',
                'expr' => 'pos.position_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'position_title' => [
                'label' => 'Position title',
                'expr' => 'pos.position_title',
                'type' => 'string',
                'groupable' => true,
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'pos.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'position_count' => [
                'label' => 'Positions',
                'expr' => 'pos.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'fiscal_periods' => [
        'label' => 'Fiscal periods',
        'module' => 'Accounting',
        'description' => 'Accounting fiscal periods',
        'table' => 'fiscal_periods as fp',
        'org_column' => 'fp.organization_id',
        'branch_column' => null,
        'default_date_column' => 'fp.start_date',
        'fields' => [
            'period_name' => [
                'label' => 'Period name',
                'expr' => 'fp.period_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'start_date' => [
                'label' => 'Start date',
                'expr' => 'fp.start_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'end_date' => [
                'label' => 'End date',
                'expr' => 'fp.end_date',
                'type' => 'date',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'fp.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'period_count' => [
                'label' => 'Periods',
                'expr' => 'fp.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'mpesa_stk' => [
        'label' => 'M-Pesa STK requests',
        'module' => 'Payments',
        'description' => 'M-Pesa STK push payment requests',
        'table' => 'mpesa_stk_requests as msr',
        'org_column' => 'msr.organization_id',
        'branch_column' => null,
        'default_date_column' => 'msr.created_at',
        'fields' => [
            'request_day' => [
                'label' => 'Date',
                'expr' => 'DATE(msr.created_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'msr.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'phone_number' => [
                'label' => 'Phone',
                'expr' => 'msr.phone_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'amount' => [
                'label' => 'Amount',
                'expr' => 'msr.amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
            ],
            'request_count' => [
                'label' => 'Requests',
                'expr' => 'msr.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'mpesa_incoming' => [
        'label' => 'M-Pesa incoming payments',
        'module' => 'Payments',
        'description' => 'Incoming M-Pesa C2B payments',
        'table' => 'mpesa_incoming_payments as mip',
        'org_column' => 'mip.organization_id',
        'branch_column' => null,
        'default_date_column' => 'mip.received_at',
        'fields' => [
            'received_day' => [
                'label' => 'Date',
                'expr' => 'DATE(mip.received_at)',
                'type' => 'date',
                'groupable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'expr' => 'mip.status',
                'type' => 'string',
                'groupable' => true,
            ],
            'source' => [
                'label' => 'Source',
                'expr' => 'mip.source',
                'type' => 'string',
                'groupable' => true,
            ],
            'phone_number' => [
                'label' => 'Phone',
                'expr' => 'mip.phone_number',
                'type' => 'string',
                'groupable' => true,
            ],
            'amount' => [
                'label' => 'Amount',
                'expr' => 'mip.amount',
                'type' => 'money',
                'aggregates' => ['sum', 'avg', 'count', 'min', 'max'],
            ],
            'payment_count' => [
                'label' => 'Payments',
                'expr' => 'mip.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'branches' => [
        'label' => 'Branches',
        'module' => 'Administration',
        'description' => 'Organization branches',
        'table' => 'branches as b',
        'org_column' => 'b.organization_id',
        'branch_column' => 'b.id',
        'default_date_column' => 'b.created_at',
        'fields' => [
            'branch_code' => [
                'label' => 'Branch code',
                'expr' => 'b.branch_code',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch name',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_type' => [
                'label' => 'Branch type',
                'expr' => 'b.branch_type',
                'type' => 'string',
                'groupable' => true,
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'b.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_count' => [
                'label' => 'Branches',
                'expr' => 'b.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],

    'users' => [
        'label' => 'Users',
        'module' => 'Administration',
        'description' => 'System users and cashiers',
        'table' => 'users as u',
        'org_column' => 'u.organization_id',
        'branch_column' => 'u.branch_id',
        'default_date_column' => 'u.created_at',
        'joins' => [
            'branches' => ['branches as b', 'b.id', '=', 'u.branch_id'],
            'roles' => ['roles as ro', 'ro.id', '=', 'u.role_id'],
        ],
        'left_joins' => ['branches', 'roles'],
        'fields' => [
            'username' => [
                'label' => 'Username',
                'expr' => 'u.username',
                'type' => 'string',
                'groupable' => true,
            ],
            'full_name' => [
                'label' => 'Full name',
                'expr' => 'u.full_name',
                'type' => 'string',
                'groupable' => true,
            ],
            'branch_name' => [
                'label' => 'Branch',
                'expr' => 'b.branch_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'branches',
            ],
            'role_name' => [
                'label' => 'Role',
                'expr' => 'ro.role_name',
                'type' => 'string',
                'groupable' => true,
                'requires_join' => 'roles',
            ],
            'is_active' => [
                'label' => 'Active',
                'expr' => 'u.is_active',
                'type' => 'string',
                'groupable' => true,
            ],
            'user_count' => [
                'label' => 'Users',
                'expr' => 'u.id',
                'type' => 'number',
                'aggregates' => ['count'],
            ],
        ],
    ],
];
