<?php

/**
 * Shared row keys for blending multiple report-builder data sources.
 * Each dimension maps to a SQL expression per source; metrics are aggregated per key then joined.
 */
return [
    'day' => [
        'label' => 'Day',
        'output_alias' => 'report_day',
        'sources' => [
            'sales' => ['expr' => 'DATE(s.completed_at)', 'date_filter' => 's.completed_at'],
            'sale_items' => ['expr' => 'DATE(s.completed_at)', 'date_filter' => 's.completed_at'],
            'sale_payments' => ['expr' => 'DATE(s.completed_at)', 'date_filter' => 's.completed_at'],
            'returns' => ['expr' => 'DATE(r.created_at)', 'date_filter' => 'r.created_at'],
            'expenses' => ['expr' => 'DATE(e.expense_date)', 'date_filter' => 'e.expense_date'],
            'journal_entries' => ['expr' => 'DATE(je.entry_date)', 'date_filter' => 'je.entry_date'],
            'journal_lines' => ['expr' => 'DATE(je.entry_date)', 'date_filter' => 'je.entry_date'],
            'inventory_transactions' => ['expr' => 'DATE(it.created_at)', 'date_filter' => 'it.created_at'],
            'stock_receipts' => ['expr' => 'DATE(sr.created_at)', 'date_filter' => 'sr.created_at'],
            'stock_movements' => ['expr' => 'DATE(smh.created_at)', 'date_filter' => 'smh.created_at'],
            'damages' => ['expr' => 'DATE(d.created_at)', 'date_filter' => 'd.created_at'],
            'lpo_orders' => ['expr' => 'DATE(lpo.created_at)', 'date_filter' => 'lpo.created_at'],
            'employees' => ['expr' => 'DATE(emp.created_at)', 'date_filter' => 'emp.created_at'],
            'attendance' => ['expr' => 'DATE(ea.attendance_date)', 'date_filter' => 'ea.attendance_date'],
            'payroll_lines' => ['expr' => 'DATE(pr.run_date)', 'date_filter' => 'pr.run_date'],
            'hospitality_checks' => ['expr' => 'DATE(hc.opened_at)', 'date_filter' => 'hc.opened_at'],
            'hospitality_check_lines' => ['expr' => 'DATE(hc.opened_at)', 'date_filter' => 'hc.opened_at'],
            'hospitality_check_payments' => ['expr' => 'DATE(hcp.created_at)', 'date_filter' => 'hcp.created_at'],
            'hospitality_folios' => ['expr' => 'DATE(hf.checked_in_at)', 'date_filter' => 'hf.checked_in_at'],
            'hospitality_folio_charges' => ['expr' => 'DATE(COALESCE(hfc.posted_at, hfc.created_at))', 'date_filter' => 'hfc.created_at'],
            'hospitality_folio_payments' => ['expr' => 'DATE(hfp.created_at)', 'date_filter' => 'hfp.created_at'],
            'hospitality_reservations' => ['expr' => 'hres.arrival_date', 'date_filter' => 'hres.arrival_date'],
            'dispatch_trips' => ['expr' => 'DATE(dt.created_at)', 'date_filter' => 'dt.created_at'],
        ],
    ],
    'month' => [
        'label' => 'Month',
        'output_alias' => 'report_month',
        'sources' => [
            'sales' => ['expr' => "DATE_FORMAT(s.completed_at, '%Y-%m')", 'date_filter' => 's.completed_at'],
            'sale_items' => ['expr' => "DATE_FORMAT(s.completed_at, '%Y-%m')", 'date_filter' => 's.completed_at'],
            'sale_payments' => ['expr' => "DATE_FORMAT(s.completed_at, '%Y-%m')", 'date_filter' => 's.completed_at'],
            'returns' => ['expr' => "DATE_FORMAT(r.created_at, '%Y-%m')", 'date_filter' => 'r.created_at'],
            'expenses' => ['expr' => "DATE_FORMAT(e.expense_date, '%Y-%m')", 'date_filter' => 'e.expense_date'],
            'journal_entries' => ['expr' => "DATE_FORMAT(je.entry_date, '%Y-%m')", 'date_filter' => 'je.entry_date'],
            'journal_lines' => ['expr' => "DATE_FORMAT(je.entry_date, '%Y-%m')", 'date_filter' => 'je.entry_date'],
            'inventory_transactions' => ['expr' => "DATE_FORMAT(it.created_at, '%Y-%m')", 'date_filter' => 'it.created_at'],
            'stock_receipts' => ['expr' => "DATE_FORMAT(sr.created_at, '%Y-%m')", 'date_filter' => 'sr.created_at'],
            'stock_movements' => ['expr' => "DATE_FORMAT(smh.created_at, '%Y-%m')", 'date_filter' => 'smh.created_at'],
            'damages' => ['expr' => "DATE_FORMAT(d.created_at, '%Y-%m')", 'date_filter' => 'd.created_at'],
            'lpo_orders' => ['expr' => "DATE_FORMAT(lpo.created_at, '%Y-%m')", 'date_filter' => 'lpo.created_at'],
            'employees' => ['expr' => "DATE_FORMAT(emp.created_at, '%Y-%m')", 'date_filter' => 'emp.created_at'],
            'attendance' => ['expr' => "DATE_FORMAT(ea.attendance_date, '%Y-%m')", 'date_filter' => 'ea.attendance_date'],
            'payroll_lines' => ['expr' => "DATE_FORMAT(pr.run_date, '%Y-%m')", 'date_filter' => 'pr.run_date'],
            'hospitality_checks' => ['expr' => "DATE_FORMAT(hc.opened_at, '%Y-%m')", 'date_filter' => 'hc.opened_at'],
            'hospitality_check_lines' => ['expr' => "DATE_FORMAT(hc.opened_at, '%Y-%m')", 'date_filter' => 'hc.opened_at'],
            'hospitality_check_payments' => ['expr' => "DATE_FORMAT(hcp.created_at, '%Y-%m')", 'date_filter' => 'hcp.created_at'],
            'hospitality_folios' => ['expr' => "DATE_FORMAT(hf.checked_in_at, '%Y-%m')", 'date_filter' => 'hf.checked_in_at'],
            'hospitality_folio_charges' => ['expr' => "DATE_FORMAT(COALESCE(hfc.posted_at, hfc.created_at), '%Y-%m')", 'date_filter' => 'hfc.created_at'],
            'hospitality_folio_payments' => ['expr' => "DATE_FORMAT(hfp.created_at, '%Y-%m')", 'date_filter' => 'hfp.created_at'],
            'hospitality_reservations' => ['expr' => "DATE_FORMAT(hres.arrival_date, '%Y-%m')", 'date_filter' => 'hres.arrival_date'],
            'dispatch_trips' => ['expr' => "DATE_FORMAT(dt.created_at, '%Y-%m')", 'date_filter' => 'dt.created_at'],
        ],
    ],
    'branch' => [
        'label' => 'Branch',
        'output_alias' => 'branch_name',
        'sources' => [
            'sales' => ['expr' => 'b.branch_name', 'date_filter' => 's.completed_at', 'joins' => ['branches']],
            'sale_items' => ['expr' => 'b.branch_name', 'date_filter' => 's.completed_at', 'joins' => ['branches']],
            'sale_payments' => ['expr' => 'b.branch_name', 'date_filter' => 's.completed_at', 'joins' => ['branches']],
            'returns' => ['expr' => 'b.branch_name', 'date_filter' => 'r.return_date', 'joins' => ['branches']],
            'expenses' => ['expr' => 'b.branch_name', 'date_filter' => 'e.expense_date', 'joins' => ['branches']],
            'journal_entries' => ['expr' => 'b.branch_name', 'date_filter' => 'je.entry_date', 'joins' => ['branches']],
            'journal_lines' => ['expr' => 'b.branch_name', 'date_filter' => 'je.entry_date', 'joins' => ['branches']],
            'inventory_transactions' => ['expr' => 'b.branch_name', 'date_filter' => 'it.transaction_date', 'joins' => ['branches']],
            'stock_receipts' => ['expr' => 'b.branch_name', 'date_filter' => 'sr.receipt_date', 'joins' => ['branches']],
            'employees' => ['expr' => 'b.branch_name', 'date_filter' => 'emp.created_at', 'joins' => ['branches']],
            'attendance' => ['expr' => 'b.branch_name', 'date_filter' => 'ea.attendance_date', 'joins' => ['branches']],
            'payroll_lines' => ['expr' => 'b.branch_name', 'date_filter' => 'pr.run_date', 'joins' => ['branches']],
            'hospitality_checks' => ['expr' => 'b.branch_name', 'date_filter' => 'hc.opened_at', 'joins' => ['branches']],
            'hospitality_check_lines' => ['expr' => 'b.branch_name', 'date_filter' => 'hc.opened_at', 'joins' => ['branches']],
            'hospitality_folios' => ['expr' => 'b.branch_name', 'date_filter' => 'hf.checked_in_at', 'joins' => ['branches']],
            'hospitality_reservations' => ['expr' => 'b.branch_name', 'date_filter' => 'hres.arrival_date', 'joins' => ['branches']],
            'dispatch_trips' => ['expr' => 'b.branch_name', 'date_filter' => 'dt.created_at', 'joins' => ['branches']],
        ],
    ],
    'department' => [
        'label' => 'Department',
        'output_alias' => 'department_name',
        'sources' => [
            'employees' => ['expr' => 'dept.department_name', 'date_filter' => 'emp.created_at', 'joins' => ['departments']],
            'payroll_lines' => ['expr' => 'dept.department_name', 'date_filter' => 'pr.run_date', 'joins' => ['departments']],
        ],
    ],
];
