<?php

/**
 * Production role templates — permission sets and profile recommendations.
 *
 * Roles are global (shared across tenants). On provisioning, the API returns
 * which roles fit the tenant's profile and enabled modules.
 */
return [

    'roles' => [
        'Branch Manager' => [
            'scope' => 'org',
            'description' => 'Day-to-day branch operations: sales, inventory, purchasing, and basic reports.',
            'permissions' => [
                'dashboard.overview.view',
                'sales.dashboard.view',
                'sales.orders.view',
                'sales.orders.create',
                'sales.orders.edit',
                'sales.returns.view',
                'sales.returns.create',
                'sales.vouchers.view',
                'sales.reservations.view',
                'payments.sale_payments.view',
                'payments.sale_payments.create',
                'pos.end_of_day.view',
                'inventory.stock.view',
                'inventory.receipts.view',
                'inventory.movements.view',
                'inventory.transfers.view',
                'inventory.transfers.create',
                'inventory.damages.view',
                'inventory.damages.create',
                'inventory.stock_take.view',
                'purchasing.lpo.view',
                'purchasing.lpo.create',
                'purchasing.lpo.edit',
                'purchasing.lpo.approve',
                'purchasing.suppliers.view',
                'purchasing.supplier_payments.view',
                'purchasing.supplier_payments.create',
                'purchasing.supplier_returns.view',
                'purchasing.supplier_returns.create',
                'customers.customers.view',
                'customers.customers.edit',
                'reports.hub.view',
                'reports.daily_sales.view',
                'reports.stock_on_hand.view',
                'reports.profit_loss.view',
                'admin.branches.view',
                'admin.users.view',
            ],
        ],

        'Cashier' => [
            'scope' => 'branch',
            'description' => 'POS checkout, till sessions, and end-of-day reporting.',
            'requires_modules' => ['sales.pos'],
            'permissions' => [
                'pos.terminal.view',
                'pos.checkout.create',
                'pos.till_management.view',
                'pos.till_management.create',
                'pos.end_of_day.view',
                'catalogue.products.view',
            ],
        ],

        'Warehouse Clerk' => [
            'scope' => 'branch',
            'description' => 'Receiving, stock movements, transfers, and stock take.',
            'requires_modules' => ['inventory'],
            'permissions' => [
                'dashboard.overview.view',
                'inventory.stock.view',
                'inventory.receipts.view',
                'inventory.receipts.create',
                'inventory.movements.view',
                'inventory.transfers.view',
                'inventory.transfers.create',
                'inventory.damages.view',
                'inventory.damages.create',
                'inventory.stock_take.view',
                'inventory.stock_take.create',
                'purchasing.lpo.view',
                'purchasing.suppliers.view',
                'purchasing.supplier_returns.view',
                'purchasing.supplier_returns.create',
            ],
        ],

        'Dispatch Coordinator' => [
            'scope' => 'branch',
            'description' => 'Dispatch board, trips, loading lists, fleet master data, and logistics reports.',
            'requires_modules' => ['distribution'],
            'permissions' => [
                'dashboard.overview.view',
                'fulfillment.overview.view',
                'fulfillment.drivers.view',
                'fulfillment.drivers.create',
                'fulfillment.drivers.edit',
                'fulfillment.vehicles.view',
                'fulfillment.vehicles.create',
                'fulfillment.vehicles.edit',
                'fulfillment.routes.view',
                'fulfillment.routes.create',
                'fulfillment.routes.edit',
                'fulfillment.schedules.view',
                'fulfillment.dispatch.view',
                'fulfillment.dispatch.manage',
                'fulfillment.trips.view',
                'fulfillment.trips.create',
                'fulfillment.trips.edit',
                'fulfillment.picking.view',
                'fulfillment.picking.edit',
                'fulfillment.loading_lists.view',
                'fulfillment.pod.view',
                'sales.orders.view',
                'sales.orders.edit',
                'inventory.stock.view',
                'reports.hub.view',
                'reports.dispatch_trips.view',
                'reports.driver_deliveries.view',
            ],
        ],

        'Mobile Sales Rep' => [
            'scope' => 'branch',
            'description' => 'Field sales on assigned routes via the mobile app.',
            'requires_modules' => ['sales.mobile'],
            'permissions' => [
                'mobile_sales.dashboard.view',
                'mobile_sales.orders.view',
                'mobile_sales.orders.create',
                'mobile_sales.orders.edit',
                'mobile_sales.customers.view',
                'mobile_sales.customers.create',
                'mobile_sales.customers.edit',
                'mobile_sales.catalog.view',
                'mobile_sales.stock.view',
                'mobile_sales.routes.view',
                'mobile_sales.payments.view',
                'mobile_sales.payments.create',
                'sales.orders.create',
                'catalogue.products.view',
                'inventory.stock.view',
                'payments.sale_payments.create',
            ],
        ],

        'Driver' => [
            'scope' => 'branch',
            'description' => 'Mobile delivery runs: view assigned trip stops, navigate to customers, capture POD, and mark deliveries.',
            'requires_modules' => ['sales.mobile', 'distribution'],
            'permissions' => [
                'mobile_driver.trips.view',
                'mobile_driver.deliveries.view',
                'mobile_driver.deliveries.deliver',
                'mobile_driver.pod.view',
                'mobile_driver.pod.create',
                'mobile_driver.cash.view',
                'mobile_driver.cash.create',
            ],
        ],

        'Accountant' => [
            'scope' => 'org',
            'description' => 'General ledger, journals, fiscal periods, and financial reports.',
            'requires_modules' => ['accounting'],
            'permissions' => [
                'dashboard.overview.view',
                'accounting.dashboard.view',
                'accounting.chart_of_accounts.view',
                'accounting.journal_entries.view',
                'accounting.journal_entries.create',
                'accounting.fiscal_periods.view',
                'accounting.general_ledger.view',
                'accounting.trial_balance.view',
                'accounting.profit_loss.view',
                'accounting.balance_sheet.view',
                'accounting.cash_flow.view',
                'accounting.accounts_receivable.view',
                'accounting.accounts_payable.view',
                'accounting.expenses.view',
                'accounting.bank_reconciliation.view',
                'accounting.bank_reconciliation.manage',
                'accounting.export_queue.view',
                'accounting.account_mappings.view',
                'purchasing.supplier_payments.view',
                'admin.payment_methods.view',
                'reports.hub.view',
                'reports.profit_loss.view',
                'reports.expenses.view',
                'reports.journal_register.view',
            ],
        ],

        'Payroll Clerk' => [
            'scope' => 'org',
            'description' => 'Employees, attendance, leave, and payroll processing.',
            'requires_modules' => ['hr_payroll'],
            'permissions' => [
                'dashboard.overview.view',
                'hr.employees.view',
                'hr.departments.view',
                'hr.kpis.view',
                'hr.attendance.view',
                'hr.leave.view',
                'hr.payroll.view',
                'hr.payroll.create',
                'reports.hub.view',
            ],
        ],

        'Viewer' => [
            'scope' => 'branch',
            'description' => 'Read-only access to catalogue, sales, stock, and basic reports.',
            'permissions' => [
                'dashboard.overview.view',
                'catalogue.products.view',
                'catalogue.categories.view',
                'sales.dashboard.view',
                'sales.orders.view',
                'inventory.stock.view',
                'purchasing.lpo.view',
                'purchasing.suppliers.view',
                'customers.customers.view',
                'reports.hub.view',
                'reports.daily_sales.view',
                'reports.stock_on_hand.view',
            ],
        ],
    ],

    /** Default role names suggested per deployment profile (before module filtering). */
    'profile_roles' => [
        'small_shop' => ['Branch Manager', 'Warehouse Clerk', 'Viewer'],
        'supermarket' => ['Branch Manager', 'Cashier', 'Warehouse Clerk', 'Viewer'],
        'wholesale_retail' => [
            'Branch Manager',
            'Cashier',
            'Warehouse Clerk',
            'Mobile Sales Rep',
            'Accountant',
            'Payroll Clerk',
            'Viewer',
        ],
        'distribution' => [
            'Branch Manager',
            'Warehouse Clerk',
            'Dispatch Coordinator',
            'Mobile Sales Rep',
            'Driver',
            'Accountant',
            'Viewer',
        ],
        'custom' => ['Branch Manager', 'Viewer'],
    ],

    /** Extra roles added for custom setups when specific modules are enabled. */
    'module_roles' => [
        'sales.pos' => ['Cashier'],
        'sales.mobile' => ['Mobile Sales Rep', 'Driver'],
        'distribution' => ['Dispatch Coordinator'],
        'inventory' => ['Warehouse Clerk'],
        'accounting' => ['Accountant'],
        'hr_payroll' => ['Payroll Clerk'],
    ],

];
