<?php

/**
 * Production role templates — permission sets and profile recommendations.
 *
 * Roles are global (shared across tenants). Each template is tagged with
 * `industries` so Retail & Distribution vs Hotel & Hospitality stay separate
 * in role pickers and provisioning recommendations.
 */
return [

    'roles' => [
        'Branch Manager' => [
            'scope' => 'org',
            'industries' => ['commerce'],
            'description' => 'Day-to-day branch operations: sales, inventory, purchasing, and basic reports.',
            'permissions' => [
                'dashboard.overview.view',
                'dashboard.sales.view',
                'dashboard.inventory.view',
                'sales.orders.view',
                'sales.orders.create',
                'sales.orders.edit',
                'sales.returns.view',
                'sales.returns.create',
                'sales.vouchers.view',
                'sales.reservations.view',
                'payments.sale_payments.view',
                'payments.sale_payments.create',
                'pos.end_of_day.view',
                'pos.payments_breakdown.view',
                'inventory.stock.view',
                'inventory.receipts.view',
                'inventory.movements.view',
                'inventory.transfers.view',
                'inventory.transfers.create',
                'inventory.damages.view',
                'inventory.damages.create',
                'inventory.stock_take.view',
                'inventory.stock_take.approve',
                'inventory.adjustments.create',
                'purchasing.lpo.view',
                'purchasing.lpo.create',
                'purchasing.lpo.edit',
                'purchasing.lpo.delete',
                'purchasing.lpo.approve',
                'purchasing.suppliers.view',
                'purchasing.supplier_payments.view',
                'purchasing.supplier_payments.create',
                'purchasing.supplier_returns.view',
                'purchasing.supplier_returns.create',
                'customers.customers.view',
                'customers.customers.edit',
                'reports.hub.view',
                'reports.daily_sales.view',
                'reports.stock_on_hand.view',
                'reports.profit_loss.view',
                'admin.branches.view',
                'admin.users.view',
            ],
        ],

        'Cashier' => [
            'scope' => 'branch',
            'industries' => ['commerce'],
            'description' => 'External POS terminal and checkout. Grant Till management / End of day under Backoffice when they need those screens.',
            'requires_modules' => ['sales.pos'],
            'permissions' => [
                'pos.terminal.view',
                'pos.checkout.create',
                // Open/close till on the terminal — not the Backoffice Till management screen (view).
                'pos.till_management.create',
                'catalogue.products.view',
            ],
        ],

        'Warehouse Clerk' => [
            'scope' => 'branch',
            'industries' => ['commerce'],
            'description' => 'Receiving, stock movements, transfers, and stock take.',
            'requires_modules' => ['inventory'],
            'permissions' => [
                'dashboard.overview.view',
                'dashboard.inventory.view',
                'inventory.stock.view',
                'inventory.receipts.view',
                'inventory.receipts.create',
                'inventory.movements.view',
                'inventory.transfers.view',
                'inventory.transfers.create',
                'inventory.damages.view',
                'inventory.damages.create',
                'inventory.stock_take.view',
                'inventory.stock_take.create',
                'purchasing.lpo.view',
                'purchasing.suppliers.view',
                'purchasing.supplier_returns.view',
                'purchasing.supplier_returns.create',
            ],
        ],

        'Dispatch Coordinator' => [
            'scope' => 'branch',
            'industries' => ['commerce'],
            'description' => 'Dispatch board, trips, loading lists, fleet master data, and logistics reports.',
            'requires_modules' => ['distribution'],
            'permissions' => [
                'dashboard.overview.view',
                'fulfillment.overview.view',
                'fulfillment.drivers.view',
                'fulfillment.drivers.create',
                'fulfillment.drivers.edit',
                'fulfillment.vehicles.view',
                'fulfillment.vehicles.create',
                'fulfillment.vehicles.edit',
                'fulfillment.routes.view',
                'fulfillment.routes.create',
                'fulfillment.routes.edit',
                'fulfillment.schedules.view',
                'fulfillment.dispatch.view',
                'fulfillment.dispatch.manage',
                'fulfillment.trips.view',
                'fulfillment.trips.create',
                'fulfillment.trips.edit',
                'fulfillment.picking.view',
                'fulfillment.picking.edit',
                'fulfillment.loading_lists.view',
                'fulfillment.pod.view',
                'sales.orders.view',
                'sales.orders.edit',
                'inventory.stock.view',
                'reports.hub.view',
                'reports.dispatch_trips.view',
                'reports.driver_deliveries.view',
            ],
        ],

        'Mobile Sales Rep' => [
            'scope' => 'branch',
            'industries' => ['commerce'],
            'description' => 'Field sales on assigned routes via the mobile app.',
            'requires_modules' => ['sales.mobile'],
            'permissions' => [
                'mobile_sales.dashboard.view',
                'mobile_sales.orders.view',
                'mobile_sales.orders.create',
                'mobile_sales.orders.edit',
                'mobile_sales.customers.view',
                'mobile_sales.customers.create',
                'mobile_sales.customers.edit',
                'mobile_sales.catalog.view',
                'mobile_sales.stock.view',
                'mobile_sales.routes.view',
                'mobile_sales.payments.view',
                'mobile_sales.payments.create',
                'sales.orders.create',
                'catalogue.products.view',
                'inventory.stock.view',
                'payments.sale_payments.create',
            ],
        ],

        'Driver' => [
            'scope' => 'branch',
            'industries' => ['commerce'],
            'description' => 'Mobile delivery runs: view assigned trip stops, navigate to customers, capture POD, and mark deliveries.',
            'requires_modules' => ['sales.mobile', 'distribution'],
            'permissions' => [
                'mobile_driver.trips.view',
                'mobile_driver.deliveries.view',
                'mobile_driver.deliveries.deliver',
                'mobile_driver.pod.view',
                'mobile_driver.pod.create',
                'mobile_driver.cash.view',
                'mobile_driver.cash.create',
            ],
        ],

        'Field Manager' => [
            'scope' => 'branch',
            'industries' => ['commerce'],
            'description' => 'Centrix Manager app: approvals, executive dashboard, and operational reports.',
            'requires_modules' => ['sales.backend'],
            'permissions' => [
                'mobile_manager.app.access',
                'mobile_manager.dashboard.view',
                'mobile_manager.approvals.view',
                'mobile_manager.approvals.approve',
                'mobile_manager.approvals.reject',
                'mobile_manager.notifications.view',
                'mobile_manager.notifications.manage',
                'mobile_manager.reports.view',
                'sales.orders.approve',
                'reports.hub.view',
                'reports.daily_sales.view',
                'reports.top_debtors.view',
                'reports.stock_on_hand.view',
            ],
        ],

        'Hotel Cashier' => [
            'scope' => 'branch',
            'industries' => ['hospitality'],
            'description' => 'Hotel POS: open checks, settle, and room charge to guest folios.',
            'requires_modules' => ['hospitality.bar_pos'],
            'permissions' => [
                'hotel_bar_pos.terminal.view',
                'hotel_bar_pos.checks.view',
                'hotel_bar_pos.checks.create',
                'hotel_bar_pos.checks.edit',
                'hotel_bar_pos.room_charge.create',
                'catalogue.products.view',
            ],
        ],

        'Front Desk' => [
            'scope' => 'branch',
            'industries' => ['hospitality'],
            'description' => 'Reservations, check-in/out, guest folios, housekeeping, and night audit.',
            'requires_modules' => ['hospitality.backend'],
            'permissions' => [
                'hospitality.dashboard.view',
                'hospitality.rooms.view',
                'hospitality.reservations.view',
                'hospitality.reservations.create',
                'hospitality.reservations.edit',
                'hospitality.frontdesk.view',
                'hospitality.frontdesk.edit',
                'hospitality.folios.view',
                'hospitality.folios.create',
                'hospitality.folios.edit',
                'hospitality.housekeeping.view',
                'hospitality.housekeeping.edit',
                'hospitality.night_audit.view',
                'hospitality.night_audit.create',
            ],
        ],

        'Hotel Store Keeper' => [
            'scope' => 'branch',
            'industries' => ['hospitality'],
            'description' => 'Hotel store receiving, stock movements, and LPO visibility.',
            'requires_modules' => ['inventory'],
            'permissions' => [
                'dashboard.overview.view',
                'dashboard.inventory.view',
                'inventory.stock.view',
                'inventory.receipts.view',
                'inventory.receipts.create',
                'inventory.movements.view',
                'inventory.transfers.view',
                'inventory.transfers.create',
                'inventory.damages.view',
                'inventory.damages.create',
                'inventory.stock_take.view',
                'inventory.stock_take.create',
                'purchasing.lpo.view',
                'purchasing.suppliers.view',
                'purchasing.supplier_returns.view',
                'purchasing.supplier_returns.create',
                'catalogue.products.view',
            ],
        ],

        'Hotel Manager' => [
            'scope' => 'org',
            'industries' => ['hospitality'],
            'description' => 'Hotel operations lead: front desk, F&B stock, purchasing, and hotel reports.',
            'permissions' => [
                'hospitality.dashboard.view',
                'hospitality.outlets.view',
                'hospitality.outlets.create',
                'hospitality.outlets.edit',
                'hospitality.rooms.view',
                'hospitality.rooms.create',
                'hospitality.rooms.edit',
                'hospitality.reservations.view',
                'hospitality.reservations.create',
                'hospitality.reservations.edit',
                'hospitality.frontdesk.view',
                'hospitality.frontdesk.edit',
                'hospitality.folios.view',
                'hospitality.folios.create',
                'hospitality.folios.edit',
                'hospitality.housekeeping.view',
                'hospitality.housekeeping.edit',
                'hospitality.night_audit.view',
                'hospitality.night_audit.create',
                'hospitality.orders.view',
                'hospitality.payments_breakdown.view',
                'hospitality.reports.view',
                'hospitality.settings.view',
                'hospitality.settings.edit',
                'hotel_bar_pos.terminal.view',
                'hotel_bar_pos.checks.view',
                'dashboard.overview.view',
                'dashboard.inventory.view',
                'catalogue.products.view',
                'catalogue.products.create',
                'catalogue.products.edit',
                'catalogue.categories.view',
                'catalogue.categories.create',
                'catalogue.categories.edit',
                'catalogue.uoms.view',
                'catalogue.uoms.create',
                'catalogue.uoms.edit',
                'inventory.stock.view',
                'inventory.receipts.view',
                'inventory.receipts.create',
                'inventory.transfers.view',
                'inventory.transfers.create',
                'inventory.stock_take.view',
                'inventory.stock_take.approve',
                'purchasing.lpo.view',
                'purchasing.lpo.create',
                'purchasing.lpo.edit',
                'purchasing.lpo.delete',
                'purchasing.lpo.approve',
                'purchasing.suppliers.view',
                'reports.hub.view',
                'reports.stock_on_hand.view',
                'admin.branches.view',
                'admin.users.view',
            ],
        ],

        'Accountant' => [
            'scope' => 'org',
            'industries' => ['commerce', 'hospitality'],
            'description' => 'General ledger, journals, fiscal periods, and financial reports.',
            'requires_modules' => ['accounting'],
            'permissions' => [
                'accounting.dashboard.view',
                'accounting.chart_of_accounts.view',
                'accounting.journal_entries.view',
                'accounting.journal_entries.create',
                'accounting.fiscal_periods.view',
                'accounting.general_ledger.view',
                'accounting.trial_balance.view',
                'accounting.profit_loss.view',
                'accounting.balance_sheet.view',
                'accounting.cash_flow.view',
                'accounting.accounts_receivable.view',
                'accounting.accounts_payable.view',
                'accounting.expenses.view',
                'accounting.bank_reconciliation.view',
                'accounting.bank_reconciliation.manage',
                'accounting.export_queue.view',
                'accounting.account_mappings.view',
                'admin.payment_methods.view',
                'reports.profit_loss.view',
                'reports.expenses.view',
                'reports.journal_register.view',
                'reports.kra_compliance_summary.view',
                'reports.kra_receipts.view',
                'reports.kra_unfiscalized_sales.view',
            ],
        ],

        'Payroll Clerk' => [
            'scope' => 'org',
            'industries' => ['commerce', 'hospitality'],
            'description' => 'Employees, attendance, leave, and payroll processing.',
            'requires_modules' => ['hr_payroll'],
            'permissions' => [
                'hr.employees.view',
                'hr.departments.view',
                'hr.kpis.view',
                'hr.attendance.view',
                'hr.leave.view',
                'hr.payroll.view',
                'hr.payroll.create',
                'reports.payroll_summary.view',
            ],
        ],

        'Viewer' => [
            'scope' => 'branch',
            'industries' => ['commerce', 'hospitality'],
            'description' => 'Read-only access to catalogue, stock, and basic reports.',
            'permissions' => [
                'dashboard.overview.view',
                'catalogue.products.view',
                'catalogue.categories.view',
                'dashboard.sales.view',
                'sales.orders.view',
                'dashboard.inventory.view',
                'inventory.stock.view',
                'purchasing.lpo.view',
                'purchasing.suppliers.view',
                'customers.customers.view',
                'hospitality.dashboard.view',
                'hospitality.rooms.view',
                'hospitality.reservations.view',
                'reports.hub.view',
                'reports.daily_sales.view',
                'reports.stock_on_hand.view',
            ],
        ],
    ],

    /** Default role names suggested per deployment profile (before module filtering). */
    'profile_roles' => [
        'small_shop' => ['Branch Manager', 'Warehouse Clerk', 'Viewer'],
        'supermarket' => ['Branch Manager', 'Cashier', 'Warehouse Clerk', 'Viewer'],
        'wholesale_retail' => [
            'Branch Manager',
            'Cashier',
            'Warehouse Clerk',
            'Mobile Sales Rep',
            'Field Manager',
            'Accountant',
            'Payroll Clerk',
            'Viewer',
        ],
        'distribution' => [
            'Branch Manager',
            'Warehouse Clerk',
            'Dispatch Coordinator',
            'Mobile Sales Rep',
            'Driver',
            'Accountant',
            'Viewer',
        ],
        'hotel_bar' => [
            'Hotel Manager',
            'Hotel Cashier',
            'Front Desk',
            'Hotel Store Keeper',
            'Accountant',
            'Payroll Clerk',
            'Viewer',
        ],
        'custom' => ['Branch Manager', 'Viewer'],
    ],

    /** Extra roles added for custom setups when specific modules are enabled. */
    'module_roles' => [
        'sales.pos' => ['Cashier'],
        'sales.mobile' => ['Mobile Sales Rep', 'Driver'],
        'sales.backend' => ['Field Manager'],
        'distribution' => ['Dispatch Coordinator'],
        'inventory' => ['Warehouse Clerk'],
        'accounting' => ['Accountant'],
        'hr_payroll' => ['Payroll Clerk'],
        'hospitality.bar_pos' => ['Hotel Cashier'],
        'hospitality.backend' => ['Front Desk', 'Hotel Manager'],
    ],

];
